### ISSUE TITLE
Support 8UC3 image encoding

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#1044]
Found in `2017-10-26-V2-Log1.bag` (https://ford-multi-av-seasonal.s3-us-west-2.amazonaws.com/2017-10-26/V2/Log1/2017-10-26-V2-Log1.bag)

**Comment by jtbandes** [comment]
Relevant code: https://github.com/foxglove/studio/blob/main/app/panels/ImageView/decodings.ts
