### ISSUE TITLE
Further customization of geometry_msgs/PoseStamped

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#1049]
From https://github.com/cruise-automation/webviz/issues/586.

> I would like to visualize messages of the type geometry_msgs/PoseStamped using a rendered Arrow, but the arrow length is always defaulted to 2.0m. I I would like to have much smaller arrows (centimeter-long) for better visualization of my application. The only portions of the arrow that are configurable are the head and its width. It would be great if we could also configure the Shaft Length (see below for the available configurations for geometry_msgs/PoseStamped arrow)

![106826948-8aac6180-664d-11eb-8c4b-acd58d66a886](https://user-images.githubusercontent.com/195374/119057016-8ef05680-b980-11eb-8c26-2139ee142e7d.png)

**Comment by amacneil** [comment]
While we're here, let's change the arrow default dimensions to actually be an arrow and not a cylinder.

**Comment by jhurliman** [comment]
Implemented in New3d
