### ISSUE TITLE
Invalid layout file breaks layout list

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1054]
If an invalid layout file (or an invisible file that isn't a layout at all, like `.DS_Store` added automatically by Finder), listing layouts throws an error and you can no longer see the other layouts in the app:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/14237/119207390-c707a000-ba39-11eb-9349-b4148afafc6c.png">

**Comment by defunctzombie** [comment]
@jtbandes assigned to you since it might be related to the layout work you are currently doing - would be nice to fix this up while in there
