### ISSUE TITLE
Remove YAML support

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#1102]
The fact that various parts of the app support YAML input/output is not well surfaced and doesn't appear in our documentation anywhere. The `js-yaml` dependency is fairly heavy, I propose we remove it.

**Comment by defunctzombie** [comment]
👍 Whats the effort to remove it?

Why is it a heavy dependency?

**Comment by jhurliman** [comment]
It looks straightforward, I'll open a proposal PR shortly. The YAML spec is vast (it's just a few features short of a programming language), and the final minified `js-yaml` weighs in over 200KB that gets bundled into both the renderer bundle and the main process bundle.
