### ISSUE TITLE
Support int64/uint64 data

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1125]
Currently int64/uint64 fields from ROS msgs are parsed as JavaScript `bigint`s. However, these values can't be plotted or displayed in Raw Messages. Work will need to be done in individual panels that we want to support `bigint`s.

TODO:

- [x] #1730
- [x] #1302

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/pull/1294 solves this for RawMessages.

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/pull/1298 adds node playground support

**Comment by defunctzombie** [comment]
Both items are marked as complete.
