### ISSUE TITLE
display recommendation to switch to Chome

### ISSUE THREAD

**Issue by wkalt** [foxglove/studio#1132]
In the web build at studio.foxglove.dev, a firefox user will see this on page load (before attempting to load a bag):

![2021-06-01_16-54](https://user-images.githubusercontent.com/4952091/120403931-197a7380-c2fa-11eb-844f-8276cbe03df5.png)

Firefox support isn't a requirement for us today, but we should display a message to try the site with Chrome, rather than the error.

**Comment by jhurliman** [comment]
The error is:

```
Error: Chart requires browsers with offscreen canvas support
    <anonymous> index.tsx:144
```

**Comment by amacneil** [comment]
I think we should take down the web build for now since it is not officially supported. It can stay up on a non public domain.
