### ISSUE TITLE
Display notification when plot downsamples data

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1158]
The plot panel downsamples data to improve performance for large data sets. For unaware users the downsampling appears as data loss or incomplete data and they wonder if something is broken.

We should display a notice indicating data has been downsampled and that zooming in will show higher fidelity data.

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/pull/1188 dialed down the aggressiveness of the downsampling and made the data points a bit smaller to accommodate the denser data.

Another idea instead of a notification is to show lines only (no data points) when the data is downsampled as a visual hint.

**Comment by amacneil** [comment]
I'm not convinced that we need this. Every metrics/charting platform I have used downsamples data over a large time window.
