### ISSUE TITLE
3D panel can not display tf_static frames

### ISSUE THREAD

**Issue by ScottYang1982** [foxglove/studio#1201]
**3D** panel can not display /tf_static frames.

**Comment by defunctzombie** [comment]
@ScottYang1982 Could you elaborate a bit more on the issue? What do you mean by cannot display? If you could provide a sample bag file and a few notes on the behavior you expected that would be helpful.

**Comment by jhurliman** [comment]
Fixed in https://github.com/foxglove/studio/pull/2291
