### ISSUE TITLE
Feature request: watch playback time in extensions

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1248]
Example use case - showing a line on a plot indicating where the current playback time is. As playback progresses this line would sweep across the plot providing a visual indicator to help the user relate other panel data to the location on the plot.

**Comment by jhurliman** [comment]
@defunctzombie I thought this was added to the extension API?

**Comment by defunctzombie** [comment]
We added _previewTime_ https://github.com/foxglove/studio/blob/main/packages/studio/index.d.ts#L103 which is the value when a user hovers over a plot or map panel location and we want to "click-to-seek" but we did not add currentTime yet.
