### ISSUE TITLE
Feature request: Support an .@index modifier in message path syntax

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1254]
# Current Behavior

There is no way to use message path syntax to:
- get the index of a certain element in a message's array
- calculate expressions within array brackets

# Desired Behavior

Write something like `/some_topic.some_array.@index("dog")` to get the index of the value "dog" in the array `/some_topic.some_array`.

This will not account for arrays of objects – just arrays of primitives (strings and numbers will probably be most useful).

Also write something like `/some_topic.another_array[/some_topic.some_array.@index("dog")]` - should interpret `/some_topic.some_array.@index("dog")` first, and then interpret the rest of the path as usual.

# Context

Came up as possible solution for https://github.com/foxglove/studio/issues/1232 

# Description

Use message path syntax to:
- get the index of a certain element in a message's array
- calculate expressions within array brackets

# Possible Implementation

- Edit `grammar.ne` (caveat that any `.@___` modifiers will not work outside the Plot panel, as the codebase stands)

**Comment by amacneil** [comment]
I find the `.@foo` modifiers a bit weird-looking. However, it would be nice to standardize these and get them working outside of the plot panel.

I might also advocate for `indexOf` over just `index`?

Throwing out some alternative syntax ideas:
1. Functions, e.g. `indexOf("/some_topic.some_array", "dog")` or `abs(/some_topic.some_value)` (quotes could probably be optional) - for prior art see [github actions docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions)
2. Do we need to differentiate functions at all? What about just `/some_topic.some_array.indexOf(dog)` and `/some_topic.somevalue.sin()`? We could either use knowledge of the message, or the presence of quotes to know that it's a function.
3. Pipe modifiers? `/some_topic.some_array|indexOf(dog)` (including for completeness, but I don't actually like this)

Of these, I think I like the look of option 2 best. Open to other thoughts.
