### ISSUE TITLE
Node Playground should support publishing common ROS datatypes even if they're not in the bag

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1261]
Split from #726 

The common datatypes introduced in #1038 should be exposed to Node Playground code so that it can use common ROS datatypes even if they are not in the bag/data source.

There is currently a hack specifically to allow publishing `visualization_msgs/MarkerArray`: 

https://github.com/foxglove/studio/blob/860b4df2cad85a39bca022749f80a0a48c6a8796/app/players/UserNodePlayer/nodeTransformerWorker/typescript/ast.ts#L322-L323

**Comment by jtbandes** [comment]
I just discovered there is some logic that translates `a_msgs__B` to `a_msgs/B` in the transformation code: https://github.com/foxglove/studio/blob/ffe3c722d645ede0e7f81d69002261bd59762c60/packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/transformer.ts#L365-L368

**Comment by bunnyc1986** [comment]
I found the fix it to add `basicDatatypes` into the `generateRosLib`'s `datatypes` Map

https://github.com/foxglove/studio/blob/main/packages/studio-base/src/players/UserNodePlayer/index.ts#L578-L581

to 
```
    const rosLib: string = await transformWorker.send("generateRosLib", {
      topics,
      datatypes: new Map([...basicDatatypes, ...datatypes]),
    });
```
