### ISSUE TITLE
Update Message Path filter syntax to support bigints

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1302]
As follow-up / related work to #1297 & #1298, the message path syntax needs to be updated to support bigints as filter values. Currently it uses parseInt on the filter expression:

https://github.com/foxglove/studio/blob/1b950be6616faab3dd85b688b0c49e18ae611667/packages/studio-base/src/components/MessagePathSyntax/grammar.ne#L26-L28

And applies the filter by comparing with `==`:

https://github.com/foxglove/studio/blob/1b950be6616faab3dd85b688b0c49e18ae611667/packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts#L143-L146

This leads to surprising/incorrect filter results when filtering on bigint (int64/uint64) values:

![](https://user-images.githubusercontent.com/14237/123317059-6fe66680-d4e2-11eb-9545-f8609ee9d285.png)

**Comment by defunctzombie** [comment]
Fixed in https://github.com/foxglove/studio/pull/1445
