### ISSUE TITLE
Fix flaky ImageCanvas Markers screenshot

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1328]
The Markers screenshot is flaky, particularly it seems that the interpolation mode seems to vary between runs. This was probably a regression with #1046.

The rendering mode is changed here, which seems like it happens during initialization, so I'm not sure what would cause flakiness — perhaps the use of a worker / offscreen canvas.

https://github.com/foxglove/studio/blob/7c86b5b561becd451981d7d600c93f0d16e52ee0/packages/studio-base/src/panels/ImageView/ImageCanvas.tsx#L187:L187

**Comment by defunctzombie** [comment]
Fixed within https://github.com/foxglove/studio/pull/1367
