### ISSUE TITLE
Add _blank target to various anchor tags

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1332]
In https://github.com/foxglove/studio/pull/1329 I removed the _blank target attribute for anchor tags since they are no longer necessary for studio. They are still necessary for web to avoid the user replacing the current studio page with the target page.

**Comment by jtbandes** [comment]
I know we've filed some tickets for specific instances of this issue, e.g. https://github.com/foxglove/studio/issues/2438

Is there any general solution or lint rule to be made here? Any reason to keep this ticket open?

**Comment by defunctzombie** [comment]
Closing. We fixed this for the desktop for all links. For web we need to be more diligent as 2438 notes.

**Comment by jtbandes** [comment]
I think this ticket was about web though...

**Comment by defunctzombie** [comment]
Yea - I think its better for us to fix this when we find it. Maybe a lint rule or component. We can keep 2438 open as our more active ticket since it shows a specific case within the app.
