### ISSUE TITLE
Plot tooltip only allows viewing data from one dataset

### ISSUE THREAD

**Issue by lucabonamini** [foxglove/studio#1344]
**Description**
When more than one timeseries is loaded in a Plot panel, tooltip shows data of the first loaded only on hover.

- Version: 0.12.0
- OS: Ubuntu 18.04

**Steps To Reproduce**
![Screenshot from 2021-06-30 15-19-35](https://user-images.githubusercontent.com/24660508/123971034-fa830600-d9b9-11eb-815f-007fd3441898.png)

**Expected Behavior**
Tooltip should have data relatives to all the timeseries loaded.

**Actual Behavior**
Tooltip shows data of the first timeseries loaded only.

**Comment by jtbandes** [comment]
Related: #1113

**Comment by jetdillo** [comment]
I could really use a fix for this issue as I have my graphs configured to aggregate the data.* elements from a topic (like /imu/data.orientation.*) onto a single graph panel to more easily compare them against each other vs. split out into separate panels.

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/pull/1835 This allows for hovering near the other dataset points to see their values to fix parts of the poor UX described in this issue.

I think it could make sense to handle scatter and time series differently and display all the intersected x-axis values in one tooltip for time based plots so I will leave this issue open.
