### ISSUE TITLE
URDFViewer sentry error when there is no joint state name

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1345]
**Description**

```
TypeError: Cannot read property 'forEach' of undefined
```

![image](https://user-images.githubusercontent.com/84792/123975404-28dcf300-d972-11eb-9018-dbf18877a0f2.png)

- Version: 0.12.0
- OS: Ubuntu 18.04

https://sentry.io/organizations/foxglove/issues/2484956494/?project=5649767&referrer=slack

**Comment by jtbandes** [comment]
Any repro steps? How is there no name? Was this using node playground?

Lots of panels assume messages conform to a certain shape based on the datatype name. Adding `?.` everywhere seems like overkill and we’d need to change all our types to be DeepPartial to enforce it. So maybe we need more of an upfront validation step? (But running this on each message could be expensive)

**Comment by defunctzombie** [comment]
I've not tried to repro - only hoisted the sentry error to a github issue. Might be doable to reproduce with node playground. Either we need the panels to be more defensive or a better mechanism to catch the errors within the panel to prevent them bubbling to sentry. Tho if we do catch the error in the panel it will be rather opaque for the user what action to take unless we do perform some sort of validations on the messages.

**Comment by jtbandes** [comment]
Closing since the Sentry issue was resolved due to inactivity, and the error doesn't seem particularly actionable unless we know more about how to reproduce it. Only 1 instance was ever recorded in Sentry.
