### ISSUE TITLE
Convert class components to function components

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1426]
Some components remain using classes. They should be assimilated into the function component borg.

- [x] packages/studio-base/src/components/Autocomplete.tsx
- [x] packages/studio-base/src/components/ButtonBase.tsx
- [ ] packages/studio-base/src/components/Dropdown/index.tsx https://github.com/foxglove/studio/pull/2141
- [ ] packages/studio-base/src/components/KeyListener.tsx https://github.com/foxglove/studio/pull/2142
- [x] packages/studio-base/src/components/Menu/Menu.tsx
- [ ] ~~packages/studio-base/src/components/Menu/SubMenu.tsx~~ We will replace this with Fluent or MUI
- [x] #1568
- [x] packages/studio-base/src/components/NotificationDisplay.tsx
- [x] packages/studio-base/src/components/Select/Option.tsx #1542
- [x] packages/studio-base/src/components/Select/Select.tsx #1542
- [x] packages/studio-base/src/components/Slider.tsx
- [ ] packages/studio-base/src/panels/ThreeDimensionalViz/DrawingTools/MeasuringTool.ts https://github.com/foxglove/studio/pull/2451
- [x] packages/studio-base/src/panels/diagnostics/DiagnosticStatus.tsx
- [x] packages/studio-base/src/panels/diagnostics/DiagnosticSummary.tsx

**Comment by jtbandes** [comment]
Several of these should be removed and replaced with FluentUI:
- #703 
- #705 
- #702

**Comment by defunctzombie** [comment]
Closing this out - The remaining items of interest have open PRs and we will track those individually.
