### ISSUE TITLE
Warning banner for unsupported browsers

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1490]
**Description**
studio.foxglove.dev is fussy about which browsers it works on. We are tracking cross-browser work in https://github.com/foxglove/studio/issues/1511.

In the meantime, we should display a banner across the top of the window for unsupported browsers encouraging them to try Chrome for now, and linking to a Github meta-ticket.

On my current gen iphone/iOS, I get nothing but a white screen. In this case we should display the same warning and ensure that it doesn't require our javascript bundle to load.

**Comment by defunctzombie** [comment]
I think this is done with #1502 - please re-open with updated description if you think more should be done.
