### ISSUE TITLE
Add "Download App" CTA to web build; Allow visitors to easily navigate back to foxglove.dev

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1537]
Currently no obvious way to go from web build demo to an app download page.

Adding this button would be useful before web build has login flow.

**Comment by amacneil** [comment]
I think this is a good idea but let’s not make it too distracting. A sidebar icon with red “unread messages” bubble or something unobtrusive like that?

@2metres probably has better suggestions
