### ISSUE TITLE
Windows version initializes with blank screen

### ISSUE THREAD

**Issue by mikepianka** [foxglove/studio#1552]
**Description**
I just tried installing and running the Windows version. When I open the app, I see some content briefly flash but then the window goes blank.

- Version: latest
- OS: Windows 10 19043.1083

**Steps To Reproduce**
Install the Windows version and run it. The window opens, flashes some content, then goes blank like this:

![image](https://user-images.githubusercontent.com/47948499/126783605-6deb579c-19b2-4a34-a8a3-072c8ef150fd.png)

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment]
@mikepianka If you open developer tools (View -> Advanced -> Toggle Developer Tools) are there any obvious errors?

**Comment by mikepianka** [comment]
After restarting my machine I reopened Studio and it displayed as expected. But, after closing Studio and reopening it, I get the blank screen again. Developer tools does not bring up anything because it says it has been disconnected.

![image](https://user-images.githubusercontent.com/47948499/126793133-0a7cd48c-9134-49a9-8d41-7cf65f89fc88.png)

**Comment by defunctzombie** [comment]
@mikepianka Thanks for doing that troubleshooting with me - when devtools shows disconnected that means an internal process crashed (v8 or the web process to be more specific). We have an theory on what this might be - seems to be related to a font rendering bug we're seeing in our application crash reports after a recent font change. We'll get a fix today and get you a version to test to see if it resolves your issue.

**Comment by amacneil** [comment]
Are you using a HiDPI/retina screen on windows by any chance? In the past when we’ve seen this that was a contributing factor.

**Comment by mikepianka** [comment]
Ok thanks for the quick response. I'm just using some standard HD monitors, nothing fancy.

**Comment by amacneil** [comment]
@mikepianka can you try v0.13.3 which we just released?

**Comment by amacneil** [comment]
Fixed in https://github.com/foxglove/studio/commit/c5f97f2619cec40118132f7ab48f2b36c3493c91

**Comment by mikepianka** [comment]
Thanks for the fix. I have been away from my workstation and haven't had a chance to try it yet. I will give it a go tomorrow.

**Comment by mikepianka** [comment]
It's fixed and working as expected now. Thanks again 👏

**Comment by amacneil** [comment]
Excellent!
