### ISSUE TITLE
Move packages/ros1-turtlesim-test to separate repo

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1582]
Since ros1 package is moved out - time for this one to find a new home. Could be within the ros1 package - maybe an examples folder - or a separate repo as a standalone example. Whatever makes sense for user discovery. Maybe this was only useful for initial testing and no more.

**Comment by jhurliman** [comment]
Fixed in https://github.com/foxglove/ros1/pull/14

**Comment by defunctzombie** [comment]
👍 Seems turtlesim was moved out of this repo long ago anyhow 👋 🐢
