### ISSUE TITLE
Overflowing link text in sign-in dialog

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1586]
**Description**

The activation link text overflows the sign-in dialog boundary.

<img width="366" alt="Screen Shot 2021-07-29 at 3 31 23 PM" src="https://user-images.githubusercontent.com/6993359/127930027-2c739bb7-e67e-4434-8130-15f060c03184.png">

- Version: 0.13.3
- OS: macOS

**Steps To Reproduce**

- Make Foxglove Studio app narrow (~half your screen width).
- Go through sign-in flow (via Layouts tab in sidebar menu).
- See the activation link's text overflowing past the dialog boundary.

**Expected Behavior**
The link text should wrap.

**Actual Behavior**
The link text disappears past the boundaries of the dialog.

**Comment by defunctzombie** [comment]
Fixed in https://github.com/foxglove/studio/pull/1590

The container will try to fit the link text and only when the window is so narrow that that link text can't even fit in the window does it start to get cut off.
