### ISSUE TITLE
First entry in Add Panel is highlighted

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#1589]
**Description**

When I open the Add Panel sidebar, the first entry in the list, "3D", is highlighted by default. It stays highlighted even if you mouseover other entries. This makes it read like it is a grouping header instead of one of the panels. 

<img width="380" alt="image" src="https://user-images.githubusercontent.com/108767/128086894-5e27f7c2-742b-46c5-8c47-16da8110335b.png">

- Version: 0.14.0
- OS: macOS

**Comment by jtbandes** [comment]
FYI, it's highlighted because the list supports keyboard navigation. You can press up/down arrow keys to select items. Not saying this is ideal, just an explanation of why it's like this.

**Comment by rgov** [comment]
On Mac apps, such as the Finder, the first time you hit <kbd>↓</kbd> it highlights the first row. If you hit <kbd>↑</kbd> it highlights the last row.

**Comment by amacneil** [comment]
> On Mac apps, such as the Finder, the first time you hit ↓ it highlights the first row. If you hit ↑ with no prior selection it highlights the last row.

Agreed, this would be better behavior than highlighting it by default

**Comment by defunctzombie** [comment]
Should this also un-highlight the first item when you've used the mouse to hover over another item? Then keyboard keys would navigate from the hovered item?

**Comment by amacneil** [comment]
Still a problem
