### ISSUE TITLE
Inconsistent hover styling for layout menus

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1605]
**Description**
<img width="342" alt="Screen Shot 2021-08-05 at 4 10 54 PM" src="https://user-images.githubusercontent.com/6993359/128432826-ba477944-0eca-4f20-99e6-ca6a078ca4da.png">
<img width="339" alt="Screen Shot 2021-08-05 at 4 11 04 PM" src="https://user-images.githubusercontent.com/6993359/128432829-a8e61146-6c5b-4777-ae40-584f6bf46331.png">

- Version: 0.14.0
- OS: macOS

**Steps To Reproduce**
- Open the layouts tab in Foxglove Studio's sidebar
- Hover over the ellipsis icon next to your active layout
- You'll see an unexpected rounded border around the `...` button
- NOTE: Hover over the ellipsis icon next to an inactive layout will NOT show this unexpected border

**Expected Behavior**
- There should not be a border around the `...` button on hover, for active and inactive layouts

**Actual Behavior**
- There is currently a border around the `...` button on hover, ONLY for active layouts

**Comment by defunctzombie** [comment]
At some point this behavior was fixed and I am not able to re-produce on 0.20.1. Please re-open if you find a way to reproduce.
