### ISSUE TITLE
Amplitude metrics not working on web build

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1622]
**Description**
Amplitude metrics are not working on studio.foxglove.dev.

- Version: 0.14.0
- OS: macOS

**Steps To Reproduce**

- Navigate to studio.foxglove.dev
- Look at Chrome console for errors
- See following Amplitude errors
<img width="813" alt="Screen Shot 2021-08-11 at 10 11 12 AM" src="https://user-images.githubusercontent.com/6993359/129073199-30afa436-0fef-4192-a6c6-c3d02059ce80.png">

**Expected Behavior**
No Amplitude errors in console; metrics correctly collected from web build.

**Actual Behavior**
Errors in console; metrics not being collected from web build.

**Comment by jtbandes** [comment]
This bug is caused by https://github.com/webpack/webpack/issues/12960.

**Comment by amacneil** [comment]
Pretty sure this is still not working

**Comment by jtbandes** [comment]
One issue now is that in the web build, the app version is reported as 0.0.0:

https://github.com/foxglove/studio/blob/1d34d9672fbc8e4968f72c53c708cf9c03693c52/packages/studio-base/src/services/AmplitudeAnalytics.ts#L79-L81

(I don't think this is what's causing analytics to not show up at all though)

**Comment by amacneil** [comment]
@esthersweon did this get fixed? If not, would be great if someone can look into this this week.

**Comment by amacneil** [comment]
Pretty sure this is still not working

**Comment by jtbandes** [comment]
Indeed, I don't think any work was done on this since my last comment (at least I didn't see any PRs go by)
