### ISSUE TITLE
Auto detect Rosbridge ROS 1 vs ROS 2

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1654]
**Description**
When selecting Rosbridge in the connection picker, I shouldn't need to specify ROS 1 vs ROS 2. We should auto detect this based on the robot we are connected to.

Related: https://github.com/foxglove/studio/issues/1653 (combined `Open file` option in connection picker).

**Comment by jtbandes** [comment]
Reverting in https://github.com/foxglove/studio/pull/1763
