### ISSUE TITLE
Add preloading for ROS 2 bag data

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1658]
After connecting to a ROS 1 bag data source (i.e. not live), Studio typically preloads data to pre-populate panels like the Plot panel. We should add this same support for ROS 2 bag data.

**Comment by defunctzombie** [comment]
Unassigned myself

@amacneil for thoughts on prioritization of this

**Comment by amacneil** [comment]
Keep ticket open but not a priority until someone asks for it.
