### ISSUE TITLE
ROS 2 Native: Publishing support

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1661]
This feature request is for the ROS 2 native connection to support publishing back to the ROS stack.

We currently recommend ROS 2 users use the [rosbridge](https://foxglove.dev/docs/studio/connection/rosbridge) connection option instead, which already supports publishing, and also supports reading custom message types.

**Comment by jmm-slamcore** [comment]
Any updates on this issue? Can't seem to be able to publish goals to Nav2 yet/not even able to see the publish pose button on the desktop app when using ROS2.

**Comment by defunctzombie** [comment]
We recommend using the rosbridge connection if you need publish support in ROS2. We do not currently have plans to add publishing support to the native ROS2 connection.

**Comment by jtbandes** [comment]
Going forward, we plan to deprecate and remove the ROS 2 native connection (https://github.com/foxglove/studio/issues/4900). We are working on a new [foxglove_bridge](https://github.com/foxglove/ros-foxglove-bridge), which will provide improved performance and reliability over the Rosbridge and native connections. You can already use the new bridge today (see the README). Stay tuned for upcoming announcements about the new bridge!

**Comment by pepeRossRobotics** [comment]
@jtbandes Will foxglove_bridge support UDP connections?

**Comment by jtbandes** [comment]
Not in its current form – see https://github.com/foxglove/studio/discussions/4613 for more discussion on UDP.

**Comment by ruffsl** [comment]
> Not in its current form – see https://github.com/foxglove/studio/discussions/4613 for more discussion on UDP.

@jtbandes , that link now 404s. Where were these discussions migrated to?

**Comment by jtbandes** [comment]
I think it was one of these:
- https://github.com/orgs/foxglove/discussions/15
- https://github.com/orgs/foxglove/discussions/574
