### ISSUE TITLE
Make ROS message types available to extensions

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#1684]
https://github.com/foxglove/studio/blob/main/packages/studio-base/src/types/Messages.ts

These types aren't available in the extension API, but at least some like `Header` ought to be so it is easier to define compound message types in extension code.

**Comment by amacneil** [comment]
Pretty sure this is supported now.

**Comment by defunctzombie** [comment]
@amacneil What makes you think it is supported? I don't recall any package we've published with the ROS message types as typescript definitions.

**Comment by amacneil** [comment]
Nevermind, I thought this was talking about ROS schemas being available to user scripts.

As for the typescript types, a logical place for them to live would be https://github.com/foxglove/rosmsg-msgs-common
