### ISSUE TITLE
Automate publishing releases to apt repo

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1686]
Publishing releases to apt repo is currently a manual step following the release. This should be automated in the [post-release.yml](https://github.com/foxglove/studio/blob/main/.github/workflows/post-release.yml) workflow.

Per comment below: would also be nice to automatically publish to homebrew.

**Comment by amacneil** [comment]
Yeah there is a pretty decent github action for normal homebrew, not sure if it supports cask (might need modification). I use it for dbmate:

https://github.com/amacneil/dbmate/blob/main/.github/workflows/release.yml

Doubt there will be any existing PR if we do this in our post-release action.

**Comment by rgov** [comment]
> Doubt there will be any existing PR if we do this in our post-release action.

As in, you open a PR for 0.17.0 and then quickly cut a bug-fix 0.17.1 before the 0.17.0 cask update is merged.

**Comment by amacneil** [comment]
Oh, I see. Yeah, that would be confusing. I wonder how often that happens (surely pretty frequent given how many apps homebrew/cask support).
