### ISSUE TITLE
Enable controlling of length of the arrow created using the PoseStamped message 

### ISSUE THREAD

**Issue by MithunKinarullathil** [foxglove/studio#1704]
The below shows the properties of the arrow created using a posestamped message type. Currently we can only control the width of the arrow body and not the length (currently 4.7 according to @jtbandes ;) ). Please enable the editing of the length of the body of the arrow since for some maps the size is very big and for others it's very small.

![image](https://user-images.githubusercontent.com/51120171/131002888-11801072-06b8-448d-a607-78798e33c323.png)

**Comment by jtbandes** [comment]
I realized we actually have another ticket for this already! Duplicate of #1049
