### ISSUE TITLE
Data source extensions

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1710]
Currently, extensions only support implementing custom panels.

We want to add support for extensions to implement a custom data source (player).

**Comment by rgov** [comment]
I have some prospective users who would be interested in this for a few proprietary formats. We store some data in standalone files (e.g., images) and our recording just has pointers to those files. It would be useful to be able to pre-load or cache those for good performance.

**Comment by jhurliman** [comment]
Related: https://github.com/foxglove/studio/pull/4456

**Comment by RileyEv** [comment]
What is the current plan with this? We have some data stored in proprietary data store that would be nice to view in foxglove.

**Comment by jtbandes** [comment]
This is not currently on the near term roadmap. We are currently working on message conversion extensions, which focus on translating proprietary schemas to foxglove-supported schemas: https://github.com/foxglove/studio/pull/4507

We recommend storing proprietary data in [MCAP](https://mcap.dev) files, or converting it to MCAP after recording. MCAP is serialization-agnostic (Foxglove Studio supports MCAP files containing JSON, Protobuf, Flatbuffers, and more). It can be stored in the [Foxglove Data Platform](https://foxglove.dev/data-platform) and streamed easily to Studio.

**Comment by amacneil** [comment]
Closing because there is no current plan for this feature. We're not philosophically against it, but we want to improve the data source APIs before we expose them publicly.

As a workaround, most people use:
- [MCAP](https://mcap.dev/) for recorded data
- [Foxglove Websocket](https://github.com/foxglove/ws-protocol) for live connections

See: [custom data sources docs](https://foxglove.dev/docs/studio/connection/custom)
