### ISSUE TITLE
"Bag went back in time" when switching layouts

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1712]
**Description**
When switching layouts I get a "bag went back in time" error

- Version: v0.16 and latest main
- OS: Ubuntu

**Steps To Reproduce**

- Delete appdata directory
- Open studio with welcome layout and demo.bag
- Create a new layout, and switch back and forth a few times

**Expected Behavior**
No error

**Actual Behavior**
![Screenshot from 2021-08-27 15-26-46](https://user-images.githubusercontent.com/637671/131194603-1fa79baa-8423-4d91-a736-98da7646a822.png)

**Comment by jackiescanlon** [comment]
This happened to me as well, except with live data and not bags.

**Comment by jtbandes** [comment]
@jackiescanlon Thanks for adding a vote here! Is there more you can share about the problem you're seeing — is it happening regularly / do you have steps to reproduce the problem? Can you share any example data with us that exhibits the issue?

**Comment by jackiescanlon** [comment]
This isn't happening regularly. Unfortunately I can't share the data that triggered this because its confidential, and I haven't been able to reproduce yet. I'll keep an eye on it and see if I can get some reproducible steps and data together for this bug.

**Comment by defunctzombie** [comment]
@jackiescanlon @amacneil I tried to reproduce this with 0.20.1 and have not been able to. Are you still seeing this recently?
