### ISSUE TITLE
Plot panel isn't responding to resizes

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1714]
**Description**
Plot panel resizing seems to be broken on latest main.

- Version: main
- OS: ubuntu

**Steps To Reproduce**
Open plot panel then try to resize it

**Expected Behavior**
Resizes appropriately

**Actual Behavior**
![Screenshot from 2021-08-27 15-56-00](https://user-images.githubusercontent.com/637671/131196240-de38a6e8-e1e3-4b5a-bb0a-8941c8e4f446.png)

**Comment by defunctzombie** [comment]
This was broken in https://github.com/foxglove/studio/pull/1705
