### ISSUE TITLE
Ctrl-B should show/hide sidebar

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1717]
**Description**
Ctrl-B shows/hides the sidebar in both Jupyter Lab and VS Code, let's follow this convention.

**Comment by amacneil** [comment]
Closing because we might revisit the sidebar UX entirely.

**Comment by 2metres** [comment]
`Cmd + \` Hide shows the sidebar in VS Code

**Comment by amacneil** [comment]
On my computer, `Cmd + \` in VS Code opens 1Password 😭 

But `Cmd + B` in VS Code opens the sidebar
