### ISSUE TITLE
Plot panels synchronizing x axis range between index and timestamp

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#1722]
Studio: 0.16.0

Studio attempts to synchronize the *x* axis ranges of multiple Plot panels. But if a plot has an *x* axis that is not timestamp-based, like "index", it should not get synced with another panel that uses the timestamp range.

I think there used to be an option to disable synchronizing but I don't see it anymore.

**Comment by defunctzombie** [comment]
Wrote up the second part of this issue in https://github.com/foxglove/studio/issues/1732
