### ISSUE TITLE
Invalid bag causes sentry error with opaque error message

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1741]
**Description**
Due to rospy behavior I was able to create a bag file where messages fall outside of the claimed start/end time of the bag. This fails one of our assertions, but the error message is unhelpful.

- Version: 0.16
- OS: Linux

**Steps To Reproduce**

Create an invalid bag file: [bug.bag.zip](https://github.com/foxglove/studio/files/7087444/bug.bag.zip)
Using this script:
```py
import rosbag
import rospy
from time import time
from datetime import datetime
from visualization_msgs.msg import Marker

bag = rosbag.Bag('bug.bag', 'w')

try:        
    bagtime = rospy.Time()
    bagtime.secs = round(datetime(2021, 1, 1).timestamp())
    
    m = Marker()
    bag.write('/marker', m,bagtime)
    
    bagtime.secs += 1
    bag.write('/marker', m, bagtime)
    
    print('success')
finally:
    bag.close()
```

I assume this invalid bag is due to updating the `bagtime` variable after the first message gets written. This is probably a bug in `rospy`, but this issue is related to our handling of the invalid bag, not whether it should be possible or not.

**Current Experience**
Weird error (and gets reported to sentry):
```
Internal data provider assertion failed
ApiCheckerDataProvider(BagDataProvider@3): message.receiveTime (1609488000.000000000) is before start (1609488001.000000000)
```

![Screenshot from 2021-08-31 17-44-17](https://user-images.githubusercontent.com/637671/131593877-b9eaa61c-7824-43e4-bec0-dc378d5059a9.png)

**Desired Experience**
More helpful error message and not report to sentry.

**Comment by jhurliman** [comment]
No error is shown in the latest build
