### ISSUE TITLE
TransformStamped is Unsupported / Unavailable in 3d panel

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1749]
**Description**
In this bag, my transforms work fine (I can render the scene and change viewport transform), but I can't render the transforms in the 3d scene (they show as `Unsupported`):

![Screenshot from 2021-09-02 10-01-41](https://user-images.githubusercontent.com/637671/131886535-8b3e0b35-4e27-4c3f-abaa-00bc87b4389c.png)

- Version: v0.16
- OS: linux

**Steps To Reproduce**
[nuscenes.bag.zip](https://github.com/foxglove/studio/files/7100562/nuscenes.bag.zip)

It's weird that TransformStamped works fine for rendering the scene, but we're unable to render the transforms themselves.

**Comment by amacneil** [comment]
Solved by publishing [tf2_msgs/TFMessage](https://docs.ros.org/en/jade/api/tf2_msgs/html/msg/TFMessage.html) instead of [geometry_msgs/TransformStamped](http://docs.ros.org/en/api/geometry_msgs/html/msg/TransformStamped.html) (thanks @jhurliman).

Leaving this bug open to discuss whether we should support `geometry_msgs/TransformStamped` directly.

**Comment by jhurliman** [comment]
Working in the latest release
