### ISSUE TITLE
Cannot subscribe to `/rosout` with ROS2 native connector

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#1750]
**Description**

The RTPS subscription succeeds, but we don't have a loaded message definition for `rcl_interfaces/msg/Log` (https://github.com/ros2/rcl_interfaces/blob/master/rcl_interfaces/msg/Log.msg). Our https://github.com/foxglove/rosmsg-msgs-common library should evolve to export separate ros1 and ros2 sets of definitions, which would also fix the `/msg/` hack.

**Steps To Reproduce**

Connect with the ROS 2 native player and try to subscribe to `/rosout`

**Comment by amacneil** [comment]
Fixed by https://github.com/foxglove/studio/pull/1798
