### ISSUE TITLE
Extensions sidebar visual polish

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1778]
The Extensions sidebar has some strange text alignment and is inconsistent with the new Layouts sidebar.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/14237/132106190-15e3dc38-8c29-48dd-a30d-35dc81233b70.png">

<img width="222" alt="image" src="https://user-images.githubusercontent.com/14237/132106201-d682e04f-fbff-4f08-bb72-ccd53f660947.png">

The extension details view has some line spacing that's too tight, some inconsistent font sizes, and it's not really clear what the different text fields are - presumably the "foxglove" is the extension author's name and "foxglove.studio-extension-turtlesim" is the extension id? It's not clear that clicking the id will open GitHub until after you click.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/14237/132106227-327f7e4d-aade-4d8f-8100-f46c5721f458.png">

<img width="106" alt="image" src="https://user-images.githubusercontent.com/14237/132106267-424e9afa-88f0-413d-a5f0-0eba939c5a47.png">

**Comment by defunctzombie** [comment]
This was fixed by moving extensions sidebar over to mui https://github.com/foxglove/studio/pull/3455
