### ISSUE TITLE
Cache CurrentUser information for use when offline

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1819]
Currently, the CurrentUserProvider calls the `/me` API on every app launch to fetch the user info. If the computer is offline, but the user was previously logged in, we should cache this info so the app doesn't appear to be logged out if the request fails.

**Comment by defunctzombie** [comment]
One way to handle this might be to only look for the access token being present to determine if "signed in" rather than the presence of the user. The user information and presence is only needed on certain panels?

**Comment by jtbandes** [comment]
The user id is needed since it's used to determine the cache location.
