### ISSUE TITLE
Make documentation consistent across app and website

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1822]
**Description**
Currently, there are 2 versions of app documentation - in-app (in the form of panel docs, message path syntax info, node playground docs, etc) and the [website](foxglove.dev/docs). 

**Current Experience**
Documentation is not consistent across Foxglove Studio app and [website](foxglove.dev/docs). Appropriately updating documentation currently requires doing so in 2 places, which isn't sustainable.

**Desired Experience**
In-app panel documentation should cover:
- High-level summary of what the panel does
- Panel shortcuts
- Link to the docs page for more details (would not be available offline, so immediately useful tips should be in the summary or shortcuts)

**Comment by amacneil** [comment]
How practical would it be to bundle the panel docs directly into studio? (e.g. when you click a panel help we show you a fully static/offline iframe with the docs for that particular panel).

Or, maybe even one level further - we just make the entire docs available somehow (an offline in-app doc browser - not sure how we would switch to this though, maybe it just opens in a new window).

I guess it might depend on moving the actual documentation into studio repo. But putting aside repo structure, is that something we would want to do?
