### ISSUE TITLE
Diagnostics Panel: Allow filtering diagnostics by level

### ISSUE THREAD

**Issue by jessicaaustin** [foxglove/studio#1837]
I'm interested in adding a new setting for the Diagnostics panel that allows filtering diagnostics by level. 

This would allow me to create a layout with two diagnostics panels: one that has only "bad" diagnostics, and one that has all diagnostics. This separation reduces cognitive load for the user -- they can look in one place for everything that's going wrong, and ignore the rest.

Note: This is similar to how rqt Robot Monitor works:

![rqt_robot_monitor_example](https://user-images.githubusercontent.com/1159930/132927692-365e11b1-bb3b-4ba9-8968-f590921a0ba7.png)

**Comment by jessicaaustin** [comment]
See https://github.com/foxglove/studio/pull/1838 for an example of me playing around with this concept. 

Here, I've added a simple boolean to check if a diagnostic is OK or not. 

Probably having checkboxes to show/hide each level makes more sense?

**Comment by jtbandes** [comment]
Thanks for your interest and contribution! We've implemented a more detailed level filter in https://github.com/foxglove/studio/pull/1877 that will be in the next release. Let us know what you think 😃

**Comment by jessicaaustin** [comment]
@jtbandes Nice, I like it! I pulled down `main` and tried it out against one of our bag files, and was easily able to split out "bad" diagnostics from everything else.
