### ISSUE TITLE
Investigate plot lag on prod build

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1871]
More info coming soon

**Comment by jtbandes** [comment]
The plot in question had ~50,000 points and part of the slowness was simply rendering all the arcs to draw the points. Perhaps the time has come to stop using 2D canvas to render plots and switch to WebGL:

- https://danchitnis.github.io/webgl-plot-examples/vanilla/index.html
- https://blog.scottlogic.com/2020/05/01/rendering-one-million-points-with-d3.html

**Comment by defunctzombie** [comment]
Give this a try https://github.com/foxglove/studio/pull/1874
