### ISSUE TITLE
Team layouts ask to confirm revert, but personal layouts do not

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1884]
**Description**
Inconsistency - for personal layouts:
1. Change a personal layout
2. Right click -> Revert
3. Changes are reverted

However, for team layouts:
1. Change a team layout
2. Right click -> Revert
3. I get prompted whether I am sure I want to discard changes

I think probably just never showing the confirmation modal is ok? But whichever option we go with, I don't see any reason for team layouts to be different from personal layouts?

- Version: latest main
- OS: linux

**Comment by jtbandes** [comment]
https://github.com/foxglove/studio/blob/f53d9379100e9a0d25f26ac08d2dad9edd42671a/packages/studio-base/src/components/LayoutBrowser/index.tsx#L301
