### ISSUE TITLE
unfriendly error on web build for unsupported browsers

### ISSUE THREAD

**Issue by wkalt** [foxglove/studio#1925]
Attached screenshot of studio.foxglove.dev in firefox.
![2021-10-01_08-20](https://user-images.githubusercontent.com/4952091/135645974-b3d73905-d034-4df2-899e-eb4652612e48.png)

**Comment by amacneil** [comment]
Duplicating some thoughts from Slack:

I think a more user friendly "crashed panel" UI would go a long way here (similar to the "crashed tab" UI in Chrome). We should hide the stacktrace behind a link, and display a sad robot or something instead.

cc @2metres for thoughts

**Comment by jtbandes** [comment]
Related: https://github.com/foxglove/studio/issues/1758

**Comment by jtbandes** [comment]
Pointer to relevant code: 

https://github.com/foxglove/studio/blob/4fa507eb92d3e68b8b814e8ac1c221c8a5b90c8b/web/src/VersionBanner.tsx#L39-L105

https://github.com/foxglove/studio/blob/586978d02118da940864e9bba87a8a31a298f590/packages/studio-base/src/components/ErrorBoundary.tsx#L41-L56
