### ISSUE TITLE
Support for PointCloud2 in Node Playground

### ISSUE THREAD

**Issue by jabbottn** [foxglove/studio#1953]
Currently, Node Playground does not support publishing of PointCloud2 messages which are much smaller and more efficient than marker points. Trying to publish a PointCloud2 message from the Node Playground will lead to `unsupported node kind` error from foxglove studio. Would be great to be able to publish point clouds from the playground and have them show up in the 3D view.

**Comment by jtbandes** [comment]
As long as the input data contains a PointCloud2 message, the Node Playground will automatically generate a TS type in the `"ros"` library which you can use to publish PointCloud2 messages:

```ts
import { Input, Messages } from "ros";

type GlobalVariables = { id: number };

export const inputs = ["/foo"];
export const output = "/studio_node/example";

const publisher = (
  message: Input<"/foo">,
  globalVars: GlobalVariables
): Messages.sensor_msgs__PointCloud2 => {
  let pointCloud: Messages.sensor_msgs__PointCloud2 = {
    header: { frame_id: "foo", seq: 0, stamp: message.receiveTime },
    point_step: 16,
    row_step: 16,
    data: new Uint8Array([0, 1, 2, 3]),
    is_dense: true,
    is_bigendian: false,
    width: 1,
    height: 1,
    fields: [],
  };
  return pointCloud;
};

export default publisher;
```
