### ISSUE TITLE
Valid message path in Raw Message panel is highlighted in red

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#1958]
**Description**

Open the attached bag, use a Raw Message panel and enter the following message path:

```
/example_markers.header.stamp.sec
```

It is highlighted in red, even though it works.

[poses.bag.zip](https://github.com/foxglove/studio/files/7325566/poses.bag.zip)

**Comment by amacneil** [comment]
![image](https://user-images.githubusercontent.com/637671/142516203-6eca15d6-bfa6-4ab1-80de-d4eb4b21bb0f.png)
