### ISSUE TITLE
Pose rendered in 3D panel that cannot be hidden

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#1959]
**Description**

Open the attached bag, open a 3D Panel, enable the `/example_markers` topic in the 3D panel topic picker. Select the target frame `pose`. In the same way TFs are rendered, a pose visualization with the label "pose" is rendered and cannot be hidden.

[poses.bag.zip](https://github.com/foxglove/studio/files/7325594/poses.bag.zip)

**Comment by amacneil** [comment]
Can't reproduce on latest web. 

@jhurliman are there any other repro steps we missed here?

**Comment by jhurliman** [comment]
It looks like this is fixed. There's another TF-bug when loading this bag now, but I'll open a separate ticket.
