### ISSUE TITLE
Console player: Support seek backfill while paused

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1962]

**Comment by foxymiles** [comment]
@amacneil I think this should be much improved now. Can you give it a try?

**Comment by amacneil** [comment]
Still not working for me. To repro just open any bag (e.g. nuscenes) from console. As soon as data starts loading I would expect to see the 3d panel populate, but it currently doesn't show anything until you hit play.

Then, pause playback. While paused, you should be able to seek to a point and have the 3d panel and image panels populate.

**Comment by defunctzombie** [comment]
Assigning to @jtbandes for incorporating into the experimental data platform player. The experimental player will be our path forward.

**Comment by defunctzombie** [comment]
The experimental data platform player supports seeking while paused.
