### ISSUE TITLE
Console player: Support preloading

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1964]
Requires larger refactor to allow players other than RandomAccessPlayer to vend preloaded messages.

**Comment by amacneil** [comment]
This is working much better, but still not 100%. When loading plots, it seems to preload part of the data, but doesn't load prior to the current seek position, and doesn't preload all the way to the end. Example:

https://user-images.githubusercontent.com/637671/155829545-7e9b8f03-ca13-411b-a22e-4026883b2377.mov

You should be able to repro with [this example](https://studio.foxglove.dev/?ds=foxglove-data-platform&ds.deviceId=dev_mHH1Cp4gPybCPR8y&time=2018-07-24T03%3A28%3A47.647Z&ds.start=2018-07-24T03%3A28%3A47.647Z&ds.end=2018-07-24T03%3A29%3A06.797Z).

**Comment by foxymiles** [comment]
@amacneil There was a bug around preloading segments I have a fix for. Also, currently we preload up to 15 seconds of data. Should I increase that? If so to what?

**Comment by amacneil** [comment]
Let's discuss with @defunctzombie.

I don't have data or intuition to say whether increasing preloading from 15 seconds is a good idea. But I think that at some point we will need to bite the bullet and give panels (e.g. plot, map, state transitions) an official way to request complete preloading of certain topics outside of the regular caching system.

**Comment by defunctzombie** [comment]
Closing this. The experimental console player does preloading. There's improvements that need to be made there but preloading itself is implemented. I don't want to cut over to the experimental player until I do some better buffering.
