### ISSUE TITLE
Change default font size to 13px

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1998]
**Description**
Studio currently uses a huge mix of base font sizes, from 12px for much of the original webviz design, to 14px for much of the new fluent stuff.

We should standardize on 13px as our base font size for majority of app text. Besides being a middle ground, it's also what vscode uses for most of its interface (besides the code editor).

**Comment by 2metres** [comment]
This will likely come with the switch over to Material-UI

![image](https://user-images.githubusercontent.com/924528/150865821-fb2bf6b4-0694-4717-a717-8dba4eec3279.png)

**Comment by defunctzombie** [comment]
@amacneil @2metres is this still a thing or has our font size situation improved?

**Comment by amacneil** [comment]
This is sufficiently done, font sizes are much more consistent now.
