### ISSUE TITLE
Incorrect size of OccupancyGrid

### ISSUE THREAD

**Issue by siddancha** [foxglove/studio#2044]
I'm publishing `nav_msgs/OccupancyGrid` messages with a grid size of 100x100. When I visualize this in Foxglove Studio, the aspect ratio of the grid is incorrect; the grid renders as a thin rectangle instead of a square. It visualizes fine in RViz.

I've attached the bag file and screenshots from both Foxglove and RViz.

- Version: 0.20.1
- OS: Ubuntu 20.04

**Steps To Reproduce**
Zipped bag file with `nav_msgs/OccupancyGrid` messages : [grid.bag.zip](https://github.com/foxglove/studio/files/7437399/grid.bag.zip)

**Expected Behavior**
A square 100x100 grid correctly rendered by RViz:

https://user-images.githubusercontent.com/6638091/139337878-5ba965ff-dad5-4c6a-af21-08404a4abcb2.mp4

**Actual Behavior**
A thin rectangular grid in Foxglove Studio:

https://user-images.githubusercontent.com/6638091/139337999-11a88240-ecdf-449f-9fea-88c0ad642024.mp4

**Comment by jtbandes** [comment]
Thanks for the report!
