### ISSUE TITLE
Extension API: addPanel config is not applied

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2067]
In terms of passing in the initial state, that partially worked for me with my extensions panel. That is, when it initially opens the sibling panel using `context.layout.addPanel`, the state is not applied. But if I restart Studio then it pulls the state I requested from disk. I'm guessing this is probably a problem on my end? I'm using this at the very start of my panel:

```
// DetailPanelState is my custom config type for this panel
  const [panelState, setPanelState] = useState<DetailPanelState>(
    context.initialState as DetailPanelState,
  );
```

_Originally posted by @jessicaaustin in https://github.com/foxglove/studio/issues/1914#issuecomment-953169873_

**Comment by foxymiles** [comment]
Fixed by #2232
