### ISSUE TITLE
Unable to log in to dev build of web app

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2085]
**Steps To Reproduce**
Run `yarn web:serve`. Visit localhost:8080 and try to log in.

**Expected Behavior**
Login flow is successful

**Actual Behavior**
I'm redirected to the login page, then back to the app, but nothing happens

**Comment by foxymiles** [comment]
Looking into this. This is going to require some changes to our auth flow it looks like.

cc @bryfox

**Comment by foxymiles** [comment]
To make this a little easier in the meantime while we work on a better fix I've added two new package.json scripts:

```yarn web:serve:dev```

and 

```yarn web:serve:local```

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/issues/2086#issuecomment-1006768155

**Comment by defunctzombie** [comment]
I've removed the bug label from this issue. It impacts local development of the web build only. I added some comments on a related ticket. We can consider adding some different flow when in `NODE_ENV===development` or at least a notice.

**Comment by defunctzombie** [comment]
We use device auth flow in the dev build now so you can login.
