### ISSUE TITLE
Worldview backgroundColor in Studio does not do anything

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2097]
See https://github.com/foxglove/studio/pull/2096

Even when no scene content is drawn, setting the backgroundColor to solid green still produces a black 3D scene.

**Comment by jtbandes** [comment]
Is it possible you're using the wrong units (0–1 vs 0–255)?

**Comment by jhurliman** [comment]
I tried both 1 and 255 for the red value, same result of a black 3D view.

**Comment by jtbandes** [comment]
I added `backgroundColor={[1, 0, 0, 1]}` in my local branch and it works for me. I don't think there is a Studio bug here. However, it does seem like maybe regl-worldview doesn't support dynamically changing the background color?

<img width="474" alt="image" src="https://user-images.githubusercontent.com/14237/140783960-79e0c419-6b90-485e-83c0-4da83939cbe1.png">
