### ISSUE TITLE
Studio doesn't render mesh Resoure Markers with the correct opacity

### ISSUE THREAD

**Issue by alluring-mushroom** [foxglove/studio#2098]
**Description**
When broadcasting ros2 Markers, with the opacity less than 1.0, studio renders the mesh correctly, except it has no transparency.

- Version: Foxglove Studio 0.21.0
- OS: Ubuntu 20.04

**Steps To Reproduce**

- Setup a python node to broadcast a Marker
<img width="555" alt="image" src="https://user-images.githubusercontent.com/86041465/140666589-ae4b2618-a6ea-4ef3-91c0-ef7558c92b40.png">

- the url here is http://localhost:8000/models/discharge_flask/discharge_flask.glb, and is being served by the builtin python http server for now
- I am running in ros2 galactic, using the ros2 web-bridge to get the data to foxglove 

**Expected Behavior**
It should look like this (this is my hacky implementation of meshmarkers I made before the awesome foxglove team worked on it
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/86041465/140666735-2cf0ac00-bed7-4496-86ff-be4795fba31f.png">

**Actual Behavior**
No transparency is rendered:
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/86041465/140666669-01fdfdfd-be27-4f5d-bf86-f2e1946f4fe1.png">
Instead

**Comment by alluring-mushroom** [comment]
Sorry, I forgot to submit the bag. Here it i
[rosbag2_2021_11_08-10_01_13.zip](https://github.com/foxglove/studio/files/7493411/rosbag2_2021_11_08-10_01_13.zip)
s

**Comment by jhurliman** [comment]
@alluring-mushroom can you send http://localhost:8000/models/discharge_flask/discharge_flask.glb as well?

**Comment by jhurliman** [comment]
@alluring-mushroom never mind, I was able to confirm opacity works in my PR without it. Fix is landing shortly.
