### ISSUE TITLE
Plot "X range in seconds" doesn't work correctly with bag files

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2108]
**Description**
Trying to "follow" the playback head doesn't seem to work with bag files.

- Version: v0.21.0
- OS: web

**Steps To Reproduce**

1. Open bag file.
2. Set "x range in seconds" to 10
3. click "reset view" in plot panel

**Actual Behavior**
doesn't follow playback.

**Comment by foxymiles** [comment]
Is this related to #2192? It seems to work if I have two plot windows open.

**Comment by foxymiles** [comment]
Here's a video showing opening/closing plot panels changing this behavior on the fly.

https://user-images.githubusercontent.com/93935560/142690720-acdd23c3-453d-48e7-8f2f-98d1b8fe67dc.mp4

**Comment by defunctzombie** [comment]
Also fixed by https://github.com/foxglove/studio/pull/2249
