### ISSUE TITLE
Add Amplitude metric for experimental feature usage

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#2111]
- Foxglove developers should be able to determine how frequently (or infrequently) users are toggling on certain experimental features

**Comment by esthersweon** [comment]
NOTE: Should add this as step to PR description.

**Comment by jtbandes** [comment]
@esthersweon Any plans to work on this in the future or should we close it?

**Comment by esthersweon** [comment]
I can work on this.

Opened PR that adds a reminder item to the PR template here: https://github.com/foxglove/studio/pull/4982

Will open separate PR that adds metrics to current experimental features.
