### ISSUE TITLE
Log level filter dropdown jumps to the top left of the screen while the log is scrolling.

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#2119]
**Description**
There seems to be a dropdown positioning glitch when the log level window window is scrolling.

**Steps To Reproduce**

1. Set up a workspace with an actively streaming Rosout window.
2. Click on the log level filter dropdown to open it.
3. Position your cursor over the error or fatal items in the dropdown but don't click it.
4. Wait for log events to scroll the underlying window.
5. You'll notice that the filter dropdown jumps back and forth from the correct position to the upper left of the entire workspace.

https://user-images.githubusercontent.com/93935560/140984277-bd621e33-5ef8-420c-8b66-31b359165a82.mp4

**Comment by amacneil** [comment]
Fixed by https://github.com/foxglove/studio/pull/2131
