### ISSUE TITLE
Swapping out a panel produces panel with no settings

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2133]
**Steps To Reproduce**
- Add a 3D panel. Click ⚙️ > Panel Settings and observe defaults are present (2/3 switches are on by default).
- Click ⚙️ > Change panel > 3D. Look at the new panel's settings.

**Expected Behavior**
The swapped-in 3D panel should have the same defaults set.

**Actual Behavior**
The new panel has a config of `{}`, which for some reason does not get merged with the 3D panel's defaultConfig.

If swapping in a new Tab panel, this bug causes the newly added tab's "Pick a panel" to not work.

**Comment by amacneil** [comment]
Let's also prevent users from changing their current panel to the same panel type.

**Comment by defunctzombie** [comment]
Did this get looked at? I recall us looking at it but wasn't sure if this rolled into any of the various layout PRs that may have fixed this.

I tried reproducing by swapping in a new tab panel and was able to use the "pick a panel" feature of the tab panel and was able to pick a panel.

**Comment by jtbandes** [comment]
That particular Tab issue was fixed by https://github.com/foxglove/studio/pull/2132
