### ISSUE TITLE
3D Panel topic settings modal gets stuck to mouse cursor when moving it

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#2159]
**Description**

https://user-images.githubusercontent.com/924528/141916419-2a1f7eea-be34-4cd9-a097-ceb16ff170b9.mov

- Version: Version 0.22.0-dev (darwin)
- OS: macOS 12.0 (21A344)

**Steps To Reproduce**
From demo.bag in the 3D panel open velodyne topic settings, drag window so that edge of modal is out of frame

**Comment by jtbandes** [comment]
Missing an overflow:hidden somewhere?

**Comment by 2metres** [comment]
I think my recent change <https://github.com/foxglove/studio/pull/2128>
that removed the RenderToBody and thus made the Modal movable

>

**Comment by jtbandes** [comment]
> and thus made the Modal movable

No, I made it draggable in https://github.com/foxglove/studio/pull/2054
