### ISSUE TITLE
Prevent users from changing their current panel to the same panel type

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2182]
Let's also prevent users from changing their current panel to the same panel type.

_Originally posted by @amacneil in https://github.com/foxglove/studio/issues/2133#issuecomment-973444397_

**Comment by jhurliman** [comment]
Dang it, I used this daily

**Comment by jtbandes** [comment]
There's a Reset to Defaults button in the settings sidebar you can use instead.
