### ISSUE TITLE
Transform named empty string should be handled

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2193]
If I create a pose with a frame_id of empty string, we should handle that somehow. Currently it displays things from the wrong frame:

![image](https://user-images.githubusercontent.com/637671/142703508-f1e59c2c-8cfc-4366-a2a4-fbb691032de5.png)

It might be nice to explicitly show `(empty)` in the transform selector, or otherwise make it clear that it is an empty string and not just "no transform selected".

**Comment by defunctzombie** [comment]
@amacneil We now show `(empty)` when you have an empty frame_id string.
