### ISSUE TITLE
URDF viz disappears when toggling between tabs

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2199]
**Description**

Create a layout with two or more tabs, at least one containing a 3D scene. Set the 3D Model in that scene to a valid URDF URL so the robot model appears. Switch tabs, then switch back. The model and any transform visualizations loaded from the URDF will have disappeared until you change the camera coordinate frame.

- Version: `db448473a975cdd3da17d829a8e86d8de532368c `
- OS: All

**Comment by defunctzombie** [comment]
@jhurliman sending your way - I think you added the URDF feature to the 3d panel so hoping you have some context on tackling this.

**Comment by defunctzombie** [comment]
Spoke with @jhurliman - gonna grab this since it might be a strange react-ism we need to apply to resolve this.
