### ISSUE TITLE
URDF visualization fails for duckiebot

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2203]
One or more bugs in xacro-parser prevents the URDF in duckiebot_description from being loaded. This appears to be a separate issue from https://github.com/foxglove/studio/issues/2202, hence the separate ticket.

**Comment by jhurliman** [comment]
Should be fixed in https://github.com/gkjohnson/xacro-parser/pull/76

**Comment by defunctzombie** [comment]
@jhurliman Which urdf file did you use to test this?

**Comment by jhurliman** [comment]
https://github.com/duckietown/duckietown-sim-server/blob/master/duckiebot_description/urdf/duckiebot.xacro

**Comment by defunctzombie** [comment]
@jhurliman Did you have to also install the package locally on your computer cause it references a package:// url? I tried opening in our web app and it didn't work.

**Comment by jhurliman** [comment]
Yes, I've only tested non-trivial URDF loading with package:// URLs.
