### ISSUE TITLE
UI Regression: Grouping panels as tabs

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#2204]
**Description**
Regression in UI for grouping panels as tabs

Before:
<img width="200" alt="Screen Shot 2021-11-23 at 1 12 49 AM" src="https://user-images.githubusercontent.com/6993359/142997580-156782e6-af8f-48f4-b439-301b861cfd85.png">

After:
<img width="183" alt="Screen Shot 2021-11-23 at 1 08 55 AM" src="https://user-images.githubusercontent.com/6993359/142997410-1c43fb1d-343b-4db7-aebc-f54c9ab531ce.png">

- Version: 0.22.1
- OS: macOS Monterey

**Steps To Reproduce**

- `Cmd` + click multiple panels to select
- Hover over any selected panel

**Expected Behavior**
- See consistently colored buttons with spacing between them

**Actual Behavior**
- See inconsistently colored buttons with no spacing between them

**Comment by jtbandes** [comment]
I think I fixed this in #2194, can you verify on main?

**Comment by 2metres** [comment]
Still seeing in v22.1

**Comment by 2metres** [comment]
Appears fixed on `main`
