### ISSUE TITLE
"Change panel" menu jumps down screen when typing in a search term

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#2205]
**Description**
- "Change panel" menu jumps down screen when typing in a search term

- Version: 0.22.1
- OS: macOS Monterey

**Steps To Reproduce**

- Open any panel's menu
- Click into "Choose panel"
- Start typing in a search term
  <img width="515" alt="Screen Shot 2021-11-23 at 1 16 11 AM" src="https://user-images.githubusercontent.com/6993359/142998125-3b21f7e3-fd6b-4716-a376-64308ec23904.png">
  <img width="453" alt="Screen Shot 2021-11-23 at 1 16 33 AM" src="https://user-images.githubusercontent.com/6993359/142998128-d0ad8329-3100-4d1a-9962-a379fee87bca.png">

**Expected Behavior**
- Submenu stays connected to the "Choose panel" menu option

**Actual Behavior**
- Submenu jumps down the screen as the submenu gets shorter

**Comment by jtbandes** [comment]
I think this might be a recent regression...I'm pretty sure I used this menu within the last week and didn't see this behavior, but I can reproduce on studio.foxglove.dev right now

**Comment by jtbandes** [comment]
Doesn't seem to be fully fixed. I think it depends on the initial screen size and whether the full menu content fits on screen without scrolling.
