### ISSUE TITLE
Remove requirement for node playground nodes to have `/studio_node/` prefix

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2210]
Currently node playground forces you to have a `/studio_node/` prefix. This behavior is inherited from webviz, but seems unnecessarily restrictive. For example, people might want to write a NP node to publish a `/tf` topic if they don't already have one.

**Comment by bunnyc1986** [comment]
thanks for posting the issue. I found the 3D panel automatically picks up the topic if its output type is `tf2_msgs__TFMessage`. So having the prefix doesn't affect transforms to be published from node playground.

**Comment by amacneil** [comment]
@defunctzombie @jtbandes @jhurliman is there any reason we enforce this prefix? Why don't we let NP publish on any topic?

**Comment by defunctzombie** [comment]
I don't think there's a technical requirement. For end users it might be nice to disambiguate between what studio generated locally and what came from their data source - but we don't have to impose that on folks.

**Comment by amacneil** [comment]
Agree that it's a nice property, but let's leave that up to the node author. They can always add whatever prefix they want.

**Comment by jtbandes** [comment]
No reason, other than sanity at Cruise when dealing with bags containing hundreds of topics.

**Comment by defunctzombie** [comment]
@amacneil I think this is better for Jan 2022 roadmap given the other items and bug backlog we have.

**Comment by jhurliman** [comment]
The main technical reason we do this now is to check for circular dependencies with node playground input/output topics. Any input topics that start with `/studio_node/` are considered invalid. Imposing this same restriction without the prefix will require a bit of code refactor.

**Comment by defunctzombie** [comment]
@jhurliman is it correct that a node playground node cannot listen to the output of another node playground node? Or does that work today? So we'd only need to do a circular dependency check on the input/outputs of the currently active nodes.

**Comment by jhurliman** [comment]
@defunctzombie I have no idea if this is just a circular dependency prevention or if piping node playground scripts together doesn't work at all.
