### ISSUE TITLE
PointCloud2 rendering should support `is_bigendian: true`

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2225]
Currently, the `is_bigendian` field of point cloud topics ~is silently ignored~ throws an error as of #2390. We should add big-endian support, or at least log an error if we encounter a big-endian point cloud that we can't render.

- [x] Add an error to the topic tree when we encounter a big endian point cloud.
- [ ] Enhance our point cloud rendering to render big endian point clouds correctly.

**Comment by defunctzombie** [comment]
Changing this to a feature now that the bug half is fixed.

**Comment by defunctzombie** [comment]
No user has asked for this.
