### ISSUE TITLE
Can't add custom topics to Image panel's Markers dropdown using mouse

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2226]
The dropdown for custom topics appears behind the menu, and clicking it doesn't work. A workaround is to use the arrow keys + enter to select an item from the dropdown.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/14237/143955714-03b948a7-0e0c-4013-bd8b-7d77a5b0652e.png">

**Comment by defunctzombie** [comment]
Which menu is this? The image topics menu or the markers menu? Do I need a data source loaded to reproduce this issue?

**Comment by jtbandes** [comment]
Markers menu; you can probably use any bag that has an image topic in it.
