### ISSUE TITLE
Toolbar disappears in fullscreen mode if the panel is in a tab

### ISSUE THREAD

**Issue by bunnyc1986** [foxglove/studio#2248]
**Description**
Toolbar disappears in fullscreen mode if the panel is in a tab

- Version: The latest version on demo website
- OS: Mac OS 11.6, and Chrome 96.0.4664.55

**Steps To Reproduce**

![image](https://user-images.githubusercontent.com/1644274/144327052-14807ff0-4c6b-4f1a-9083-a843f81bad6c.png)

**Expected Behavior**
The toolbar should show up as if the panel is not in a tab.

**Actual Behavior**
Toolbar disappears in fullscreen mode if the panel is in a tab.

**Comment by defunctzombie** [comment]
@bunnyc1986 could you elaborate on the steps to reproduce this?

I create a new tab panel and an image panel inside the tab panel. I can fullscreen both panels and continue to see the appropriate panel controls.

**Comment by jtbandes** [comment]
Maybe this is a z-index issue? I see some problems when fullscreening a panel that's inside a tab if there are also other panels adjacent to the tab:

https://user-images.githubusercontent.com/14237/144651986-214ca4d3-b64a-41d2-a41d-fc38b3a0ce16.mov

**Comment by bunnyc1986** [comment]
> @bunnyc1986 could you elaborate on the steps to reproduce this?
> 
> I create a new tab panel and an image panel inside the tab panel. I can fullscreen both panels and continue to see the appropriate panel controls.

@jtbandes 's screen recording has the exact reproduction steps. Thanks for posing it!
