### ISSUE TITLE
Add a rolling average math modifier for plots

### ISSUE THREAD

**Issue by Ryan-Holben** [foxglove/studio#2250]
It would be very helpful to have a rolling average math modifier for plots.  For example, suppose I'm plotting runtime values published by a node.  That data can be very noisy, so overlaying this with a second plot of the rolling average can help with interpretability. 

I'm not sure what the best interface would be for specifying the averaging interval, but for example if we are doing time series data, it could look like:  `.@average{0.5}` to indicate a half second window.

**Comment by jhurliman** [comment]
Would specifying a message count (`.average{5}` for a 10hz topic over a 0.5s window) work? This would be more generic than assuming a timestamp is available.

**Comment by Ryan-Holben** [comment]
Yes, absolutely.

**Comment by Ryan-Holben** [comment]
Though a downside is that assumes the topics come in at a regular cadence.  So there are tradeoffs.
