### ISSUE TITLE
Point cloud does not render from demo bag

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2278]
**Description**
When I open the demo bag and select the `/velodyne_points` topic in a new 3d panel I expect to see the point cloud show up. However nothing shows up when I play the file.

Regression from: https://github.com/foxglove/studio/pull/2243

**Steps To Reproduce**

1. Open a new layout
2. Add a 3d panel
3. Open the demo bag
4. Select `/velodyne_points` in the 3d panel
5. Play the file

**Expected Behavior**
After the above steps I expect to see point clouds rendered in the 3d scene.

**Actual Behavior**
Nothing is rendered in the 3d scene.

**Comment by jhurliman** [comment]
I cannot repro using either latest `main` or https://studio.foxglove.dev/ and `demo.bag`. Screenshots:
<img width="1312" alt="Screen Shot 2021-12-05 at 2 38 46 PM" src="https://user-images.githubusercontent.com/195374/144766769-49514293-e712-4cff-b1ea-ae3d43225822.png">
<img width="1358" alt="Screen Shot 2021-12-05 at 2 39 54 PM" src="https://user-images.githubusercontent.com/195374/144766773-c78d37ae-b297-4dc8-8945-a35e9192c8bc.png">

**Comment by defunctzombie** [comment]
The issue is that when adding a new 3d panel, then selecting the `velodyne_points` topic - I should see the points show up. That does not happen. In the above screenshots you are looking at the welcome layout which is already configured. Try adding a blank 3d panel and then enabling the topic.

The behavior I am describing should show the selected topic without the user having to configure the frame.

**Comment by defunctzombie** [comment]
Seems like if this is a regression it isn't recent. Closing out the bug and we can separately discuss any UX around making it more obvious where to select the frame.
