### ISSUE TITLE
Allow user to add an option "Connection Name" when opening a remote file or connection

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#2310]
As a user I would like to be able to see a human readble name for my remote connections and files

**Comment by amacneil** [comment]
I feel like maybe just using more sane names (in the connection sidebar and the window or browser title) would be a good start.

E.g. for local or remote http files, just use the file name rather than the whole URL. For Data Platform, we can come up with something reasonable too.

**Comment by defunctzombie** [comment]
I've removed myself from assignment since we have de-prioritized this issue for now.

**Comment by amacneil** [comment]
Not convinced we need this. Closing but @2metres if you feel strongly let's discuss sometime.
