### ISSUE TITLE
WebSocket Connection has the wrong default value in 

### ISSUE THREAD

**Issue by KerstinKeller** [foxglove/studio#2334]
**Description**
When trying to connect to the websocket server, the default connection in Studio is a link to a bag file
```
https://storage.googleapis.com/foxglove-public-assets/demo.bag
````
instead of 
```
"ws://localhost:8765"
```

- Version: latest dev build, since today

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/13848742/145399540-4f275aa3-6195-48d3-a1f4-98a3677c292e.png)
Try to open the Websocket connection.

**Comment by jtbandes** [comment]
I'm having trouble reproducing this issue. Can you try again on the latest version and confirm?

Also FYI, you should be able to use the new url format:

https://studio.foxglove.dev/?ds=foxglove-websocket&ds.url=ws://localhost:8765/

**Comment by KerstinKeller** [comment]
It's a bit strange, it seems to happen when I refresh the brower, after a connection was already established...

**Comment by jtbandes** [comment]
I still don't see the behavior when I refresh 😕 maybe you can record a video?

**Comment by KerstinKeller** [comment]
https://user-images.githubusercontent.com/13848742/145814354-e2f8f869-63ee-43d1-bb10-e8e1a4b6428a.mov

I am hoping this helps.
