### ISSUE TITLE
Sign Out button is too close to bottom of screen

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2340]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/14237/145478244-b6e761c6-479f-44ac-a64c-feb5cf240237.png">

**Comment by amacneil** [comment]
cc @esthersweon @2metres 

I was just saying to Esther we should fix the bottom padding on the Help sidebar, but it looks like this is happening on all sidebars (account sidebar, also the connection sidebar if you shrink your browser window).

Might need a fix that works for all of them.

**Comment by jtbandes** [comment]
Should also make sure this is captured in screenshot tests so it doesn't regress

**Comment by defunctzombie** [comment]
Fixed by https://github.com/foxglove/studio/pull/2387
