### ISSUE TITLE
Correctly handle refreshing page when a local file URL is open

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2341]
**Description**
Currently if I load a file and then hit refresh, I get this error:

![image](https://user-images.githubusercontent.com/637671/145479531-4049a013-a9cd-429b-b22d-8a62dfe6ab59.png)

```
Failed to execute 'showOpenFilePicker' on 'Window': Must be handling a user gesture to show a file picker.
```

We should either be clever and store the file handle in local storage / indexdb / etc, or we should show a more helpful modal asking the user to reselect their file.

**Comment by defunctzombie** [comment]
This is fixed now. For local files we no longer store state in the URL.
