### ISSUE TITLE
Custom OccupancyGrid color scheme

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2359]
Point clouds support custom coloring schemes, OccupancyGrid should as well.

**Comment by jtbandes** [comment]
What types of custom coloring schemes are important? Is just a 2-stop gradient enough or do we want to support custom assignments of specific values to colors? See also: https://github.com/foxglove/studio/pull/2003

**Comment by jhurliman** [comment]
A single tint color would be enough, anything past that is a nice cherry on top.

**Comment by jhurliman** [comment]
Implemented in New3D
