### ISSUE TITLE
All panel headers appear when hovering over any panel in a tab

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2377]
**Description**

Create a top-level Tab panel. Put two Image panels inside of a single tab. Hover over one of the Image panels, and observe the Image panel header appearing on both Image panels.

**Comment by jhurliman** [comment]
This appears to affect all panels, not just Image panel.

**Comment by 2metres** [comment]
I managed to find the culprit. But fixing this is difficult given then nesting that's happening.

https://github.com/foxglove/studio/blob/e4014daf9b197bee9520df17c467f8646654dd04/packages/studio-base/src/components/Panel.tsx#L92-L99
