### ISSUE TITLE
Diagnostic Detail panel dropdown hides all other options when one is selected

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2379]
The Diagnostic Detail panel has a dropdown that allows showing the key/values + OK/ERROR status for all diagnostics or only a single diagnostic. The "all diagnostics" option is just a blank dropdown entry which looks more like a bug than a purposeful choice, and the behavior of the dropdown is different after selecting the blank option vs one of the other options. Selecting a specific option and then opening the dropdown again, it looks like it's using the entry name as filter text so no other options appear.

<img width="475" alt="Screen Shot 2021-12-14 at 3 00 20 PM" src="https://user-images.githubusercontent.com/195374/146093253-c7e3908e-d9c2-4a6d-a32d-b0971e9dd9b3.png">
<img width="471" alt="Screen Shot 2021-12-14 at 3 00 32 PM" src="https://user-images.githubusercontent.com/195374/146093265-c0bf3650-eb04-4d88-bcff-3e2fce330e71.png">

**Comment by jtbandes** [comment]
This seems to depend which kind of item you click. If you click an item that represents a whole hardware_id, the problem doesn't occur. If you select a hardware_id+name combo, it does. For example with this data (from demo.bag):

<img width="269" alt="image" src="https://user-images.githubusercontent.com/14237/146110990-142c18aa-2596-4b01-a8cb-d28b78093054.png">

If I choose the `piksi rtk` item, I don't experience the problem, but I do with the other two more specific piksi options.

**Comment by amacneil** [comment]
Need to discuss desired behavior.

**Comment by defunctzombie** [comment]
I re-read the original issue description and I do not understand how to reproduce. @jhurliman could you indicate what steps you took to get into the state where you see blank entries? I agree what I see in the screenshot with blank dropdown entries looks undesirable. What I don't yet understand is what the desired behavior is or the steps to reproduce.

**Comment by jhurliman** [comment]
Here's a video demonstrating the problem. You can reproduce this by playing around with the dropdown in the fourth tab of the nuScenes layout.

https://user-images.githubusercontent.com/195374/149594924-db6f7497-b531-4f41-af6f-01d3c6245099.mov

Desired behavior:
 - Don't use `""` (empty strings) as a dropdown entry. It looks accidental and doesn't clue the user as to what will happen if you select it
 - Don't hide all of the other dropdown items when one is already selected
