### ISSUE TITLE
Changing link preference to "Ask each time" immediately goes back to launch choice screen

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2383]
1. Visit https://studio.foxglove.dev/?ds=foxglove-websocket&ds.url=ws://localhost:8765/
2. Select "remember my preference" and click "Web"
3. Open Preferences sidebar and select "Open links in: Ask each time"

**Expected:** no change for the current session; the **next** time I open a link, I will be asked whether to open it in web or desktop.

**Actual:** the app immediately reverts back to the screen where I originally clicked Web for the current session.

https://user-images.githubusercontent.com/14237/146097368-08d013b5-49e2-42d3-b00c-f12ef9c0d898.mov

**Comment by foxymiles** [comment]
I'm having trouble reproducing this one. Any other steps I might need to take @jtbandes ?

**Comment by jtbandes** [comment]
Nope, same repro steps still work for me...

**Comment by foxymiles** [comment]
> Nope, same repro steps still work for me...

Do you see any difference in an incognito vs normal window?

**Comment by foxymiles** [comment]
Note: this seems to only happen if studio can't connect to the websocket and start up a player.
