### ISSUE TITLE
Marker arrays of mesh markers do not display correctly in 3D panel

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#2408]
**Description**
- 3D panel only displays the last mesh marker in a marker array of mesh markers

- Version: 0.24
- OS: macOS

**Steps To Reproduce**

- Open Studio with [meshmarkers.bag](https://drive.google.com/file/d/16RR4ijj7_mMr8l3-wvjMmQtXnk8FF3y2/view?usp=sharing)
- Add the following Node Playground script

```
import { Input, Messages } from "ros";

type Output = Messages.visualization_msgs__MarkerArray;
type GlobalVariables = { id: number };

export const inputs = ["/avocado"];
export const output = "/studio_node/gundam_parts";

const publisher = (
  message: Input<"/avocado">,
  globalVars: GlobalVariables
): Output => {
  const markers = new Array(96)
    .fill(1)
    .map((_elem, idx) => idx)
    .map((idx) => {
      const formattedNum = `00${idx + 1}`.slice(-3);
      return {
        ...message.message,
        pose: {
          ...message.message.pose,
          position: { x: idx + 10, y: idx + 10, z: idx + 10 },
        },
        mesh_resource: `https://raw.githubusercontent.com/gundam-global-challenge/gundam_robot/master/gundam_rx78_description/meshes/rx78_object_${formattedNum}-lib.dae`,
      };
    });
  return { markers };
};

export default publisher;
```

- Open 3D panel to toggle on the `/studio_node/gundam_parts` topic

**Expected Behavior**
- All 90+ mesh markers show up in the 3D scene

**Actual Behavior**
- Only the last mesh marker in the array shows up in the 3D scene
<img width="550" alt="Screen Shot 2021-12-15 at 6 07 55 PM" src="https://user-images.githubusercontent.com/6993359/146294882-42266ede-b982-427f-a258-62075dd40b39.png">

**Comment by jtbandes** [comment]
I think this is expected. The markers need to have different `id`/`ns` values for them to not overwrite each other.
