### ISSUE TITLE
"Your active layout was deleted" warning when I just deleted it

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2436]
When I manually delete my active layout, we currently display a warning. The warning should only be displayed when the layout is deleted externally, not when it's an explicit action that I took.

https://user-images.githubusercontent.com/14237/146600197-05cc790a-2fa1-4be5-9f86-c725b9f4f52c.mov

**Comment by defunctzombie** [comment]
![image](https://user-images.githubusercontent.com/84792/146608890-d33c0b6e-c9d7-4361-b1ac-9419bf1eec6d.png)
