### ISSUE TITLE
External links in Help sidebar should open in a new tab

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2438]
In the web app, all the links in the Help sidebar under External Resources / Product / Legal seem to load in the current window rather than opening a new window (`target="_blank"`). This interrupts the flow of using the app and it would be preferable for them to open in a new window.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/14237/146600740-c1442b8c-1c7e-4f55-8791-33b88ecdb9af.png">

I think it would also be nice to display an icon indicating that these are external links, like this little box+arrow icon Wikipedia uses:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/14237/146600934-8ba4c33e-d433-4403-8678-882519f6a036.png">

**Comment by defunctzombie** [comment]
@esthersweon should be an easy fix - maybe we should have an <ExternalLink> component that encapsulates this so we can easily use that wherever.
