### ISSUE TITLE
Desktop app doesn't show subscribing topics when connected via ROS 1 data source

### ISSUE THREAD

**Issue by s-sliwinski** [foxglove/studio#2458]
**Description**
Foxglove desktop app doesn't show subscribing topics when connected directly and doesn't allow to publish to them

- Version: v0.24.0
- OS: Ubuntu 20.04.3 LTS (Focal Fossa)

**Steps To Reproduce**

I'm using RPI4 as my ROS machine. There i run roscore and subscriber node (/listener) from this tutorial: http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29.
But the /chatter topic doesn't show up in foxglove. I must add that it displays in terminal on PC connected to raspberry so the connections seams to be ok.

## rostopic list:
![image](https://user-images.githubusercontent.com/39583362/146910715-7a987824-1b81-4556-84ec-5d59abba7c5f.png)

## roswtf:
![image](https://user-images.githubusercontent.com/39583362/146910480-2aaac07d-df75-435c-8a8d-aecf89cda722.png)

## foxglove direct connection:
![image](https://user-images.githubusercontent.com/39583362/146910611-737d799e-0dad-4830-8096-42afbbefa6e6.png)

**Expected Behavior**
/chatter topic displays in "Raw Message" and "Publish" panels. 

**Actual Behavior**
/chatter topic doesn't show up in foxglove studio

When i enter /chatter directly in the "Publish" panel and publish the message shows in foxglove studio but doesn't go to roscore:
![image](https://user-images.githubusercontent.com/39583362/146913778-3cd1c21f-9e10-4d89-be8d-d03eec8d029a.png)

**Comment by amacneil** [comment]
Often this is a problem where the ROS host (robot) doesn't know the correct IP address or hostname of your computer, which it needs to publish messages to the client (in this case the "client" is Foxglove Studio).

In v0.24 you can solve this by setting `ROS_HOSTNAME` in the settings sidebar (cog icon in bottom right):

![image](https://user-images.githubusercontent.com/637671/147317873-117c74ff-e591-4be2-89f9-bed31ed22cee.png)

In v0.25 we have made this more prominent, you will see it in the new Open dialog whenever you initiate a ROS 1 connection:

![image](https://user-images.githubusercontent.com/637671/147317942-5de848aa-5063-4f8f-8af0-0d201a242ee5.png)

Let me know if that helps! If not, we can try additional debugging steps.

**Comment by defunctzombie** [comment]
I also echo what @amacneil said above. Please give the new connection dialog a try and see if that helps clarify how to connect to a live ROS1 system.

If you believe you setup the ROS_HOSTNAME and ROS_MASTER_URI correctly in Studio and your robot feel free to re-open this issue and we can take a look again.
