### ISSUE TITLE
Tooltip says "Follow undefined" when there are no coordinate frames to follow

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2466]
<img width="125" alt="Screen Shot 2021-12-21 at 2 53 13 PM" src="https://user-images.githubusercontent.com/195374/147028662-1f512a99-b314-4f17-bbf8-15f4e2c37a70.png">

**Comment by defunctzombie** [comment]
👍 Will take

**Comment by defunctzombie** [comment]
How did you get to this state? I opened some files with no frames and did not have a tooltip show up when I hover on the disabled follow button.

**Comment by defunctzombie** [comment]
I haven't been able to reproduce since we landed the various follow changes. If you do encounter weirdness around the tooltip again happy to take another look.
