### ISSUE TITLE
ROS2 incompatible QoS

### ISSUE THREAD

**Issue by bertaveira** [foxglove/studio#2473]
**Description**
When connecting directly to ROS2 local system with publishers with default QoS the following error appears:
```
New subscription discovered on this topic, requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: DURABILITY_QOS_POLICY
```
From my tests it appear to be due to the fact that foxglove subscribes to topics with durability QoS as "Transient local". As the documentation says this is not compatible with "Volatile" durability QoS which is the default QoS for ros2. Foxglove subscribing to topics as "volatile" would probably give better results since it is always compatible:
![image](https://user-images.githubusercontent.com/9644729/147127168-f80ecaa6-c4c0-4ff7-9c37-696bae531fa7.png)

- Version: v0.24
- OS: Ubuntu 20.04

**Steps To Reproduce**

Fire up any node that publishes topics in default QoS (with durability "volatile").
Example:
```
ros2 run demo_nodes_cpp talker
```
Fire up foxglove studio and connect via ROS2 direct connection.

**Expected Behavior**
Being able to display the messages in any panel of foxglove.

**Actual Behavior**
The node publishing the topic gives a warning saying 
```
New subscription discovered on this topic, requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: DURABILITY_QOS_POLICY
```
And no message is received in foxglove.

**Comment by jhurliman** [comment]
Thanks for the report. This is a limitation of how subscriptions are currently done in Studio's ROS2 native data source. I should be able to fix it within the next two weeks. In the meantime if you are blocked, we fixed this same issue in the rosbridge connector for ROS2.
