### ISSUE TITLE
Topic error for missing transform(s) is misleading when the transform from render frame to fixed frame is missing

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2474]
**Description**

Now that we round trip transforms through a fixed frame, the code that generates the error message about missing transforms needs to become more intelligent. This is what I see right now:

<img width="346" alt="Screen Shot 2021-12-22 at 9 31 44 AM" src="https://user-images.githubusercontent.com/195374/147132769-de9eab8c-6dd1-4ca6-b24a-7cce754c90d3.png">

"missing to base_link" is correct. "base_link to base_link" and "sensor to base_link" being missing is confusing, it really means "base_link to map" is missing.

**Comment by defunctzombie** [comment]
Related issue: https://github.com/foxglove/studio/issues/2575

**Comment by defunctzombie** [comment]
Removing the `bug` label from this and keeping `ux` label. This issue and #2575 would both help end users understand what our new tf interpolations are doing under the hood and why they are seeing errors.
