### ISSUE TITLE
Marker lifetime story is failing

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2478]
Two failures:

- `fail2: t3 is ahead of currentTime (t2)"`
- `fail4: Expired at t1:1, currentTime is t2`

<img width="682" alt="Screen Shot 2021-12-22 at 10 12 25 AM" src="https://user-images.githubusercontent.com/195374/147138553-b9590c04-f25f-4cd6-808e-5c76bfe2c4d3.png">

**Comment by defunctzombie** [comment]
What is the expected outcome for this story?

**Comment by jhurliman** [comment]
Three green boxes, no red
