### ISSUE TITLE
If there is an automatically selected target frame, we don't show it in the TF dropdown

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2486]
**Description**

We should remove the "choose a target frame" concept. Either no frame exists, or we automatically select a frame and show it in the dropdown.

![image](https://user-images.githubusercontent.com/637671/147155308-53483888-b82e-4569-a255-67f0fd6737c3.png)

**Comment by amacneil** [comment]
Unrelated note: The follow icon should go "unblue" when you are not following.

**Comment by defunctzombie** [comment]
Blue icon fixed here: https://github.com/foxglove/studio/pull/2494
