### ISSUE TITLE
Data source start/end time are truncated without ellipsis

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2507]
When the data source sidebar is narrow, the data source name has an ellipsis in the middle, but the start/end time are just cut off.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/14237/147287091-b6098188-4560-4466-b72f-f70c7c8af471.png">

**Comment by foxymiles** [comment]
@jtbandes We have a lot of vertical space to work with here. Should we wrap instead of truncating?

**Comment by jtbandes** [comment]
cc @2metres

**Comment by jtbandes** [comment]
Looks better, what does it do when you get even narrower?

**Comment by foxymiles** [comment]
> Looks better, what does it do when you get even narrower?

<img width="260" alt="Screen Shot 2022-01-14 at 11 35 25 AM" src="https://user-images.githubusercontent.com/93935560/149567442-f6af1805-f279-4375-9441-b82d220c4140.png">

This is as narrow as it will let me go.
