### ISSUE TITLE
Unable to load STL files as mesh marker in 3D panel

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#2508]
**Description**
- Loading the following `.stl` files in Foxglove Studio does not correctly display the mesh resource in the 3D panel.
   - https://gist.githubusercontent.com/k-okada/d917b82418dcbcbdb478bb106f7ae0ff/raw/c10fb1f508d2cef58d1fbb601edd562f53624154/box.stl
    https://raw.githubusercontent.com/turtlebot/turtlebot/melodic/turtlebot_description/meshes/stacks/hexagons/plate_simple.stl

- Error message in console:
   <img width="801" alt="Screen Shot 2022-01-03 at 1 09 13 PM" src="https://user-images.githubusercontent.com/6993359/147980694-be38593d-3acd-4c20-8302-9dd6f35b566b.png">

   
- Version: 0.24
- OS: macOS

**Steps To Reproduce**

- Example bag: https://drive.google.com/file/d/16RR4ijj7_mMr8l3-wvjMmQtXnk8FF3y2/view?usp=sharing
- Use Node Playground to replace the existing the `/avocado` topic's existing `mesh_resource` field with the above `.stl` files

```
import { Input, Messages } from "ros";

type Output = Messages.visualization_msgs__Marker;
type GlobalVariables = { id: number };

export const inputs = ["/avocado"];
export const output = "/studio_node/another_resource";

// Populate 'Input' with a parameter to properly type your inputs, e.g. 'Input<"/your_input_topic">'
const publisher = (
  message: Input<"/avocado">,
  globalVars: GlobalVariables
): Output => {
  return {
    ...message.message,
    mesh_resource:
      "https://gist.githubusercontent.com/k-okada/d917b82418dcbcbdb478bb106f7ae0ff/raw/c10fb1f508d2cef58d1fbb601edd562f53624154/box.stl",
  };
};

export default publisher;
```

- Toggle on the new topic (/studio_node/another_resource) in the 3D panel's topic picker
<img width="412" alt="Screen Shot 2021-12-23 at 12 09 49 PM" src="https://user-images.githubusercontent.com/6993359/147287541-b3edf6d7-bf92-4dd3-af9c-a6b36360ef8e.png">

**Expected Behavior**
- You see the new mesh resource in the 3D scene

**Actual Behavior**
- No new mesh resource appears in the 3D scene

**Comment by jtbandes** [comment]
Are any errors logged in the console? It would be helpful to include that info in this ticket to help with triage.

**Comment by esthersweon** [comment]
@jtbandes - Added.

**Comment by jhurliman** [comment]
@esthersweon I'm not planning on learning regl-worldview mesh rendering internals any time soon. I assigned this to @jtbandes who might have insight there.
