### ISSUE TITLE
Can't select child topics when the parent topic is unselected

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2512]
**Description**

https://user-images.githubusercontent.com/637671/147292182-ffe29bb3-016c-4237-a0d8-6b99c2a86338.mov

**Comment by foxymiles** [comment]
What's the desired behavior here? Should it also select the parent topic or do we want to make it possible to select child topics without selecting the parent?

**Comment by amacneil** [comment]
IMO: If a parent topic is deselected, then selecting a child topic should automatically select its parent topic, and deselect any sibling topics.

**Comment by defunctzombie** [comment]
Added the new3d panel so we can take a look at whether this is still relevant for the 3d (beta) panel.

**Comment by amacneil** [comment]
New 3D solves this by removing the "disable group" function in favor of "show all" / "hide all", which is what I think I was advocating for here.
