### ISSUE TITLE
Flickering when zooming image panel

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2516]
**Description**
- nuscenes bag
- add cam front + lidar annotations
- try zooming in and out

current web: lots of flickering
v0.24: no flickering

https://user-images.githubusercontent.com/637671/147296299-e638166c-898a-43b4-a6ff-969d28dd3085.mov

**Comment by foxymiles** [comment]
@amacneil I can repro this flickering on 0.24.0 too so it seems like this issue is at least as old as that version.
