### ISSUE TITLE
Dismissing File picker leaves Open dialog in a broken state

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2521]
**Description**

In the open dialog:
- Click `Open local file`
- Click `Cancel`

Now you can no longer click `Open local file` again...

https://user-images.githubusercontent.com/637671/147314964-bdf1ac15-ea17-4618-9bc0-d571bc12b1c2.mov

- Version: latest main
- OS: web

**Comment by defunctzombie** [comment]
The open dialog is very serious about respecting your request to cancel.
