### ISSUE TITLE
Support custom image rotation in ImageView panel

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2523]
### Discussed in https://github.com/foxglove/studio/discussions/2469

<div type='discussions-op-text'>

<sup>Originally posted by **marijapili** December 22, 2021</sup>
Is it possible to implement a feature for image rotation - to adjust the view if the camera is, for example, upside down?</div>

**Comment by foxymiles** [comment]
@amacneil Would this be something we'd expose in the settings for the panel? Would we support rotating by any angle or just increments of 90°?

**Comment by jtbandes** [comment]
I think 90° rotations and horizontal/vertical flip would be nice. Probably ideal for them to be exposed as buttons in the panel UI, if we have space for it.

**Comment by foxymiles** [comment]
@jtbandes Now that we have an expanding toolbar in the upper right to support selectable image markers we could add more controls there.

**Comment by amacneil** [comment]
Panel settings might be a better place for it since it's not something you would be regularly changing?
