### ISSUE TITLE
Add warning when `nav_msgs/Path` has inconsistent frame_ids

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2543]
**Description**

In the "Nav Msgs Path" story, both lines should go up and down in a sawtooth if the per-Pose `frame_id` is being respected, and the whole path increase on the Y-axis (to point diagonally away from the camera) if `stamp` is being respected for transform interpolation.

<img width="849" alt="Screen Shot 2021-12-26 at 10 39 53 AM" src="https://user-images.githubusercontent.com/195374/147417216-8ab30431-1b4f-4512-b297-82f241b7fdfd.png">

**Comment by defunctzombie** [comment]
@jtbandes @jhurliman could one of you take this.

**Comment by jtbandes** [comment]
I wrote a python script to create a bag file with the same data. It seems like Rviz displays the path in the same way. Are we sure the per-pose headers are meant to be respected individually?

https://answers.ros.org/question/367021/which-frame_id-field-in-nav_msgspath-should-be-used/
https://github.com/ros-visualization/rviz/issues/1267#issuecomment-534470381

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/14237/152215875-58ba2cb1-13b8-4c3b-ae95-cb99f8a6f58a.png">

**Comment by defunctzombie** [comment]
Catting with John in slack about it - and it wasn't clear that they are suppose to be respected. One idea we considered is showing a topic error when we detect the user has done this (different frames per entry) since they might have something in mind that cannot be or is not supported.

**Comment by jtbandes** [comment]
What should be our course of action with this ticket? Close as expected behavior?

**Comment by amacneil** [comment]
Discussed live. Decided resolution: Our current behavior is "correct" in that it matches rviz, but we should add a topic warning if a `geometry_msgs/PoseStamped` has non-empty and different frame_id from the parent `nav_msgs/Path`
