### ISSUE TITLE
"Bag is unsorted" message is now an uncaught exception

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2552]
Repro bag: https://drive.google.com/file/d/1yVJekmiZPH5Zc_KkLfcRzxTwAPGmEWuJ/view?usp=sharing

```
Rpc.ts:160 Uncaught (in promise) Error: no receiver registered for sendNotification
    at Promise.then._channel.postMessage.topic (main.js:4717)
    at new Promise (<anonymous>)
    at Worker._onChannelMessage (main.js:4717)
```

> details: "This bag has many overlapping chunks (398 out of 519), which means that we have to decompress many chunks in order to load a particular time range. This is slow. Ideally, fix this where you're generating your bags, by sorting the messages by receive time, e.g. using a script like this: https://gist.github.com/janpaul123/deaa92338d5e8309ef7aa7a55d625152"
> message: "Bag is unsorted, which is slow"
> severity: "warn"
> type: "user"

**Comment by defunctzombie** [comment]
Fixed by https://github.com/foxglove/studio/pull/2587
