### ISSUE TITLE
Confusing error message for missing frames

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2575]
**Description**
When I open my dataset and try to visualize a marker topic in the 3d panel I see the following error:

<img width="264" alt="Screen Shot 2022-01-04 at 11 51 05 AM" src="https://user-images.githubusercontent.com/84792/148241578-e172fa44-6671-442c-bd36-8b31ae70fee9.png">

I checked and do have a `/tf_static` message and it has transforms between the two frames mentioned. After some more digging around the source code of 3d panel, I discovered that the header stamp on my markers is very old because I was using the driver in a mode that set the header stamp to the device time rather than robot time.

With the new tf interpolation changes in Studio, transforming a marker from one frame to another may fail when the stamps are not available to apply transforms at the right source and destination times. Making the error message indicate the reason for the missing frame would help me better understand why Studio is not showing my data.

- Version: 0.25+
- OS: Any

**Comment by jhurliman** [comment]
Fixed in New3D
