### ISSUE TITLE
Support reading and setting ROS params in ROS2 native connector

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2614]

**Comment by bertaveira** [comment]
+1 would love to see this feature as well

**Comment by jtbandes** [comment]
Going forward, we plan to deprecate and remove the ROS 2 native connection (https://github.com/foxglove/studio/issues/4900). We are working on a new [foxglove_bridge](https://github.com/foxglove/ros-foxglove-bridge), which will provide improved performance and reliability over the Rosbridge and native connections. You can already use the new bridge today (see the README). Stay tuned for upcoming announcements about the new bridge!
