### ISSUE TITLE
Missing transform error when I'm not using transforms or coordinate frames at all

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2630]
**Description**

When publishing `sensor_msgs/PointCloud2` message over the ws-protocol that does not have a `frame_id` field in header, I get the following error:

<img width="389" alt="Screen Shot 2022-01-08 at 4 37 32 PM" src="https://user-images.githubusercontent.com/195374/148664692-a7d9d8a3-8813-4aff-a8ae-fa25f1d51686.png">

**Steps To Reproduce**

Publish a message over ws-protocol, or encode a message into MCAP that is recognized as a renderable topic in the 3D panel but omit `header.frame_id` from the message definition.

**Expected Behavior**

I would expect my point cloud to render, and not see any errors about missing transforms since I am not using any transforms.

**Comment by defunctzombie** [comment]
Dug into this error and created a WIP PR to show the failure in a story (https://github.com/foxglove/studio/commit/d68f2aa58cfb4d2f6d0a8c680ac207d4a52985f4). The larger issue here is that we do not support omitting a frame_id.

Our type information for header assumes a frame_id field is present so we'd need to relax that to find the places in 3d panel where we make such assumptions. I imagine this work is related to empty string frames_id, tho that creates its own amusing side-effects in our app.

**Comment by defunctzombie** [comment]
@jhurliman Gave it some more thought and I think the PR I've drafted might be workable given our current 3d panel structure. There might be some other things to tidy up but give it a try with your workflow and see if it behaves as expected.
