### ISSUE TITLE
Choppy/jerky behavior when zooming synced plots

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2639]
When zooming two plot panels that are synced, the two panels don't always render at the same zoom level and one of them seems to stutter back and forth as long as the user is still scrolling.

**Steps To Reproduce**
- Open nuscenes demo data
- Switch to "Controls" tab
- Wait for data to fully buffer and populate plots
- Scroll to zoom one of the plots

**Current Experience**
The plot you are scrolling on does not respond immediately to zoom. The other plot stutters in and out between different zoom levels.

**Desired Experience**
The plots should stay (mostly) synced as they zoom without stuttering. It is acceptable if there's a small lag/delay in syncing the zoom level, but it should never stutter by zooming in and out if you are scrolling in one direction.

https://user-images.githubusercontent.com/14237/148882459-a2e3832d-264e-44ea-928a-f6b91f7fc0e3.mov

**Comment by foxymiles** [comment]
This seems to be an issue even with single plots.
