### ISSUE TITLE
Autocomplete in Node Playground `Input<>` throws an error

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2646]
**Description**
This is a regression compared with webviz.io/app.

**Steps To Reproduce**
- Add a new node in Node Playground
- Place cursor inside `Input<|>`, type quotes `Input<"|">`, and press ctrl+space to trigger autocomplete.

**Expected Behavior**
<img width="332" alt="image" src="https://user-images.githubusercontent.com/14237/148998831-4ad6d7a2-996f-4d1d-be71-f1b1bad599cd.png">

**Actual Behavior**
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/14237/148998823-5eaa8bae-059e-49b7-badb-9704ab00dedd.png">

**Comment by defunctzombie** [comment]
It seems that the generated roslib injection is causing monaco editor to receive a new roslib:

https://github.com/foxglove/studio/blob/main/packages/studio-base/src/panels/NodePlayground/Editor.tsx#L84-L89

I replaced the above code with:

```typescript
React.useEffect(() => {
    if (rosLib.includes("Placeholder")) {
      return;
    }
    const disposable = monacoApi.languages.typescript.typescriptDefaults.addExtraLib(
      rosLib,
      `file:///node_modules/@types/${projectConfig.rosLib.fileName}`,
    );

    return () => {
      disposable.dispose();
    };
  }, [rosLib]);
```

And that makes it more obvious that monaco editor (language server?) is not taking into account the new library code.

**Comment by defunctzombie** [comment]
The above extra lib issue seems to be related to https://github.com/microsoft/monaco-editor/issues/2866

And may or may not be the issue described in this bug report. Still investigating.
