### ISSUE TITLE
Text in "Log" panel is not infinitely scrollable

### ISSUE THREAD

**Issue by sherry-chef** [foxglove/studio#2652]
**Description**
Text in "Log" panel is not infinitely scrollable any more. Specifically, if the log content is longer than the Log panel size, the content before what can be contained in the Log panel will disappear when I attempted to scroll up. And then when I scrolled down the content outside of the screen sometimes disappears as well.

- Version: 0.24.0
- OS: Ubutn 18.04

**Steps To Reproduce**

Use any bag file with a super long rosout. Drag and drop it into Foxglove Studio. Let it play such that rosout content is longer than the Log panel. Then scroll up.
![image](https://user-images.githubusercontent.com/86276953/149029005-d3efab46-98e0-4a43-9e13-fd69b2b45bb6.png)

**Expected Behavior**
Infinite scroll - the content beyond the screen should still exist.

**Actual Behavior**
The content beyond the screen disappears.

**Comment by defunctzombie** [comment]
Closing because we've decided to revert the fluent-ui removal until we can prepare a migration that does not undo this bugfix.
