### ISSUE TITLE
Backticks are horribly broken

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2666]
**Description**
1. Hold backtick to enter quick edit mode
2. Mouse over some panels
3. Let go of backtick. We don't let you out.
4. If you click around some panels it's possible to get into an even more broken state where a panel thinks it is permanently being moused over.

https://user-images.githubusercontent.com/637671/149413173-fcaa9eb7-e448-4f7d-a3fe-d48e1fc9e4fd.mov

**Comment by foxymiles** [comment]
It looks like this is specific to tab panels.
