### ISSUE TITLE
Selecting some plot series adds an extra period to the message path

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2669]
**Description**
Adding a plot series that ends with `.x` (and some other suffixes) causes the series to be added with an extra period, creating an invalid message path input that has to be fixed manually.

https://user-images.githubusercontent.com/637671/149415324-291c05c1-0ee7-48b7-909b-da1561cfd4a6.mov

**Comment by foxymiles** [comment]
@amacneil Can you still repro this in current main? I'm not seeing it here.

**Comment by amacneil** [comment]
I just did some further testing, it only happens when you use find-as-you-type. It doesn't happen if you only use the mouse and select suggestions from the dropdown.

**Comment by foxymiles** [comment]
> I just did some further testing, it only happens when you use find-as-you-type. It doesn't happen if you only use the mouse and select suggestions from the dropdown.

Thanks for the extra detail that helps.
