### ISSUE TITLE
subscribe([]) in the extension API does nothing

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2679]
```typescript
subscribe(["a", "b"]) // subscribes to topics "a" and "b"
```

```typescript
subscribe(["a"]) // unsubscribes from "b", keeps the subscription to "a"
```

```typescript
subscribe([]) // unexpectedly does nothing
```

Instead of early returning in <https://github.com/foxglove/studio/blob/main/packages/studio-base/src/components/PanelExtensionAdapter.tsx#L344-L346>, this should call `unsubscribeAll()`

**Comment by jtbandes** [comment]
Is it true we've never documented that subscribe() behaves more like `setSubscribers`? Should we just change it to work like you'd expect subscribe() to work and also add an unsubscribe()?
