### ISSUE TITLE
In-app "Join Slack community" link is broken

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2692]
**Description**
On the `Get started` dialog, the link to join slack is broken. It's adding some `utm_source` parameters which seems to break the redirect.

**Comment by jhurliman** [comment]
This should probably be fixed on the backend if it's breaking the redirect with just a query parameter.

**Comment by amacneil** [comment]
Discovery: The links use `&` in `https://foxglove.dev/docs&utm_source=studio&utm_medium=open-dialog` when they should use `?` instead.
