### ISSUE TITLE
3D panel doesn't use tf_static to transform marker

### ISSUE THREAD

**Issue by chenjunnn** [foxglove/studio#2714]
**Description**
When publishing a marker in a frame different from the fixed frame, the 3d panel doesn't transform its position to the fixed frame but showing its position directly.

As the example below, the marker should be in front of the camera_link (x=0.4), but it is incorrectly shown at z=0.4 in camera_link.

![1642780645(1)](https://user-images.githubusercontent.com/57067221/150558615-2833f800-db7c-427b-8dfd-57b27e2a7690.png)
(The left is camera_link, and right is the optical frame)

**Comment by jhurliman** [comment]
I see `frame_locked` is set to false. Is it possible the relevant tf was published after the marker?

We have a number of screenshot tests to confirm that transforms are applied to markers correctly in a variety of different tf hierarchies. It's certainly possible that you found a gap in our tests, but at first glance this seems like something that should have test coverage and be working correctly.

**Comment by chenjunnn** [comment]
The tf is static, and here is what I see using Rviz
![1642781978(1)](https://user-images.githubusercontent.com/57067221/150562286-de0418f9-365c-42d5-b77d-86fc7fe129da.png)

**Comment by defunctzombie** [comment]
@chenjunnn Am I correctly seeing in your first screenshot (of Studio) That the transforms are correctly shown in the scene (the various arrows) relative to each other?

Which type of datasource are you using?

**Comment by chenjunnn** [comment]
The transforms are correctly shown. And I'm using ros2 rosbridge connection. But I think the problem has nothing to do with the datasource.
I also record a example rosbag, the marker is incorrectly shown in studio either.
[rosbag2_2022_01_23-15_00_29.zip](https://github.com/foxglove/studio/files/7919970/rosbag2_2022_01_23-15_00_29.zip)

**Comment by defunctzombie** [comment]
@chenjunnn Thanks for providing the sample bag file. I've been able to open it and also see what you describe with the marker shown at the wrong location.

@jhurliman The tf_static messages appear before the marker message in the data source.

**Comment by foxymiles** [comment]
Looks like this is a bug in regl-worldview's handling of some marker types and  not related to the datasource type or the topic name.
