### ISSUE TITLE
Switch to existing sample layout without creating a new one

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2722]
**Description**
My sample layouts are getting out of control:

![image](https://user-images.githubusercontent.com/637671/150870008-18242e9d-faa3-4dc7-95ec-edf5fa0478a8.png)

Currently we create a new layout (with the same name) every time you click "view sample data". We originally did this because we were worried about overwriting the layout for a user who may have modified it.

~However, I think the more common scenario is someone loading the sample data multiple times, and we should just overwrite their existing sample layout with the latest version.~

Jacob suggested that if there is an existing sample layout, we just switch to it and not overwrite it. If the user wants to reset their sample layout they can delete the existing one first.

**Comment by amacneil** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/637671/166826511-59bdcb3f-10d3-4b3a-869b-3fa8cf2b39cb.png">

**Comment by jtbandes** [comment]
Another possible solution is to switch to an existing layout with the same name, but not overwrite, only create a new one if it doesn’t exist already.

**Comment by defunctzombie** [comment]
Here is where the logic lives that handles layout _things_ attached to a data source factory:

https://github.com/foxglove/studio/blob/main/packages/studio-base/src/components/PlayerManager.tsx#L161-L177

**Comment by amacneil** [comment]
Let's try @jtbandes's suggestion. If the user wants to restore the original sample layout, they can delete the sample layout and it will get recreated. Otherwise, we just switch to their existing sample layout.

**Comment by amacneil** [comment]
@foxymiles want to take this one?

**Comment by foxymiles** [comment]
@amacneil Sure, I'll have a go.
