### ISSUE TITLE
Data Source: open file from url(http/https) does't support searchParams

### ISSUE THREAD

**Issue by Elaine87** [foxglove/studio#2726]
**Data Source: open file from url(http/https) does't support searchParams**

- Version: 0.27.0
- OS: macos Big Sur

**Steps To Reproduce**

![image](https://user-images.githubusercontent.com/3049861/150934245-3e481898-97d1-4a2c-840b-40abec455705.png)

**Expected Behavior**
can be opened regardless of whether url has searchParams or not

**Actual Behavior**
it has an error

----------------------------------------------------------------------------------------
I browse the code and I think the question may be in this:
 file location: foxglove/packages/studio-base/src/components/OpenDialog/Remote.tsx

```js
 const extension = path.extname(currentUrl);
```
if the variable currentUrl has searchParams which contains dot(.) will lead to above error.
Whether the pathname should be extracted as the path.extname() params:
```js
  const url = new URL(currentUrl);
  const extension = path.extname(url?.pathname);
```

**Comment by foxymiles** [comment]
Thanks for the bug report and the suggested fix!

**Comment by Elaine87** [comment]
Thank you for your efficient support！Thanks for this awesome project!
