### ISSUE TITLE
Typing in ROS_PACKAGE_PATH text field spews errors

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2733]
If I'm visualizing a model in the 3D panel, and then I start typing to change the ROS_PACKAGE_PATH, I get a huge list of errors on screen as I make each keystroke. The errors are technically correct, but super annoying.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/14237/151083395-76e9937e-e234-4dfa-984a-951577e7bc5e.png">

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/14237/151083350-fdb63c89-a32f-43be-b49d-4eb8e24f233f.png">

**Comment by jhurliman** [comment]
These show up as a sidebar ("topic") error instead of a spew of notifications now.
