### ISSUE TITLE
3D panel Grid - Line size scales with the grid size

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2742]
**Description**

<img width="683" alt="Screen Shot 2022-01-26 at 9 12 31 PM" src="https://user-images.githubusercontent.com/195374/151296177-2c2b45d5-e128-4372-b5d9-32de398e319a.png">

**Steps To Reproduce**

<img width="476" alt="Screen Shot 2022-01-26 at 9 15 50 PM" src="https://user-images.githubusercontent.com/195374/151296283-8c8365a0-01f0-4b77-b021-56a761717f4c.png">

**Comment by foxymiles** [comment]
Looks like maybe the issue is that regl-worldview interprets `scale.x` as a thickness value?

https://github.com/foxglove/regl-worldview/blob/7364e5142b50e7d50194321af91d6bb1428f493f/src/commands/Lines.js#L298-L300

**Comment by jtbandes** [comment]
I believe the grid uses `scaleInvariant` lines and this is a bug with the implementation of scale-invariant rendering.

**Comment by foxymiles** [comment]
Actually according to @jtbandes this is a longstanding issue in regl-worldview and not easy to fix.

**Comment by defunctzombie** [comment]
@jhurliman What is the intended behavior for `Line width`?

**Comment by jtbandes** [comment]
Line width is intended to be specified in pixels.

**Comment by defunctzombie** [comment]
> Line width is intended to be specified in pixels.

Why not units in the real world? meters?

**Comment by foxymiles** [comment]
> > Line width is intended to be specified in pixels.
> 
> Why not units in the real world? meters?

For a reference grid you would want line width in screen units not real units right?
