### ISSUE TITLE
3D panel Grid - Grid is not centered

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2743]
**Description**

This is most obvious with small grids (~1m or less).

<img width="600" alt="Screen Shot 2022-01-26 at 9 47 18 PM" src="https://user-images.githubusercontent.com/195374/151299423-72f7018d-1128-491e-ac68-3ef0d0bd3302.png">

**Steps To Reproduce**

<img width="484" alt="Screen Shot 2022-01-26 at 9 47 30 PM" src="https://user-images.githubusercontent.com/195374/151299443-e43cffc9-3002-4fe4-9134-5f527023b133.png">

**Comment by defunctzombie** [comment]
Not centered in what sense?

**Comment by jtbandes** [comment]
Can't reproduce. I think you must have panned your camera or have been following some frame that was not centered at (0,0,0) in world space prior to enabling the grid.

https://user-images.githubusercontent.com/14237/151877775-f73f483b-6ed8-4922-b5fd-9aec4e508306.mov

**Comment by jtbandes** [comment]
Also tried a 0.1m width:

https://user-images.githubusercontent.com/14237/151878267-f8e356da-9fa9-4cb0-b544-106c33bac7eb.mov
