### ISSUE TITLE
Annoying api errors when working on local robot network

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2757]
**Description**

I've connected my laptop to my robot's local network to debug an issue while connected to a live robot. As I use Studio (desktop), I am constantly interrupted by popups telling me some api route failed to fetch.

![image](https://user-images.githubusercontent.com/84792/151677946-208fafdf-c71d-4b0b-b6d8-c834919fde04.png)

** Desired behavior **

I'd like to work on my robot's local network without these annoying popups.

**Comment by jtbandes** [comment]
Is this still an issue?

**Comment by defunctzombie** [comment]
I think no - I believe the layout stuff has been isolated. If it happens again I'll resurface as a bug 🐛
