### ISSUE TITLE
Support "click to publish point/pose" in 3d mode

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2783]
Our "click to publish point/pose" feature currently only works in 2d mode. However, it seems this works fine in 3d mode too, we just don't let you access it.

Exhibit A:

https://user-images.githubusercontent.com/637671/152440210-e07890e8-6acc-4363-996c-51524a8de2ea.mov

Would be nice to allow me to initiate this feature in 3d mode.

**Comment by jtbandes** [comment]
Done in #3837
