### ISSUE TITLE
Add `schemaName` field to MessageEvent

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2796]
When a panel receives message events for subscribed topics, it might need to take different code paths depending on the type of the received message.

For example - the Image panel needs to know if the message it received should be processed as a ROS `ImageMarkerArray` or a [`foxglove.ImageAnnotations`](https://github.com/foxglove/website/pull/334) message. The `schemaName` determines which fields are expected and their semantics.

The existing array of message events does not convey this information as only ROS message datatypes were previously supported.

**Comment by amacneil** [comment]
We use `schemaName` in both mcap and ws-protocol, so I vote we start using that term consistently everywhere, and clean up places in our UI (and preferably our codebase too) where other terms like `datatype` are used indiscriminately.

**Comment by defunctzombie** [comment]
The consensus is `schemaName` is a better term. I've updated the issue title.

**Comment by jtbandes** [comment]
Done in #4576

**Comment by defunctzombie** [comment]
👏

**Comment by amacneil** [comment]
I have no memory of making this comment but apparently I am internally consistent over 6 months.
