### ISSUE TITLE
Alpha support for point clouds

### ISSUE THREAD

**Issue by joshabb** [foxglove/studio#2805]
It is necessary for point clouds to have alpha support as this is another way of visually encoding data. Can we please make add support for alpha coloring in point clouds?

**Comment by amacneil** [comment]
@defunctzombie is this something we can include in https://github.com/foxglove/studio/issues/1482?

**Comment by jtbandes** [comment]
Keep in mind that even if alpha is passed through to the GPU, the blending will probably not work correctly since correct transparency depends on the z-order, but we don't sort objects (especially points inside point clouds) by distance from camera before rendering them.
