### ISSUE TITLE
Plot Panel: Adding new topic erase past data of other topics

### ISSUE THREAD

**Issue by clementchef** [foxglove/studio#2809]
**Description**
Adding new topic erase past data of other topics
![Peek 2022-02-08 14-39](https://user-images.githubusercontent.com/66749666/153096224-6e5459a2-0de6-4141-bac1-cb19630bb9dd.gif)

- Version: 0.25.1
- OS: Ubuntu 18.04

**Steps To Reproduce**
Live play with rosbag play. Plot one topic. Add a second topic after a while. 

**Current Experience**

**Desired Experience**

**Comment by defunctzombie** [comment]
Confirming I am able to reproduce this with v0.29 and main.
