### ISSUE TITLE
Line thickness option on paths in 3d panel

### ISSUE THREAD

**Issue by mhl787156** [foxglove/studio#2812]
**Description**
Hi it would be nice if we could specify the line thickness of nav_msgs/Path lines within the 3d view. Currently the only options available are colour. 

This is important for me as the current default path thickness is too thick to determine the actual path of my drone! It would be nice to be able to turn it down to a scale which matches my experiments (within a 3mx3m square so 1cm width for the path line?) 

Current line thickness: 
![image](https://user-images.githubusercontent.com/10742598/153172895-9a2a9ce3-3219-4f8a-ad98-0c04f488ceb3.png)

Maybe adding similar options to PoseStamped arrow

Many Thanks! 

- Version: 0.29.0
- OS: Windows

**Steps To Reproduce**

Publish any nav_msgs/Path

**Current Experience**
The line thickness is fixed and cannot be modified. The only option is line colour. 

**Desired Experience**
The line thickness can be modified similar to the PoseStamped msg plotting

**Comment by jhurliman** [comment]
nav_msgs/Path and geometry_msgs/PoseArray share the same configuration options in New3D now.
