### ISSUE TITLE
Make "Data went back in time" less intrusive

### ISSUE THREAD

**Issue by bertaveira** [foxglove/studio#2824]
Would be nice to have a way to clear all warnings or even ignore future ones. When things go sideways I have to restart foxglove since it is impossible to clear all. It is even hard to debug the situation since it is covering part of the screen.

![image](https://user-images.githubusercontent.com/9644729/153476977-42c62243-ecb8-402c-82ba-394ba4be1b0a.png)

**Comment by defunctzombie** [comment]
@amacneil Let's add this to an upcoming roadmap month. I think its not a big lift for us to make this at least less terrible for now. Longer term I'd like to not use this style of notification for this issue - but the architecture we have today makes that trickier.

**Comment by amacneil** [comment]
A few thoughts:
- "clear all" button would definitely help, although with these errors it looks like they will keep happening if the data source is producing them
- grouping errors by text might be nice, although you still have to have the annoying popup over your screen the whole time (assuming it just comes back after you clear it)
- nicest option is probably to move this warning to the data source sidebar (similarly to how we display data source errors)

**Comment by defunctzombie** [comment]
We can tackle this by changing the MessageOrderTracker `update` call to inject problems into the player state and return a new player state. This would remove send notification and allow the issue to display on the data source sidebar in a less intrusive manner.

https://github.com/foxglove/studio/blob/main/packages%2Fstudio-base%2Fsrc%2Fcomponents%2FMessagePipeline%2FMessageOrderTracker.ts#L48
