### ISSUE TITLE
Publish pose does not work when connected to a ROS2 stack via rosbridge

### ISSUE THREAD

**Issue by samiamlabs** [foxglove/studio#2834]
Hi folks!

I noticed that the tools for publishing poses and points do not work for ROS2.
![image](https://user-images.githubusercontent.com/5682888/153764250-5e248ef7-7c1b-4f34-86aa-d2f9d1bd38d6.png)

The issue seems to be that the header fields in PoseStamped/PoinsStamped differ somewhat between the versions of ROS.

I get this error from rosbridge when I try to publish a pose:
```bash
[rosbridge_websocket-2] [ERROR] [1644769470.882365620] [rosbridge_websocket]: [Client 3] [id: publish:/goal_pose:114] publish: Message type geometry_msgs/PoseStamped does not have a field header.seq
[rosbridge_websocket-2] [ERROR] [1644769515.979927426] [rosbridge_websocket]: [Client 3] [id: publish:/clicked_point:125] publish: Message type geometry_msgs/PointStamped does not have a field header.seq
``` 

It would be nice to have an option to send ROS2 compatible messages with the tools.

**Comment by jtbandes** [comment]
Yes, we have a separate ticket for ROS 2 native publishing: https://github.com/foxglove/studio/issues/1661

However this issue is largely about the incompatibility between ROS 1 & 2 versions of PoseStamped, namely that header.seq was removed in ROS 2.

**Comment by karanchahal** [comment]
we have this problem as well, would be great to see support for ROS2 message types on foxglove

**Comment by jtbandes** [comment]
Yes, I suppose the player could expose some info about whether it is ros1/ros2/other, and the panel could use that to automatically select the message format. I'm not sure what we should do for non-ROS players to be able to use this feature in the future, though (related: https://github.com/foxglove/ws-protocol/issues/38). I guess another option is that the panel could send the message to the player in a common format (like our [Foxglove message types](https://foxglove.dev/docs/studio/messages/introduction)), and the player could take care of translating it to whatever format is required for publishing.

Thoughts @defunctzombie?

**Comment by defunctzombie** [comment]
> Yes, I suppose the player could expose some info about whether it is ros1/ros2/other, and the panel could use that to automatically select the message format.

Maybe this could be the "profile" concept that we have with mcap headers.

> I'm not sure what we should do for non-ROS players to be able to use this feature in the future, though

I think we would document the 3d panel as publishing a `foxglove.Pose` (or appropriately named message) for any "custom" framework (or profile).

> I guess another option is that the panel could send the message to the player in a common format

One gotcha here is that if I open a `Raw Message` panel on the topic I _should_ be able to see the message getting published. I think thats an important debugging property we should try to preserve.

**Comment by jtbandes** [comment]
> One gotcha here is that if I open a Raw Message panel on the topic I should be able to see the message getting published. I think thats an important debugging property we should try to preserve.

I'm not sure this is a real problem – I think messages published from Studio today don't show up in Raw Messages (or any panel) unless they make a roundtrip through the player. In that case you would be seeing the final published message in the format vended by the player.

**Comment by ladianchad** [comment]
I had the same error, but when I modified the code as follows, it worked fine.

Perhaps it is a problem the format of header msg of ros1 and ros2 is different.

**Comment by defunctzombie** [comment]
Yes the header message did change between ros1 and ros2.

Fortunately we have a field that panels can use to detect the framework and the 3d panel could use this to publish a message with the correct format for ros1 vs ros2.

@jtbandes @jhurliman I'm moving this issue into a bug since we are displaying the UI to publish to users that are connected via rosbridge. We can either resolve this by not displaying the UI when we can't support the framework or fix this to publish the correct format message. Right now the user experience is one where you see the feature and when you go to use it, it fails.

**Comment by tomy983** [comment]
I also could not publish using ROS1. Either poses or points from the 3D panel (both) or any message using the publish panel. I use the latest version , live, with noetic on ubuntu 20.04

**Comment by Gabryss** [comment]
I have the same issue using Rosbridge and it is not working, does anyone knows if changing the message type will fix the issue ?
I use foxy with Ubuntu 20.04.
Foxglove version: 1.21.0 (latest)
