### ISSUE TITLE
Add more obvious topic settings for overriding marker color

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2853]
**Description**
Currently, in the topic settings dialog, we don't visually show whether we are using an overridden color or inheriting the color from the marker. We should make this a checkbox or radio or something to more clearly differentiate between "use marker colors" and "override color".

E.g. this topic is currently inheriting marker colors, not using white. But you have no way of knowing that:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/637671/154358793-cc39c90c-ec3b-4c32-a0b2-59dc254c8dad.png">

**Comment by foxymiles** [comment]
@amacneil This seems much improved in new3d. Maybe not worth fixing in old 3d?

**Comment by amacneil** [comment]
It seems I cannot override the marker color at all in new3d.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/637671/180934657-5cd80b37-6753-4fa8-bf5a-88e567020af0.png">

I created https://github.com/foxglove/studio/issues/3943 to track the request. 

In the meantime, I will close this ticket because we are not doing any new development on old 3D.
