### ISSUE TITLE
Selected icon in Node Playground is invisible in light mode

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2854]
**Description**
Selected icon in Node Playground is invisible in light mode:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/637671/154359725-cdd73fba-ecd1-4440-911d-7d9059683af4.png">

**Comment by defunctzombie** [comment]
@2metres Any update on this? Is there something blocking this from proceeding?

**Comment by 2metres** [comment]
Will take a look today
