### ISSUE TITLE
Seeing "select a layout" when I don't have any layouts

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2863]
**Description**
When I open the desktop app and close the "Open" dialog I am presented with the "select a layout" screen. I expected to see our sample empty layout instead.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/84792/154505893-e4d7f3ae-9b25-4b7d-9764-a69990bf8a97.png">

- Version: 1.0.0
- OS: macOS

**Steps To Reproduce**

Open the desktop app and close the "Open Dialog".

**Comment by foxymiles** [comment]
Steps to reproduce from scratch:

1. `rm -r ~/Library/Application\ Support/Foxglove\ Studio*`
2. Start studio & close the open datasource dialog.
3. Delete the default layout.
4. Close and restart studio.
5. Close the open datasource dialog.
