### ISSUE TITLE
TypeError: window.showOpenFilePicker is not a function while trying to import layout using provided docker image

### ISSUE THREAD

**Issue by lroixblue** [foxglove/studio#2881]
**Description**
Error TypeError: window.showOpenFilePicker is not a function pops while trying to import layout using provided docker image ghcr.io/foxglove/studio:latest. The docker container is running on a server.
![image](https://user-images.githubusercontent.com/100133053/154950208-8ea63ebc-45cb-4bff-b843-01ef7a0c569f.png)

**Steps To Reproduce**
- Run `docker run --rm -p "8080:8080" ghcr.io/foxglove/studio:latest` on a server
- On your pc access distant foxglove instance via the url server-ip:8080
- Go to Layouts and click Import layout button

**Expected Behavior**
Import layouts in foxglove while docker image is hosted on a server.

**Comment by MaxJarofka** [comment]
Sorry to reopen the question. I just encountered the same problem with the standard procedure to get my docker image running and access foxglove via a browser.

So how do I access studio over https? Also tried to sign in in my container to share the layouts but did not manage to do so.
Any idea how I can get my layout in there? I'm thankfull for all some pointing in a direction where I can read up on this.

Best regards
Max
