### ISSUE TITLE
Add publishing support to ROS2 native data source

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2882]
I'd like to be able to use the teleop panel to control my ROS2 robot. However, when I connect with the ROS2 data source, the teleop panel is disabled with no indication why.

https://github.com/foxglove/studio/issues/2880

**Comment by jtbandes** [comment]
Duplicate of https://github.com/foxglove/studio/issues/1661

**Comment by defunctzombie** [comment]
> Duplicate of #1661

:( I tried github searching for `ros2 publish` and did not find that issue.
