### ISSUE TITLE
ROS2-MarkerArray-Some type of markers don't display(ROS2 Connection/ ROS2 bag) 

### ISSUE THREAD

**Issue by taiyuzhuo** [foxglove/studio#2894]
**Description**
Some markers don't show in foxglove studio.
For example: 
visualization_msgs::msg::Marker::TRIANGLE_LIST, visualization_msgs::msg::Marker::TEXT_VIEW_FACING

- Version: 1.1.0
- OS: ubuntu 20.04

**Steps To Reproduce**

![fox_glove_3d_panel](https://user-images.githubusercontent.com/26341668/155251921-b3182522-1fc8-4ce3-844a-a5f54b6aa559.png)
![rviz2_show](https://user-images.githubusercontent.com/26341668/155251951-e7e17f7a-cc2c-4657-86ab-1b3503253217.png)
the bag file is(a new bag):
[rosbag2_2022_03_04-14_43_09.zip](https://github.com/foxglove/studio/files/8183799/rosbag2_2022_03_04-14_43_09.zip)
the namespace is :road_laneInfos
![Screenshot from 2022-03-04 15-20-37](https://user-images.githubusercontent.com/26341668/156717766-89cf2743-b239-4a57-b9a7-5c97b9d5f3d0.png)
road_laneInfos' type is visualization_msgs::msg::Marker::TRIANGLE_LIST

**Expected Behavior**
show all types of visualization_msgs::Marker.

**Actual Behavior**
only some types of marker are able to show

**Comment by jtbandes** [comment]
Hi, can you provide some more info about the data in this bag? Which namespaces are having problems rendering? It looks like the lines are very long – I'm wondering if you tried rendering shorter lines to see if that works as expected?

**Comment by taiyuzhuo** [comment]
> Hi, can you provide some more info about the data in this bag? Which namespaces are having problems rendering? It looks like the lines are very long – I'm wondering if you tried rendering shorter lines to see if that works as expected?

I've uploaded a new bag above. the namespace is  road_laneInfos and the type is visualization_msgs::msg::Marker::TRIANGLE_LIST.
it cannot be shown in foxglove studio

**Comment by jhurliman** [comment]
@taiyuzhuo using the Raw Messages panel with the filter `/test_hd_map.markers[:]{ns=="road_laneInfos"}`, I see 57 markers with the namespace `"road_laneInfos"`. The first one (id 0) has type 11 (`TRIANGLE_LIST`), the rest appear to be type 4 (`LINE_STRIP`). All of the markers have a header.stamp of 0 (Jan 1st 1970) which is very far behind the beginning of the bag. But the unique difference with the triangle list is it has a lifetime of 100,000,000 seconds, which is some time in 1973.

I recommend fixing either the header.stamp of your markers, and/or setting the lifetime of the triangle list to 0 which indicates "infinite lifetime".

**Comment by defunctzombie** [comment]
@taiyuzhuo We've also improved the error messaging around markers with such old header stamps via https://github.com/foxglove/studio/pull/2986. Please give this a try and let us know if things are working for you.

I'm closing this issue since we've explained why the data was not showing and also incorporated some UI to make it clearer what is going on in the 3d panel.

If you run into any other issues or think you have markers with correct timestamps that are not showing up please re-open and provide any additional details.
