### ISSUE TITLE
Support color by intensity for sensor_msgs/LaserScan

### ISSUE THREAD

**Issue by ccpowers** [foxglove/studio#2895]
I would like to display messages of type `sensor_msgs/LaserScan` with color determined by their intensity field, similar to RVIZ.
![Screen Shot 2022-02-23 at 8 30 49 AM](https://user-images.githubusercontent.com/477928/155330051-3336f4d9-e2dc-4b5b-aab1-48ae0707913b.png)

The specific use case i'm interested in is setting all points in the scan that are above a certain intensity threshold to one color, and all points below the threshold to another color. This can be achieved in RVIZ by setting the `min intensity` and `max intensity` to `threshold` and `threshold + 1`, and then choosing the min and max colors to display. 
A secondary use case is to display the intensity of each point in the scan transformed across a gradient, so that the relative intensity of each point can be visualized.

Thank you!

**Comment by jhurliman** [comment]
Fixed in https://github.com/foxglove/studio/pull/2952
