### ISSUE TITLE
Dragging playback bar causes it to get stuck in seek mode

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2900]
**Steps To Reproduce**

1. mousedown on the seek bar, then drag your mouse off the bar, then release it
2. now, every time you hover over the playback bar it will seek to the mouse cursor position
3. the only way to get out of this mode is to click on the playback bar

happening on current web + desktop

https://user-images.githubusercontent.com/637671/155410644-5282e9fd-28f3-490d-b3c3-56a69e231d04.mov

**Comment by jtbandes** [comment]
This regressed in https://github.com/foxglove/studio/pull/1805.
