### ISSUE TITLE
Message count and frequency are missing for Data Platform sources

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2901]
**Description**
<img width="787" alt="image" src="https://user-images.githubusercontent.com/637671/155411601-f2ebf850-243a-4510-8680-45cdc2074615.png">

Version: web

These are currently missing for data platform data. If they aren't available, we should remove these columns.

**Comment by foxymiles** [comment]
@amacneil I can count the messages per topic pretty easily but they'll show as 0 for topics we haven't subscribed to. Is that ok?

<img width="1131" alt="Screen Shot 2022-02-28 at 9 26 07 AM" src="https://user-images.githubusercontent.com/93935560/156019881-49b49c42-15e4-4cf2-ac9b-10a7ac07e03d.png">

**Comment by jtbandes** [comment]
We should show "unknown" or "–" or something if we don't have the information, rather than 0.
