### ISSUE TITLE
Could you please provide a more detailed extension example？

### ISSUE THREAD

**Issue by rogue-shadowdancer** [foxglove/studio#2905]
I am trying to write my first foxglove extension( In order to better distinguish multiple 3D graphics, I am going to add a dark outline to each cube represented by visualization_msgs/MarkerArray, for example:
![image](https://user-images.githubusercontent.com/78423508/155479291-0d831843-dadb-471b-965f-8948b59ad20b.png)
actually they are made of many small cubes ),
but unluckily I did not know anything about front end（such as javascript/typescript/react/...). And they are also not used in my daily works(usually we use C++ & python), which means even I spent a few days learning that, I still do not know how these things works(sorry for my poor coding skill..). 
So in order to let a beginner start their job in a few hours, and finish them in a few days(Because some of the functions themselves did not looks difficult), could you please provide a react version of turtle panel extension, and explained apis in a more detailed way? Because all of the api you introduced in docs look like under react in typescript. 
Or do you have some other good ideas about this?

**Comment by foxymiles** [comment]
I've added a few more example panels in https://github.com/foxglove/create-foxglove-extension/tree/main/examples. Are these helpful?

**Comment by rogue-shadowdancer** [comment]
Great! That helps a lot!
Thanks!

**Comment by foxymiles** [comment]
You're welcome! Closing this for now. If there are specific things that are unclear in the examples or the API please let me know on slack.
