### ISSUE TITLE
Plot jitters due to format of x-axis label

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#2926]
Inherited from Webviz but still present on Foxglove Studio 1.1.0 on macOS 12.2.1

From this issue: https://github.com/cruise-automation/webviz/issues/544

---

![ezgif-2-d72313466639](https://user-images.githubusercontent.com/108767/98702499-6db30b80-2348-11eb-9971-d868b66146ba.gif)

This is a plot of a value over time. The plot keeps jumping because the rightmost x-axis label sometimes switches from 1 digit of precision to 2.

**Comment by jhurliman** [comment]
Still present:

https://user-images.githubusercontent.com/195374/165198320-21ff1973-86f9-4be7-99f4-61414b64e927.mp4

**Comment by defunctzombie** [comment]
@jtbandes assigning to you. I think your PR is 👍 and we can go from there.
