### ISSUE TITLE
Error boundary is not scrollable

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2931]
When an error appears, if the height of the error boundary is too short, the error is not visible, but it's impossible to scroll down and see the error:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/14237/156093191-a5910072-aeba-48ec-8949-6a782525b0ab.png">

When you increase the height, the error becomes visible:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/14237/156093255-6be2fb9a-8b3d-49f0-b6c8-349a075fb498.png">

**Comment by jtbandes** [comment]
Reopening. If I have a small crashed panel, I can't access the dismiss/remove buttons:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/14237/186490435-4873b92c-1e2f-4482-82ee-5d911f673b74.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/14237/186490473-9a68548a-5bc9-4cbe-a0f7-3a329a14f11f.png">

**Comment by foxymiles** [comment]
This is a bit tricky since the details themselves are also scrollable. Maybe we should make the entire container scrollable and just completely expand the details when shown?
