### ISSUE TITLE
Recent data sources list shows "MCAP" label with `ws://` URL

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#2944]
**Description**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/14237/156230462-cc4a0637-e873-415b-8ba1-8b92a4d91175.png">

**Steps To Reproduce**
- Start a foxglove websocket server, e.g. `python3 -m foxglove_websocket.examples.json_server`
- Visit studio.foxglove.dev, connect the app to the foxglove websocket server
- Stop the server, so the app displays a "connection failed" error
- Refresh studio.foxglove.dev, so `?ds=foxglove-websocket&ds.url=...` is still in the address bar
- Drag a local .mcap file into the app, now `?ds=mcap-local-file&ds.url=...` is displayed in the address bar
- Refresh the page again
  - Now the data source recents list shows:
     <img width="219" alt="image" src="https://user-images.githubusercontent.com/14237/156231114-2283d1a9-33ea-4034-bc95-1dd50e65a747.png">
  - Clicking on this entry logs out `Select Source: mcap-local-file` in the console, but doesn't show the open dialog or load a file.

**Expected Behavior**
It should never be possible to see a websocket url in the recents list with a "MCAP" label. Ideally the address bar would also never display `?ds=mcap-local-file&ds.url=...`, but we can't prevent people from typing in that url manually.

**Comment by foxymiles** [comment]
Simpler repro case:
1. Select a foxglove websocket source
2. Refresh
3. Select a local bag file

Before you even click "view file" you can see that the URL now contains an erroneous combination of `ds=ros1-local-bagfile` and a `ds.url` pointing to the websocket.
