### ISSUE TITLE
Cant zoom on plots while using live connection

### ISSUE THREAD

**Issue by clementchef** [foxglove/studio#2953]
Cant zoom on plots while using live connection

![Peek 2022-03-01 12-35](https://user-images.githubusercontent.com/66749666/156274168-8479ccb3-f0a2-4cfe-9a83-31ed3cde9dcf.gif)

- Version: 1.1.0
- OS: Ubuntu 18.04

**Steps To Reproduce**
Plot something while in live connection mode. 
Try to scroll, pan or zoom on graph always revert to default view.
Sync option in panel setting is off.

**Expected Behavior**

**Actual Behavior**

**Comment by jtbandes** [comment]
Seems related to #2701

**Comment by foxymiles** [comment]
@clementchef Can you please share more detail on your datasource? I'm not seeing this with a simple rosbridge data source.

**Comment by defunctzombie** [comment]
Via @clementchef - this is fixed in v1.3.0
