### ISSUE TITLE
node playground error when connect to websocket serve

### ISSUE THREAD

**Issue by jacqueline1990** [foxglove/studio#2971]
Hello,  I connect to foxglove websocket server and use protobuf as channel protocol, and  use node playground to generate virtual message for visualization, but a lot of typescript mistakes have happened In the panel below，and i havent written any code in node playground
![1646295622143](https://user-images.githubusercontent.com/23656783/156525260-cc31847f-652d-4b4e-b506-c64f79ce84d5.jpg)
Is there any way to ignore these problems ? or other solutions?

**Comment by defunctzombie** [comment]
Closing this issue since there's been no response for a few days. Happy to take a look at this if you can provide some steps to reproduce the error.
