### ISSUE TITLE
Message path autocomplete suggestions are not useful in some cases

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#2997]
**Description**
The message path autcomplete suggestions in this file are not useful and lead to empty plots

- Version: 1.2.0
- OS: macOS

**Steps To Reproduce**
1. Load this mcap file into studio
2. Create a plot panel
3. Select one of the suggested plot paths like `/base_footprint.transforms[:]{child_frame_id==0}.transform.rotation.y`

[test.mcap.zip](https://github.com/foxglove/studio/files/8216627/test.mcap.zip)

**Current Experience**
The suggested paths result in empty plots.

**Desired Experience**
In this case studio should suggest something that will actually result in a useful plot like:

`/base_footprint.transforms[:]{child_frame_id=='base_footprint'}.transform.rotation.y`

or 

`/base_footprint.transforms[:].transform.rotation.y`

**Comment by jhurliman** [comment]
Changing to a bug since `child_frame_id` can never match against `0`

**Comment by defunctzombie** [comment]
Should we remove these suggestions entirely? What determines that the suggestions to filter by a field value like `child_frame_id=="foo"` should be included in the suggestions vs all the other ways we can have message path input values?

**Comment by jhurliman** [comment]
> Should we remove these suggestions entirely?

I vote no, I find these suggestions helpful and would not be able to put together the correct syntax by memory without it.

**Comment by jtbandes** [comment]
> What determines that the suggestions to filter by a field value like `child_frame_id=="foo"` should be included in the suggestions vs all the other ways we can have message path input values?

Heuristic based on the `_id` suffix

**Comment by defunctzombie** [comment]
> I vote no, I find these suggestions helpful and would not be able to put together the correct syntax by memory without it.

My main complaint is they crowd the autocomplete. Maybe if you start typing a `{` then they make sense - but otherwise they feel like lots of noise.

**Comment by defunctzombie** [comment]
We need to take the type into account for the autocomplete suggestion.
