### ISSUE TITLE
Mac app update notifications not working

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3004]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/84792/157701316-21b6a6d2-424b-43d3-9e53-5994323689f7.png">

**Comment by jtbandes** [comment]
I just tested a manual notification with a dev build `new electron.Notification({ title: "Foo bar" }).show();` – this is the same API electron-builder updater uses: https://github.com/electron-userland/electron-builder/blob/17ee450dd747b867c6be5edb153a7fa39f427379/packages/electron-updater/src/AppUpdater.ts#L276

When the `.show()` is called, if the app hasn't been granted permission, this appears immediately:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/14237/157760951-f0c41384-b54a-464d-b68a-2a3b250670eb.png">

When I click Allow, I am able to see the notification that was sent.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/14237/157760991-71f806b6-f8d7-4063-b33b-d77aa2e8fd38.png">

So I think if there is a problem with our auto updater, it's not a permissions problem.

**Comment by defunctzombie** [comment]
Probably I accidentally clicked dismiss and didn't realize it ♾️ 

Going to close since it looks like the notifications are working.

**Comment by defunctzombie** [comment]
> So I think if there is a problem with our auto updater, it's not a permissions problem.

There's no clear problem other than some folks have said they see notifications and I know I haven't. But its easily because I dismissed the original notice.
