### ISSUE TITLE
Turn on experimental bag player in dev mode

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3011]
Enable the experimental bag player in dev by default.

**Comment by amacneil** [comment]
Seems potentially confusing? I guess I don't use dev mode, but why not just enable the feature flag manually?

**Comment by defunctzombie** [comment]
> Seems potentially confusing? I guess I don't use dev mode, but why not just enable the feature flag manually?

I could blast a message in our slack but folks are likely to forget. So this lets us start testing it when we work with bags during development (which is often) and identify any weirdness before we turn it on by default in production.

**Comment by amacneil** [comment]
Fair enough
