### ISSUE TITLE
Experimental player support for .mcap files

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3027]
Add support for reading .mcap files via the experimental player (IterablePlayer.ts).

The IterablePlayer uses a new mechanism for seekback to backfill the last message on each topic rather than the RandomAccessPlayer pattern of backfilling a specific amount of time. This new mechanism produces a better experience when seeking through data sources with infrequently published messages.

**Comment by defunctzombie** [comment]
@jtbandes Assigned to you as the owner per our planning discussion.

**Comment by defunctzombie** [comment]
I'll take the initial pass at adding this to studio. I may need help with adding support to the mcap typescript library for backfilling.

**Comment by jtbandes** [comment]
I once started on this task, long ago. This may or may not be helpful: https://github.com/foxglove/studio/compare/jacob/mcap-iterable
