### ISSUE TITLE
Properties documented as optional are not optional in Node Playground

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3045]
**Description**
`foxglove.LocationFix` is [documented](https://foxglove.dev/docs/studio/messages/location-fix) as only requiring `latitude` and `longitude`, but Node Playground nodes require all properties before they will compile.

Edit: This appears to apply to all `foxglove.*` schemas.

- Version: 1.4.0
- OS: mac

**Steps To Reproduce**

Nuscenes bag + NP node with the following content:

```typescript
import { Input, Message } from "./types";

type Output = Message<"foxglove.LocationFix">;

export const inputs = ["/gps"];
export const output = "/studio_node/gps";

export default function node(event: Input<"/gps">): Output {
  return {
    latitude: 0,
    longitude: 0,
  };
}

```

**Expected Behavior**
Successful node

**Actual Behavior**
```
Type '{ latitude: number; longitude: number; }' is missing the following properties from type '{ latitude: number; longitude: number; altitude: number; position_covariance: Float64Array; position_covariance_type: number; }': altitude, position_covariance, position_covariance_typeTypescript [26,3]
```

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/637671/159206897-ae3f9468-dc33-4a4b-a291-b68321df6a1c.png">

**Comment by foxymiles** [comment]
@defunctzombie This is coming from `@foxglove/rosmsg` right? Do we also want to rename that package?

```
import { RosMsgDefinition } from "@foxglove/rosmsg";

/** RosDatatypes is a map of datatype name to the datatype definition */
export type RosDatatypes = Map<string, RosMsgDefinition>;
```
