### ISSUE TITLE
[3d panel] add `foxglove.FrameTransform` support

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3050]
The `foxglove.FrameTransform` message describes a _transform_ between two coordinate frames. The transform direction is from the parent frame _to_ the child frame.

| field | type | description |
| --- | --- | --- |
| timestamp | Time | Transform time |
| parent_frame_id | string | Name of the parent frame |
| child_frame_id | string | Name of the child frame |
| transform | Transform | |

`foxglove.Time`

| field | type | description |
| --- | --- | --- |
| sec | uint32 | Seconds since epoch |
| nsec | uint32 |  Nanoseconds within the second |

`foxglove.Transform`

| field | type | description |
| --- | --- | --- |
| translation | Vector3 |  { x, y, z } |
| rotation | Quaternion |  { x, y, z, w } |

**Comment by amacneil** [comment]
Maybe drop `_id`, just call them `parent` and `child` (or `parent_frame` and `child_frame` if the former isn't obvious enough)?

Having "id" there makes me think that it should be a number.
