### ISSUE TITLE
Standardize Panel component/PanelToolbar styles

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#3054]
## Problem
Currently our panels vary widely in how you interact with them. Visualization panels tend create thier own UI's that overlay the visuals and text based data tend to use the PanelToolbar component. Some toolbars hide and show on hover and create issues for users selecting menus.

## Proposed change
Replace/Refactor the panel to handle the toolbar concept through props.

https://github.com/foxglove/ui-playground/pull/4

<img width="796" alt="Screen Shot 2022-03-22 at 2 57 43 pm" src="https://user-images.githubusercontent.com/924528/159405148-6eb337fb-6636-4f38-9544-3e9ccd981925.png">

## Challenges
Some panels use the toolbar for various searches. 
Examples: 
- Raw message (message path input), 
- Diagnostics (Panel Filter)
- Log (text search)
- Camera (camera image selection)
- Persistent toolbar takes up more vertical space. 

## Example of current panels
| Panel Name  | |
|---|---|
| 3D Panel | <img width="518" alt="Screen Shot 2022-03-22 at 2 40 56 pm" src="https://user-images.githubusercontent.com/924528/159403787-c21e46e4-870f-4941-9e36-75cbcf0aafab.png"> |
| Image Panel |<img width="449" alt="Screen Shot 2022-03-22 at 2 40 37 pm" src="https://user-images.githubusercontent.com/924528/159403788-f4bef86b-e9df-4787-b3e6-41e3a119bf6c.png"> |
| Tab | <img width="335" alt="Screen Shot 2022-03-22 at 2 44 40 pm" src="https://user-images.githubusercontent.com/924528/159403756-c975d1e7-b1ac-4303-b7c9-60edbc914e27.png"> |
| Log | <img width="336" alt="Screen Shot 2022-03-22 at 2 44 14 pm" src="https://user-images.githubusercontent.com/924528/159403768-c9cd96ab-e6d2-411c-9dc8-58d65cc58506.png"> |
| URDF | <img width="335" alt="Screen Shot 2022-03-22 at 2 43 57 pm" src="https://user-images.githubusercontent.com/924528/159403769-ec8b5729-bac7-476d-ba3f-1c00757df017.png"> |
| Raw message | <img width="204" alt="Screen Shot 2022-03-22 at 2 43 10 pm" src="https://user-images.githubusercontent.com/924528/159403774-330c989d-112d-4858-a047-068a791de1be.png"> |
| Diagnostic - Summary | <img width="329" alt="Screen Shot 2022-03-22 at 2 42 59 pm" src="https://user-images.githubusercontent.com/924528/159403777-50f84c63-a297-46d2-bd9b-dacca302f7aa.png"> |
| Diagnotics - Detail | <img width="328" alt="Screen Shot 2022-03-22 at 2 42 53 pm" src="https://user-images.githubusercontent.com/924528/159403780-70b9e420-cee0-4ed1-af50-651bfa00e1c2.png"> |
| State Transition | <img width="332" alt="Screen Shot 2022-03-22 at 2 42 48 pm" src="https://user-images.githubusercontent.com/924528/159403782-c3b19d58-78fb-48a0-9ee0-d53ce7fcba7a.png"> |
| Plot | <img width="651" alt="Screen Shot 2022-03-22 at 2 42 41 pm" src="https://user-images.githubusercontent.com/924528/159403783-bb1a3719-8f77-4282-8ff2-818f826f6a0e.png"> |
| Map | <img width="406" alt="Screen Shot 2022-03-22 at 2 42 19 pm" src="https://user-images.githubusercontent.com/924528/159403784-bcc89866-6c96-46d1-9eb0-6216ed5a96e1.png"> |

**Comment by amacneil** [comment]
Overall +++ to this effort.

Specifically looking at these icons I have no idea what the first 4 would do. maybe the first one is some sort of menu although its left placement indicates otherwise. No idea on the next 3. Then full screen and settings are obvious (I hope I got them right).

<img width="304" alt="image" src="https://user-images.githubusercontent.com/637671/159406462-9992c4c4-8026-43af-9768-a9e43fc007b3.png">

**Comment by defunctzombie** [comment]
https://studio.foxglove.dev/?layoutId=9999af94-710e-4154-bf7b-9af7c7f5aac5
