### ISSUE TITLE
Point Decay in 3D Panel broken

### ISSUE THREAD

**Issue by KarlssonW** [foxglove/studio#3056]
**Description**
Point decay time apparently no longer works

- Version: 1.4.0 or 1.3.0
- OS: Ubuntu ( Both 18.04 and 20.04 )

**Steps To Reproduce**
1.: View Any 3D Point source, either from a Bag or Live
2.: Add Decay Time via the Topic Settings Menu

**Expected Behavior**
Points would stay visible for the set decay time

**Actual Behavior**
No Points are visible at all, unless the decay time is 0

**Comment by defunctzombie** [comment]
@KarlssonW Is this for a PointCloud message or a LaserScan message?

**Comment by KarlssonW** [comment]
i have only tried this for PointCloud2 messages

**Comment by jtbandes** [comment]
If possible, can you share a sample bag file to demonstrate the problem, or provide more info about the data you're visualizing?

I tested out [this bag file](https://github.com/ROBOTIS-GIT/bags/blob/master/TB3_WAFFLE_SLAM.bag) for LaserScan:

https://user-images.githubusercontent.com/14237/160039324-6f5fe71a-b3b7-439b-ac7d-d04229362b21.mov

As well as [this bag file](https://storage.googleapis.com/foxglove-public-assets/demo.bag) for PointCloud2:

https://user-images.githubusercontent.com/14237/160039585-7e8de9be-389e-4e04-9fd1-78936d5adc5b.mov


Decay time seems to be working correctly in both bags.

**Comment by KarlssonW** [comment]
I've only had this rather big bag file at hand right now, but here:

https://drive.google.com/file/d/1He_LGpHJS5Xo7GZbMC9PHW1MbviLzFf-/view

My best guess is that it has to do with some of the other point fields, since the whole coloration UI also dissapears when i enter a decay time:

https://user-images.githubusercontent.com/12237450/160235871-2fc45d90-2a94-407d-8122-4fb819e2f66e.mp4

**Comment by jtbandes** [comment]
This problem is happening because the `header.stamp` time is used when calculating the decay time. These messages have a header.stamp that is very different from the log/receive time:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/14237/160724380-b348c20c-0ae6-492b-ad5b-8eb6eebc0ac9.png">

Since the header.stamp far is in the past, setting a decay time of 1 second results in the message being considered expired as soon as it is displayed.

**Comment by KarlssonW** [comment]
ahh ok that makes sense, thanks! odd that there wasnt a warning for the expired markers though.
