### ISSUE TITLE
.@norm modifier

### ISSUE THREAD

**Issue by bdemiroz-nvidia** [foxglove/studio#3072]
When I display a message in a panel, for vectors I get the norm next to it (see the image). However, when I display it separately, I don't see the norm. Is it possible to have a .@norm modifier such that we can display and plot it? This would be very useful for values like position, velocity, etc.

![Selection_817](https://user-images.githubusercontent.com/102264395/159808749-e88e8fd5-6238-4017-9f9a-83ba3b40e781.png)
![Selection_818](https://user-images.githubusercontent.com/102264395/159808753-364256da-01c5-4586-8bf5-31dc0317dcda.png)

note: I couldn't label this issue as "customer request". I think I don't have the permissions.

**Comment by jtbandes** [comment]
Related: https://github.com/foxglove/studio/issues/2250 https://github.com/foxglove/studio/issues/1254
