### ISSUE TITLE
"Show on startup" checkbox is cut off in open dialog

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3074]
The checkbox appears cut off, as does the bottom of the "Report a bug" text in the right-hand column:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/14237/159989121-4fdcec8b-8e50-46d1-95ab-9bcd19cdf4de.png">

**Comment by amacneil** [comment]
Upgrading to bug, this is getting worse and is a bad first run experience:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/637671/162393055-86885040-7578-4757-a69b-6ac4d50e749f.png">

**Comment by defunctzombie** [comment]
@2metres fyi - sending your way

**Comment by foxymiles** [comment]
I think this was caused by: https://github.com/foxglove/studio/pull/2563

Maybe setting a min-height here instead of a fixed height is the way to go?
