### ISSUE TITLE
Unhelpful data platform error message when user is not signed in

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3079]
**Description**
When user is signed out of the desktop app, and they try to open some data platform data in the desktop app, we currently give them an unhelpful "Status 401" error with a javascript stack trace.

- Version: 1.4.0
- OS: mac

**Current Experience**
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/637671/160195116-2ec100d5-c7a7-45b5-9933-b6e6a7dd5548.png">

**Desired Experience**
We should tell the user they are not signed in. We should not show a stack trace under any circumstances for network errors like this, they add no additional context and only serve to confuse the user and make our app look buggy.

**Comment by jtbandes** [comment]
Maybe related: https://github.com/foxglove/studio/issues/1917

**Comment by jtbandes** [comment]
@amacneil please try again now that #3093 is merged and see what you think.

The stack trace is still visible. I don't feel great about doing work to intentionally hide stack traces; it feels like it will just make debugging harder in the future.

**Comment by amacneil** [comment]
It's definitely an improvement (although the error text is missing some top padding, cc @2metres)

<img width="484" alt="image" src="https://user-images.githubusercontent.com/637671/161470922-1a7c1ac1-0af8-4f3b-92fd-c5c895e589a7.png">

I think we could still do a lot better though - e.g. there is no link/button to help me with signing in. In this particular error it's probably sensible to either redirect people straight to a login page, or show a modal with signin button. If that's hard to wire up, at least putting a signin button in the data source sidebar would help people move to the next step. 

Hard disagree on showing the stack trace. Stack traces are for unexpected exceptions, and even then they should probably only show in the developer console not our UI. Expected error cases such as "user not logged in" do not deserve a stack trace.
