### ISSUE TITLE
Layout storage stops working when LocalStorage quota is exceeded

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#3100]
**Description**
<img width="941" alt="Screen Shot 2022-03-30 at 9 31 39 am" src="https://user-images.githubusercontent.com/924528/160717637-3f6dfc55-0863-4820-a925-cae6adb643d1.png">

- Version: Dev
- OS: MacOS

**Steps To Reproduce**

Have a large number of layouts and load the example layout

**Expected Behavior**

**Actual Behavior**

**Comment by jtbandes** [comment]
I think we might want to just switch to IndexedDB for the layout storage. While having lots of layouts is not ideal we shouldn't be imposing arbitrary limits on users adding lots of layouts if they really want to.

**Comment by jtbandes** [comment]
> Why's it not ideal?

Because scrolling through a huge list is a bad UX. Maybe this is saying more about our layout UX than about the number of layouts.

https://web.dev/storage-for-the-web/#other

**Comment by foxymiles** [comment]
Sounds like the strategy here is to switch to IndexedDB and do a one-time migration from localStorage?

**Comment by defunctzombie** [comment]
> Sounds like the strategy here is to switch to IndexedDB and do a one-time migration from localStorage?

Yep.
