### ISSUE TITLE
`layoutId` query argument is ignored.

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3117]
When navigating to `studio.foxglove.dev` with a `layoutId` argument, the layout is not loaded (even tho I know this layout ID is valid because I copied it from the URL when I changed layouts):

https://studio.foxglove.dev/?layoutId=c02b6bc9-9492-4302-9cc1-238f28c3a5be

**Comment by foxymiles** [comment]
Fixed by https://github.com/foxglove/studio/pull/3171
