### ISSUE TITLE
Remote layout operations should happen immediately

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3118]
Whenever I make changes to layouts (delete, rename, etc) those changes should immediately update the remote layouts.

**Comment by jtbandes** [comment]
What if you're offline?

**Comment by defunctzombie** [comment]
> What if you're offline?

If you are offline then they should be queued. If you are online we should perform the operation faster than the "slow" sync window.

**Comment by jtbandes** [comment]
How about just initiating a sync immediately after making the change locally? i.e. skipping the existing sync timer.

**Comment by jtbandes** [comment]
By the way, what's the motivation for this ticket? Is there a UX problem you encountered?

**Comment by defunctzombie** [comment]
> By the way, what's the motivation for this ticket? Is there a UX problem you encountered?

I think I filed this after making a change to a layout and then sending a url to myself (in another session) and the layout wasn't updated when I opened it or some variant of that.

I'm gonna close this until I re-discover it with a more specific user facing example.
