### ISSUE TITLE
Visiting a url with a layoutId that is not yet loaded (from remote sync) doesn't work.

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3119]
If I make a layout and send a link to the layoutId to a team member, that layout does not load for them if they haven't sync'd their layouts.

Layout loading should work even if there hasn't been a sync.

----
* Sign in to your foxglove account.
* Open studio.foxglove.dev and let the layouts sync.
* Open https://studio.foxglove.dev/?layoutId=ea800f2c-f854-49de-8ef1-a2f7e1f31719 and the layout should open
* Delete all the localstorage items for cached remote layouts and refresh the page. The layout will not open and you'll see a `Select a layout in the sidebar to get started!` message.

This is a bad experience because when I make a new shared layout and send it to a team member to view they can't open the link.

**Comment by foxymiles** [comment]
What approach should we take here? Force a sync and then re-try to load the layout? Should we have some kind of modal state for this?

**Comment by defunctzombie** [comment]
My initial thought is that the CurrentLayoutContext/Provider needs to be enhanced to support a "loading" state. I believe right now we have a binary state: no layout and layout. With no layout we show the "select a layout from the sidebar" fallback, and with a layout we show the layout.

We need to update the state to a type that can represent four states: loading, no layout, layout, information. Now when we have the layout manager load a layout by id, we can update the layout context to indicate loading while the manager loads the layout. If there is no layout to load, then we use the no-layout state. If we have a layout we can show that, and finally if there is some permission error or load failure we can show that too (and maybe offer retry).

The **tl;dr;** is that we need to enhance the notion of the "current layout state" beyond binary present or not preset.
