### ISSUE TITLE
Protobuf `enum`s not shown in State Transitions panel

### ISSUE THREAD

**Issue by drldcsta** [foxglove/studio#3126]
We would like to be able to plot `state` as seen in the below example however it does not show up 

```syntax = "proto3";
import "src/msgs/header.proto";
 
package [REDACT];
 
/// An enumerated type to describe the state of the intersection detector
enum IntersectionStateEnum {
 INTERSECTION_STATE_NORMAL = 0;
 INTERSECTION_STATE_WARNING = 1;
 INTERSECTION_STATE_CRITICAL = 2;
 INTERSECTION_STATE_UNKNOWN = 3;
}
 
/// Status message emitted by the intersection detector
message IntersectionState {
 Header header = 1;
 IntersectionStateEnum state = 2;
 float speed_limit = 4;
 
 reserved 3;  // Removed speed_reduction_factor.
}
 
```

**Comment by jtbandes** [comment]
Blocked on https://github.com/foxglove/studio/issues/2214

**Comment by jtbandes** [comment]
Could we add some more clarification about what "does not show up" means? Are we talking about getting the names "INTERSECTION_STATE_NORMAL" to show up (which is what #2214 is about)?

**Comment by AndrewNolte** [comment]
I wont get the names, but it also won't plot the basic number

**Comment by jtbandes** [comment]
Cool, turned out to be a simple oversight with a quick fix: https://github.com/foxglove/studio/pull/3130

This fix actually made the enum names show up too, so not actually blocked on #2214 😅
