### ISSUE TITLE
Spacebar after adding a panel creates unexpected splits

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3142]
**Description**
1. open sample data set
2. add a panel
3. hit spacebar to start playback

result: unexpected splits! hitting spacebar more times creates even more splits!
expected: just play my file

- Version: main
- OS: web

https://user-images.githubusercontent.com/637671/161411512-716a44f1-c2f9-4391-98ad-17fef7c2d2aa.mov

**Comment by defunctzombie** [comment]
The "Diagnostics - Summary" item is still focused after your drag-drop action. When you push "space" you are "clicking" the list item.

Some ideas:
- Unfocus the item after the drag-drop action
- Close the Add Panel sidebar after the drag-drop action

**Comment by amacneil** [comment]
I see. Unfocus after drag-drop seems sensible.
