### ISSUE TITLE
Plot y-axis is not scaling properly

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#3168]
The *y* axis of a Plot panel is not scaling to fit the data. Perhaps this is related to plotting an array of values?

- Version: 1.6.0
- OS: macOS

The Plot panel is plotting an array of values from a message, which is displayed in the upper left. You can see that almost all of the values are greater than 1, yet the *y*-axis scale only goes up to 0.98.

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/108767/162596508-b89fbd32-d1dd-459b-af9c-f7a520590c70.png">

The scale *does* adjust with each incoming message but I can't figure out the logic to the values it picks.

**Comment by rgov** [comment]
Fixing the *y* minimum to 0 seemed to make it snap into shape (different data being shown than in previous screenshot).

<img width="557" alt="image" src="https://user-images.githubusercontent.com/108767/162596614-1bd51fc8-3864-4019-973f-3d0781a02bab.png">

**Comment by foxymiles** [comment]
I'm able to reproduce this with this node playground script:

```typescript
import { Input, Message } from "./types";

type Output = {
  values: number[];
};

export const inputs = ["/sample1"];

export const output = "/studio_node/output_topic";

export default function node(event: Input<"/sample1">): Output {
  const values = Array(30)
    .fill(undefined)
    .map((v) => 2 * Math.random());
  return {
    values,
  };
}
```
