### ISSUE TITLE
URL's layoutId does not update correctly when there is no data loaded

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#3188]
**Description**
- URL's `layoutId` does not update correctly when there is no data loaded

- Version: 1.7
- OS: Web

**Steps To Reproduce**

- Open Studio app (studio.foxglove.dev) without any data loaded
- Click on any layout in the sidebar

**Expected Behavior**
- URL updates to have a `layoutId` param

**Actual Behavior**
- URL does not update to have a `layoutId` param

**Comment by foxymiles** [comment]
In fixing this we should be careful not to undo the fix in https://github.com/foxglove/studio/pull/3031

**Comment by defunctzombie** [comment]
@foxymiles How do we make this url state stuff more robust? It seems we are constantly thrashing previous fixes.

**Comment by foxymiles** [comment]
> @foxymiles How do we make this url state stuff more robust? It seems we are constantly thrashing previous fixes.

It's tough IMO since we're compressing a lot of app state and behavior into a small state vector. Our app state is spread over several independent context and atomic state changes and updates across all of them is very challenging.
