### ISSUE TITLE
Invalid WebSocket URL pops up toast behind the open dialog

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3203]
When entering an invalid url such as `test` or `test:` in the websocket url field, the error pops up behind the open dialog in a toast notification. It would be better to display any error inline in the dialog instead.

<img width="866" alt="Screen Shot 2022-04-18 at 11 31 00 AM" src="https://user-images.githubusercontent.com/14237/163840261-c3b8f063-7a72-47a3-9e1b-dc83d03195a8.png">

**Comment by defunctzombie** [comment]
Picking up this issue as it has definitely annoyed me several times and I'd say is pretty terrible ux for what should otherwise be a simple text input error.

**Comment by jtbandes** [comment]
Additionally, the user should not be required to enter `ws://`, we should assume `ws://` if no scheme is specified.
