### ISSUE TITLE
Add option to copy current timestamp in ISO format

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3227]
**Description**
Creating events in Console requires the timestamp in ISO 8601 format:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/637671/164367072-7e3b1a29-9601-4fd3-a67a-49b07af10c2e.png">

Studio only gives you the timestamp in time-only or unix formats:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/637671/164367102-a9a52779-b551-4f4d-bdcf-f7571763be87.png">

To simplify the process of creating events, we need a way in Studio to copy the current timestamp in the format that Console expects it.

In the future we want to allow directly creating events from Studio, but this could be a good short term solution.

(request from Connor Buckland in community Slack)

cc @defunctzombie for triage

**Comment by bryfox** [comment]
Certainly doable; I think the trick will be the zone abbreviations — may need to pull in a tz database/library or find some way to work with that using `Intl`.

**Comment by amacneil** [comment]
understood re taking up more space. the goal of this ticket is just making copy pasting easier, we can solve that in the studio side or the console side.

although FYI the default studio format is `8:28:47.746 PM PDT` which doesn't give me the date so it's not going to be helpful. maybe we can make it easier to copy the full ISO8601 somewhere in studio.

**Comment by defunctzombie** [comment]
> although FYI the default studio format is `8:28:47.746 PM PDT` which doesn't give me the date so it's not going to be helpful. maybe we can make it easier to copy the full ISO8601 somewhere in studio.

It could be nice to show a tooltip? when you hover over the timestamp that has the timestamp in unix epoch or human readable (ISO). You don't have to change your settings to copy either one.

@2metres thoughts on using a tooltip here or if there's a better control or technique?

**Comment by amacneil** [comment]
How do you copy the text from the tooltip?

**Comment by defunctzombie** [comment]
> How do you copy the text from the tooltip?

Thats the age old question.

:trollface: maybe we need a panel who's sole purpose is to show you the current timestamp in every possible format.

**Comment by amacneil** [comment]
Just stick a small copy icon in the text box, and when you click it copy the full timedatestamp rather than the time-only timestamp. No one is going to be confused by that.

**Comment by defunctzombie** [comment]
> Just stick a small copy icon in the text box,

We are already constrained on space in that text box at times. I often see the time run past the end of the display. We'll see what we can come up with.

**Comment by defunctzombie** [comment]
I'm gonna close this out since we've completed the work to support pasting the timestamps that Studio does provide. If we get more feedback that folks want to see the text in another format we can re-visit the specific ask within Studio.
