### ISSUE TITLE
Clicking the "visibility" toggle for the Topic settings group does not hide the topics

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3241]
**Description**
On the map panel, when I click the 👁️ icon to toggle visibility on the topics group the topics are still visible.

<img width="764" alt="Screen Shot 2022-04-21 at 7 07 07 PM" src="https://user-images.githubusercontent.com/84792/164582362-366ced3b-637e-4bdf-8b19-c17836b46514.png">

<img width="755" alt="Screen Shot 2022-04-21 at 7 07 11 PM" src="https://user-images.githubusercontent.com/84792/164582356-d52e6225-e553-4127-b7e6-4599ef49e0d9.png">

**Comment by defunctzombie** [comment]
@foxymiles assigning to you since this is from your recent change to migrate the map panel to the settings sidebar

**Comment by foxymiles** [comment]
We've temporarily turned these off until we have thought through a bit more how we want them to work.
