### ISSUE TITLE
Proposal: remove "header stamp" playback dropdown

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3282]
No one can tell me what this dropdown is used for:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/637671/165849920-f95f2fc6-45b2-4d38-a742-388c35afd33c.png">

The 3d panel seems to ignore it, and uses header stamp or receive time depending on the topic. The plot panel definitely ignores it and uses its own per-series settings. So I'm not clear what this dropdown actually affects and why someone would use it.

**Comment by defunctzombie** [comment]
The dropdown would affect _playback_. Imagine "Header stamp" means "publish time" playback. The problem tho is that none of the data we typically play is indexed in a manner to support such a playback "correctly". Right now I believe the player logic buffers some window of data, re-orders it by header stamp, and then plays that.
