### ISSUE TITLE
Adding decay time makes point cloud disappear

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3283]
**Description**
I have a file with sensible receive times in a PointCloud2 message, and incorrect "header stamp" values.

Playing back this file works fine. However, if I add "decay" to the topic in 3d panel, the 3d panel goes blank.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/637671/165850137-85b5e7b3-84ba-4001-bfbd-ea244b083e77.png">

Apparently this is due to the invalid header stamp times. If we are playing back by receive time, then we should decay by receive time, and header stamp time shouldn't factor in to it.

- Version: main
- OS: web

**Comment by foxymiles** [comment]
Looks like this is a consequence of this change: https://github.com/foxglove/studio/pull/2986

**Comment by defunctzombie** [comment]
@foxymiles Whats the next step here? I noticed an attempt at this in #3314 but that didn't work because it was applying too broadly. Is there a fix here that should be specific to point clouds?

@jhurliman it looks like this broke in #2986 - what do you think should be done to fix this?

**Comment by foxymiles** [comment]
@defunctzombie Seems like there are people that understand this code much better than I do and have ideas on how it should be fixed so I'm probably not the best person to take this one up.

**Comment by jhurliman** [comment]
I can take this one. Timestamp handling in Old3D is very brittle right now, hopefully I can come up with a surgical fix for this specific issue without additional side effects.

**Comment by defunctzombie** [comment]
We've decided it is not worth investing in fixing this in old3d and focus on implementing this correctly in new3d.
