### ISSUE TITLE
Studio freezes when trying to step forward towards the end of a rosbag

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#3285]
**Description**

- Version: 1.9.0
- OS: macOS 12.3.1

**Steps To Reproduce**

Open a particular bag file, seek to the very end, keep stepping forward to try to find the last message.

**Actual Behavior**

UI becomes unresponsive. If Inspector is already open, then I see a very rapid log spew of identical messages like this. The playback head appears to jump back to the beginning of the file.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/108767/165873018-4a4e7c58-7f73-46c7-b123-19904b174273.png">

**Comment by defunctzombie** [comment]
Confirming I am able to reproduce. Looking into this.

**Comment by defunctzombie** [comment]
@rgov I've identified the issue and created a fix in #3291. We'll get this in the next release on Monday.
