### ISSUE TITLE
Fully support autoware universe

### ISSUE THREAD

**Issue by xczhanjun** [foxglove/studio#3289]
Ros2 based  Autoware universe is under active development, this is a good opportunity for foxglove to grow together with autoware.

**Comment by defunctzombie** [comment]
@xczhanjun Is there something specific you have in mind? Foxglove already works with ROS2 systems.

**Comment by jtbandes** [comment]
Closing this since we don't have anything actionable here and haven't gotten more feedback about which specific features would be desired.
