### ISSUE TITLE
When a connection to a topic is reestablished, it should clear the errors

### ISSUE THREAD

**Issue by MathieuMarchand** [foxglove/studio#3293]
**Description**
When a node that publishes on a topic is killed or dies and a custom extension panel is subscribed to this topic, an error message is displayed on foxglove. But when the node is re-run and the topic is being used again, the error is not cleared even though the whole system is valid.

- Version: 20.04.4
- OS: Ubuntu

**Steps To Reproduce**
1. Subscribe to a topic on a custom extension published by a ros node
2. Kill the node that publishes on the topic
3. re-run the node 

![image](https://user-images.githubusercontent.com/44498497/166122753-b425c87a-b2ab-4104-a20a-819450fc014e.png)

**Expected Behavior**
When the connection to a topic is reestablished, the errors should be cleared

**Actual Behavior**
When the connection to a topic is reestablished, the errors are still there even though the topic is being used

**Comment by jtbandes** [comment]
Are you using Rosbridge or a native (TCP) ROS connection?

**Comment by MathieuMarchand** [comment]
The native ROS connection to ROS 1
