### ISSUE TITLE
Label oriented wrong way

### ISSUE THREAD

**Issue by AndrewNolte** [foxglove/studio#3341]
**Description**

![image-20220505-043435](https://user-images.githubusercontent.com/24322714/167430067-a88d952e-58d6-4c18-96b0-071c300e21e3.png)

- Version:
- OS:

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by jtbandes** [comment]
This will be something to address in the new 3D panel.

**Comment by defunctzombie** [comment]
> This will be something to address in the new 3D panel.

Is this not easy to fix with the current 3d panel?

**Comment by defunctzombie** [comment]
@jtbandes @jhurliman is this fixable in the current 3d panel? Or is there a workaround we can propose? Why is the label inverted?

**Comment by jtbandes** [comment]
This regressed when we rewrote the "render frame" stuff as part of the TF overhaul project. I'm not aware of what would be involved in the fix, maybe John can advise since he's more familiar with how the scene is rendered in the current panel.

**Comment by defunctzombie** [comment]
We've decided to tackle this for the new3d panel and make sure it works correctly there.
