### ISSUE TITLE
rgba8 support for raw images

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3345]
It is not currently possible to send raw images with an alpha channel. Supporting `rgba8` in this code block https://github.com/foxglove/studio/blob/main/packages/studio-base/src/panels/ImageView/lib/renderImage.ts#L132-L173 would resolve the issue.

**Comment by jtbandes** [comment]
Duplicate of https://github.com/foxglove/studio/issues/1273 ?

**Comment by jhurliman** [comment]
Closing as duplicate of #1273
