### ISSUE TITLE
Custom message sent but not received properly

### ISSUE THREAD

**Issue by saumil-kapadia-ola** [foxglove/studio#3379]
I am using bag_recorder to subscribe to topics : https://github.com/joshs333/bag_recorder
When i send string messages from foxglove, bag_recorder is unable to receive it but if same message is sent using commandline "rostopic pub /record/start std_msgs/String "standard"" then it is received.

**Comment by saumil-kapadia-ola** [comment]
Yes. Publish panel with String message ``{ data: "standard" }``

**Comment by jtbandes** [comment]
Can you try the Rosbridge connection (you will need to [run the rosbridge server](https://wiki.ros.org/rosbridge_suite/Tutorials/RunningRosbridge)) and see if publishing works on that connection?

**Comment by defunctzombie** [comment]
@saumil-kapadia-ola were you able to try rosbridge?

Which version of studio are you using in the above? Can you also try with the latest version of studio?

**Comment by defunctzombie** [comment]
Closing for lack of response.
