### ISSUE TITLE
Add settings for `geometry_msgs/PolygonStamped` message type

### ISSUE THREAD

**Issue by plasota** [foxglove/studio#3396]
It would be useful to have a few settings for the `geometry_msgs/PolygonStamped` message type. The default line thickness is too thick for our application, making it difficult to discern if a point is inside or outside of the polygon.

Some suggested settings:
- Line thickness
- Line color
- Line transparency

Thanks!

**Comment by jhurliman** [comment]
Line width and color/transparency settings are implemented for PolygonStamped in New3D
