### ISSUE TITLE
Publish pose from 3D panel not working with ROS2 + rosbridge

### ISSUE THREAD

**Issue by helenol** [foxglove/studio#3409]
I'm attempting to publish a goal to ROS2 Nav2 from foxglove, communicating to ROS2 over rosbridge. I've changed the topic name for the pose publisher appropriately (`/goal_pose`), and it appears to reach the rosbridge, but the published point still contains the header.seq field which is no longer present in the ROS2 message header.

```
[rosbridge_websocket-1] [ERROR] [1652968275.114241805] [rosbridge_websocket]: [Client 0] [id: publish:/goal_pose:576] publish: Message type geometry_msgs/PoseStamped does not have a field header.seq
```
Is the error from the rosbridge output.

Hopefully this is an easy problem to fix, as it's the main feature that I still need rviz for. :) Thanks for the *amazing* work on this tool!

- Version: 1.11.0
- OS: Ubuntu 20.04

**Steps To Reproduce**

1. Run a robot in ROS2 over rosbridge.
2. Attempt to publish a pose goal on /goal_pose from the 3D UI.
3. `ros2 topic echo /goal_pose`

**Expected Behavior**
1. Published message should appear on `ros2 topic echo /goal_pose`.

**Actual Behavior**
1. No message appears, and rosbridge outputs an error: ```[rosbridge_websocket]: [Client 0] [id: publish:/goal_pose:576] publish: Message type geometry_msgs/PoseStamped does not have a field header.seq```

**Comment by jtbandes** [comment]
Thanks for reporting! This issue is already tracked in https://github.com/foxglove/studio/issues/2834, you can follow along there for updates.
