### ISSUE TITLE
Automatically redirect to login for data platform player

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3411]
**Description**
If someone shares a data platform link with me, but I am not signed in to Studio, I get an error:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/637671/169350770-c0c22551-9bdf-49d6-bd6f-e93e79d2dd44.png">

Instead of this unhelpful error, we should just redirect the user to the signin page (or on desktop, pop up the signin dialog).

**Comment by amacneil** [comment]
@foxymiles want to take a look at this?

**Comment by foxymiles** [comment]
Sure I can work on this.
