### ISSUE TITLE
Refactor plot panel to use settings sidebar

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#3432]
Now that settings nodes can have actions ( #3419 )  we should refactor the plot panel to make use of the settings sidebar

**Comment by defunctzombie** [comment]
@foxymiles What happened to the PR you had for this? Did we merge that under a feature flag or pass on it for now? I really liked where it was going.

**Comment by foxymiles** [comment]
https://github.com/foxglove/studio/pull/3470

I closed it since we didn't seem to have a clear path forward but can re-open if you think we should continue to explore this. I think it would be worth discussing some of our ideas for a more compact representation of some settings fields.
