### ISSUE TITLE
Split topics into folders using "/"

### ISSUE THREAD

**Issue by adamcircle** [foxglove/studio#3449]
Suppose I have the following topics:

```
/folder1/topic1
/folder1/topic2
/folder1/topic3
/folder2/topic1
/folder2/topic2
/other
```
I would expect this to be formatted such that the first three topics wind up in a folder called `folder1`, the next 2 topics wind up in `folder2`, and the last topic is at the top level.

**Comment by jtbandes** [comment]
Hi, can you describe more about which part of the UI you are talking about? Topics appear in several places: the data source sidebar, the 3D panel's topic picker, and dropdown menus in several other panels.
