### ISSUE TITLE
Support for protobuf `oneof`

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3480]
The protobuf support in `@foxglove/mcap-support` should support messages that use `oneof`.

https://github.com/foxglove/studio/blob/e5d1f84914d9d63ce4ae032d40807b4229b696df/packages/mcap-support/src/protobufDefinitionsToDatatypes.ts#L42

**Comment by amacneil** [comment]
I assume this will make message path autocomplete a little crazy if people do this right?

I think we should still support it either way.

**Comment by jtbandes** [comment]
I think we would probably treat it the way the protobuf generated code does, where the oneof is like a message with a bunch of optional submessages for each alternative (kind of like our ImageAnnotations / Markers container messages, but with single items instead of arrays).

**Comment by defunctzombie** [comment]
We believe this works until we learn otherwise with a specific example.
