### ISSUE TITLE
Image panel - fix image annotation topics sort order

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3505]
**Description**
When the image annotation topics were in the toolbar as a dropdown we would sort "relevant" topics before other topics so they appear first in the list. Relevant topics are those matching the image topic prefix.

![image](https://user-images.githubusercontent.com/84792/172258070-f88a2221-d5ae-4210-80ac-d047269a4165.png)

With the new annotation topics list in panel settings this list is unsorted making the relevant topics harder to find.

**Comment by amacneil** [comment]
Besides updating the new sidebar with the improved sort order, it would be nicer still if we could visually separate "recommended" vs "other" (non official terms) annotation topics. E.g. a menu separator:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/637671/172265052-ee81f70c-1ccd-443b-8640-3f71feed55b9.png">

**Comment by amacneil** [comment]
Related - https://github.com/foxglove/studio/issues/3509
