### ISSUE TITLE
KeyListener not working as expected in Image Panel

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#3542]
**Description**
Zoom shortcuts no longer work on Image panel, may be larger image with KeyListener

- Version: Web
- OS: Chrome on macOS
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Example bag
- ROS distro (if applicable):

**Steps To Reproduce**

Select image panel and press `+`, `-`, `0`  

**Expected Behavior**
```ts
  const keyDownHandlers = useMemo(() => {
    return {
      "=": zoomIn,
      "-": zoomOut,
      "0": onZoom100,
    };
  }, [onZoom100, zoomIn, zoomOut]);
```

**Actual Behavior**
No zooming

**Comment by foxymiles** [comment]
I think we'll need to set `tabIndex` on elements we want to receive keyboard focus in order for the event handlers to fire:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets#using_tabindex
