### ISSUE TITLE
Add pushbutton inputs to panel settings

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#3543]
I would like to be able to add a pushbutton to my panel's settings tree and have it trigger the action handler.

Example use case: I have a list in my panel's settings and I would like to give the user a button to add a new entry to the list.

**Comment by defunctzombie** [comment]
@foxymiles How's the new 3d panel doing this or the plot panel? IIRC there is some mechanism to add new items?

**Comment by rgov** [comment]
Thanks! I got it to work with actions. It's a little busy, but workable. Feel free to close.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/108767/172900086-276a1b50-c544-4203-a8e4-91c329d96bb7.png">
