### ISSUE TITLE
Allow control of disclosure triangle status in panel settings 

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#3544]
I have a panel with a long list of settings. When I open the settings pane, every level of the tree starts expanded:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/108767/172761190-ee4fc7ae-9441-4f97-9088-7b307c862434.png">

It would be nice to have these start collapsed so that it is easier to navigate.

**Comment by amacneil** [comment]
> Gamepad panel

🎉 awesome!

**Comment by defunctzombie** [comment]
I think there's an option for each node whether it is collapsed or not at the start. @foxymiles ?
