### ISSUE TITLE
Settings action menu gets fatter on narrow windows

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#3553]
Foxglove Studio 1.13.2

On a wide window, the action menu for a settings node looks like this:

<img width="129" alt="image" src="https://user-images.githubusercontent.com/108767/172914523-859e9713-a4d4-4766-8004-553d3553a163.png">

On a narrower window:

<img width="124" alt="image" src="https://user-images.githubusercontent.com/108767/172914504-abbd7525-91f1-48b2-84d5-4a8b3797b625.png">

**Comment by defunctzombie** [comment]
@2metres assigning to you to tackle whatever css evil has happened here.

**Comment by 2metres** [comment]
I think this was resolved by https://github.com/foxglove/studio/pull/3575
