### ISSUE TITLE
Image view zoom to fit doesn't always work.

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#3560]
**Description**
The "zoom to fit" button in the image panel zoom menu doesn't always work.

- Version: studio.foxglove.dev
- OS: macOS
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): nuscenes
- ROS distro (if applicable): -

**Steps To Reproduce**
1. Open sample data
2. Create a new layout
3. Add an image panel
4. Zoom out as far as possible
5. Select "zoom to fit" from the zoom menu

**Expected Behavior**
The image should zoom to fit.

**Actual Behavior**
Nothing happens.

Note that if you zoom slightly after doing zoom to fit it seems to be zooming from a full zoom which suggests that the zoom is being set but it's not triggering a re-render of the image.

**Comment by 2metres** [comment]
Appears to effect "zoom to fill" as well
