### ISSUE TITLE
GLIBC_2.29 not found

### ISSUE THREAD

**Issue by osholsonel20** [foxglove/studio#3606]
**Description**

- Version: 1.14.2
- OS: Ubuntu 18.04 arm64
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS 1
- ROS distro (if applicable): Melodic

**Steps To Reproduce**

- Download the debian file on a Ubuntu 18.04 arm device.
- Run foxglove-studio

Previous version of Foxglove successfully ran, now after the update it no longer does on this specific device combination

![output](https://user-images.githubusercontent.com/46691182/173675524-8ab8628c-ad60-4ccc-8c7c-a44b5a1dfe85.png)

**Comment by defunctzombie** [comment]
I suspect this is caused by the upgrade of Electron: https://github.com/foxglove/studio/commit/f161057f53e6b4e512b29116589327ca0ca056f4

**Comment by defunctzombie** [comment]
Electron identified the issue and has a fix: https://github.com/electron/electron/pull/34491

This fix is not yet in a release of electron for v19 but based on it merging into the v19 backport branch should be in v19.0.5

**Comment by amacneil** [comment]
In the meantime, we keep old versions of Foxglove in our apt repo, so you should be able to downgrade with:

```sh
sudo apt install foxglove-studio=1.13.2
```

**Comment by osholsonel20** [comment]
Just kind of a heads up here, I removed electron 19.0.3, and called "yarn add electron@npm:19.0.5". Built the debian then tested on an Arm64 Ubuntu 18.04 device and it's working as intended! 19.0.5 was just recently added to npm https://www.npmjs.com/package/electron
