### ISSUE TITLE
Changing panel type results in "Loading panel settings"

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3625]
**Description**
1. Open panel settings sidebar
2. Change the panel type
3. Panel settings gets stuck in "Loading panel settings" state

https://user-images.githubusercontent.com/637671/173993879-c025c2d7-ab81-4d56-b37d-9a9cc1d3e3e6.mov

**Comment by foxymiles** [comment]
This one is also a very old bug.

**Comment by foxymiles** [comment]
Looks like the issue here is that when we change a panel type we don't update the selected panel id. It still points to the old panel id.

**Comment by amacneil** [comment]
@foxymiles your PR fixed the issue described, but now there is a new bug. If settings sidebar is closed, and I change the panel, it gets "selected".

I also keep getting stuck in panel-select mode now. Infuriatingly, this seems to happen more often when I start screen recording, but I can trigger it sometimes without that too. When it happens, this is pretty bad, and as far as I can see is new behavior. Let me know if you can repro, might be easier to revert https://github.com/foxglove/studio/pull/3637 while we figure it out.

https://user-images.githubusercontent.com/637671/174716301-f0a49bbd-9740-42d8-bc96-b66e651ae5c1.mov
