### ISSUE TITLE
Dropping a panel between two panels causes it to replace entire tab

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3631]
**Description**
1. Create a tabbed layout
2. Drag and drop one of your panels exactly between two other panels
3. The entire tab contents is replaced with that panel 😱 

I tried this with a non-tabbed layout and it behaves correctly, the drop is rejected and the dragged panel stays in its original position.

https://user-images.githubusercontent.com/637671/174185737-026e5cc1-6a26-49ee-ab51-b8162f0ed754.mov

**Comment by foxymiles** [comment]
Looks like this bug predates our recent toolbar drag & drop changes.
