### ISSUE TITLE
macOS screen record causes Foxglove to get stuck in panel multi-select mode

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3657]
**Description**
Today in "really weird bugs"

- open a layout
- hit cmd+shift+5 to show the screen record options
- hit esc to close
- clicking in the studio browser window is now stuck in multi-select mode
- the only way you can get out of this mode is by clicking out of the chrome window and then going back

In this video, about half way through I pull up the screen record options, and you can see we get stuck in panel multi-select mode. Then at the end I fix it by clicking away.

https://user-images.githubusercontent.com/637671/174845653-3836ff32-723d-4bc1-803e-00f509b48ded.mov

**Comment by amacneil** [comment]
cc @foxymiles this happens even after https://github.com/foxglove/studio/pull/3653. I haven't gone back to see when it was introduced, but I screen record quite a bit and only just noticed it yesterday.

**Comment by foxymiles** [comment]
Bizarre. I'll take a look.

**Comment by foxymiles** [comment]
Yeah this is probably a conflict between our hotkeys and the mac screen record hotkeys.

**Comment by foxymiles** [comment]
@jtbandes Yeah you're right the app never gets the shift up.

**Comment by jtbandes** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1194004
