### ISSUE TITLE
Can't click on follow controls when 3D panel is narrow

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3665]
[Old3D] The follow control / frame selector is overlapped by some invisible element that makes it impossible to click:

https://user-images.githubusercontent.com/14237/174918091-048d7b48-ff70-453b-ac74-13e808953162.mov

**Comment by defunctzombie** [comment]
Closing this as not planned. We are focusing on 3D (beta) which uses a different UI for topic management.
