### ISSUE TITLE
[New3D] Camera image doesn't move  when change distance of camera info on setting panel

### ISSUE THREAD

**Issue by belopot** [foxglove/studio#3670]
**Description**
Camera image doesn't move  when change distance of camera info on setting panel

- Version: 1.15.0-dev
- OS: Web
- Data source: Sample data

**Steps To Reproduce**
1. Open New 3D panel settings.
2. Change the distance of camera_info in Topics
![image](https://user-images.githubusercontent.com/46432435/175105135-d9590e6f-8fd5-4fb5-b5df-6ac8e4c4d224.png)

**Expected Behavior**
The camera image should move to a new position
![image](https://user-images.githubusercontent.com/46432435/175106310-551d0053-9667-4844-8a28-265164c8efe5.png)

**Actual Behavior**
The camera image doesn't move to a new position
![image](https://user-images.githubusercontent.com/46432435/175106336-89c9eb91-f2b6-4a13-9498-d7226cbfd3cb.png)

**Comment by belopot** [comment]
@amacneil @jhurliman If you want. I will fix with myself

**Comment by jhurliman** [comment]
This is working as intended. The purple frame and the image are two separate topics being visualized. You can change the distance of the image using the settings for the image topic.
