### ISSUE TITLE
Choosing to plot multiple values via the Raw Messages panel does not work as expected

### ISSUE THREAD

**Issue by drldcsta** [foxglove/studio#3672]
If you have the raw messages panel open and choose to plot two separate things, the first time you click "create line graph" it will open the plot panel, start drawing the data and create a legend entry for what you clicked. When you click a second "create line graph" the data starts getting plotted, but the legend does not get updated.  My expectation is that the legend will get updated with both values. 

- Version: 1.15.0
- OS: Ubuntu 22.04 (via parallels on an m1 Mac)
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): rosbridge connection to ros2 
- ROS distro (if applicable): humble

https://user-images.githubusercontent.com/4950919/175115506-76cdd66c-9fdd-4058-8ae2-8319ceb7433e.mp4

**Comment by foxymiles** [comment]
Maybe a side effect of https://github.com/foxglove/studio/pull/3629
