### ISSUE TITLE
Related settings in Map panel are not appropriately grouped together

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#3673]
**Description**
- Related settings in Map panel are not appropriately grouped together

<img width="349" alt="Screen Shot 2022-06-22 at 12 41 55 PM" src="https://user-images.githubusercontent.com/6993359/175125799-de956fd9-bcea-417d-8ba6-c6f07195e5b2.png">

- Version: 1.15.0
- OS: macOS
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): N/A
- ROS distro (if applicable): N/A

**Steps To Reproduce**

- Open Map panel and select "Custom" for the Tile layer

**Current Experience**
- The Custom tile URL option shows up at the end of the current settings list (i.e. not next to the original Tile layer setting)

**Desired Experience**
- The Custom tile URL option should show up next to the original Tile layer setting

**Comment by defunctzombie** [comment]
Thx for the fix @foxymiles . For future reference @esthersweon this could definitely rise to the level of a UX bug. Good catch.
