### ISSUE TITLE
Popup to notify existing users about new panel settings location

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3676]
Some users are confused because we didn't tell them where we moved panel settings (e.g. https://github.com/foxglove/studio/issues/3270).

Image panel, Map panel, and New3D especially now rely heavily on the panel settings. We should show existing users a one-time tooltip popup to notify them of this change.

**Comment by amacneil** [comment]
@foxymiles @2metres can we ship something for this this week?

I suggest a small popup that shows up once per person, grab the first panel that has a settings cog in their layout, and show the popup next to that. New users should not see the popup at all.

A quick way I can think of to differentiate new vs existing users is check the analytics ([first_seen_month](https://github.com/foxglove/studio/blob/main/packages/studio-base/src/services/AmplitudeAnalytics.ts#L56)). There might be a cleaner way to do this but it would work fine.

Not sure where/how you want to store the "dismissed" state.

**Comment by foxymiles** [comment]
@defunctzombie @amacneil Would we should this even for users that use the app for the first time a year from now?

**Comment by foxymiles** [comment]
@amacneil I don't see a way to fetch data back from analytics to check if this is a user we've already logged.

**Comment by amacneil** [comment]
> @defunctzombie @amacneil Would we show this even for users that use the app for the first time a year from now?

My vote is no. As I said above "New users should not see the popup at all".

Although @foxymiles you're right I also can't see any way to read user properties in analytics. So I guess we need to track in localstorage alongside some "first seen" timestamp so we can avoid showing it to new users. You could probably initialize "first seen" from the creation dates of layouts or something.

**Comment by defunctzombie** [comment]
What's wrong with showing an indicator to new users that they can find panel settings by clicking the settings cog? Do we think we won't get it right and it will be annoying?

**Comment by amacneil** [comment]
I think the tooltip should say "FYI we have moved settings here". I find it very annoying when I sign up for an app as a new user and the first thing I have to do is click through a bunch of "hey we have a new feature, hey we moved xyz" when I have never used the app before. We should solve first-run experience separately.

**Comment by defunctzombie** [comment]
We've decided the window for informing users of this change has passed. In the future we will provide a transition notice alongside landing sweeping UI changes.
