### ISSUE TITLE
Unable to rotate/zoom into the 3D view using a touch screen

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3677]
From https://github.com/foxglove/studio/issues/1891

> [adityakamath](https://github.com/adityakamath) commented [on Sep 18, 2021](https://github.com/foxglove/studio/issues/1891#issue-1000130376)
I use Foxglove Studio on a laptop which has a touch screen, but I am unable to use Foxglove with it. I am forced to use a mouse (which means I cannot carry my laptop around behind my robot). I am not sure if it is an issue with my laptop or are touch screens not supported in general?
> 
> If its the latter, would love to see touch screen support in the future..
> 
> Version: Foxglove Studio v0.18.1
> OS: Windows 10
> Laptop: Asus Zenbook Flip 14

> Hi @jtbandes, to elaborate, I am able to click and select things on the Studio dashboard, but unable to rotate/zoom into the 3D view using the touch screen.
> 
> PS. I am using the windows application, not the browser view.

**Comment by LeZhang13** [comment]
Hey, guys! I use the V1.17.1 version studio in Ubantu+WIN10+macOS system.And I connect a touch screen to use the Foxglove Studio.
As my test, in Ubantu, I can use my screen touch function to move forward/left/right/backward in 3D panel as the w/a/s/d(or the mouse left key), but can't operate zoom in/zoom out or Pan/rotate. 
And can't use screen touch function( move forward/left/right/backward in 3D panel as the w/a/s/d) in win10 and macOS. (I am able to click and select things on the Studio dashboard too).
Can I reuqest the zoom in/out and Pan and rotate support for screen touch function for Ubantu system? I think this will be more cool! 
Thanks~
The test video in Ubantu1804:

https://user-images.githubusercontent.com/89899260/179231062-73dac4cd-ee53-41e3-89ea-79ccf1c5c02a.mp4


The test video in win10:

https://user-images.githubusercontent.com/89899260/179231085-6714d2b8-fd87-48ac-9c71-8ca32832c245.mp4

Studio version:
![image](https://user-images.githubusercontent.com/89899260/179231194-e8035308-7569-49b8-9eb4-45c019d7b145.png)
