### ISSUE TITLE
`min` support for `vec2`/`vec3` SettingsTreeField inputs

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3690]

**Comment by foxymiles** [comment]
Do you want the same min/max applied to all fields of the vector?

**Comment by jhurliman** [comment]
Yes. I suppose it could be `[number | undefined, number | undefined, number | undefined]` but it seems overkill to me. I think just a single number applying to all fields is sufficient. I forgot to mention in the title but `max` should be added as well.

**Comment by defunctzombie** [comment]
Moving this issue to the 3d panel project not settings and panel ux since this is new work coming from 3d panel requests.
