### ISSUE TITLE
Support setting and reading variables in panel extension api

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3705]
Some panels allow the user to interact with objects (i.e. the 3d panel lets users click on a marker and see its properties). When an object is selected in such a panel, it should be possible for the panel to update a global variable with a value (usually the selected object).

Other panels should be able to see this value (similar to how user scripts can read variables).

It should be possible to reference this variable (or its fields) within the message path syntax.

**Comment by defunctzombie** [comment]
We need to make a call on whether we want this feature for GA.

**Comment by jhurliman** [comment]
Summary from our discussion today on the path forward:

- Add two new methods to the panel extension API for reading the list of all global variables and setting a global variable as key + value, where value is a POD/POJO. (This API should probably closely mirror how parameters are handled in the extension API.)
- The 3D panel automatically calls `setVariable("selected", currentSelection)` whenever a renderable is selected, and `setVariable("selected", undefined)` on deselection. The `"selected"` variable name can be changed in panel settings.
- User Scripts have access to these global variables somehow. (JH: I'm not familiar with this aspect of global variables, is there a `getVariable("selected")` function in user scripts?)
- Message path syntax is updated to support sub-fields of global variables. For example, the currently selected object might be from the `/tracked_objects` topic, but I want to view `/planning.entities[:]{id==$selected.id}` in Raw Messages.

The net result is less user configuration to unlock this feature. You don't have to configure any variable linking, the functionality starts working as soon as you click on something in any 3D panel. The message path syntax for this is still a challenging learning curve, but we can provide copy-paste examples in the documentation now.

**Comment by defunctzombie** [comment]
> * User Scripts have access to these global variables somehow. (JH: I'm not familiar with this aspect of global variables, is there a `getVariable("selected")` function in user scripts?)

User scripts get the variables as the second argument to their function. The first argument is the message event and the second is the global variables.

**Comment by jhurliman** [comment]
The extension API change was merged in #3941. The change to New3D is in #3951 but with a lesser scope: a `selected_id` variable is used and only for markers. This obviates the need to change message path syntax right away.
