### ISSUE TITLE
Support picking of individual items in instanced renderables & point clouds

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3707]

**Comment by jtbandes** [comment]
Why second pass instead of assigning an id per instance during the first pass?

**Comment by jhurliman** [comment]
That could work if we think up a way to assign non-colliding IDs inexpensively.

**Comment by defunctzombie** [comment]
Had a chat and going to push this until after GA.

This ticket is about selecting individual points in point clouds.

**Comment by jtbandes** [comment]
Also applies to individual cubes/spheres in cube_list/sphere_list markers, right?

**Comment by jhurliman** [comment]
Selecting cubes/sphere in lists works fine. You are shown the full marker message that contains the specific selection though, instead of drilling down to the array index for the specific cube or sphere you clicked on.

**Comment by defunctzombie** [comment]
Re-surfacing this as higher priority. This is a feature of the existing 3d panel and is now a customer request. At minimum having the ability to click a point cloud point and see the x/y/z. We can re-target the issue for that specific feature if thats easier than the larger scope this issue might describe.
