### ISSUE TITLE
Position-only follow mode

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3710]

**Comment by jtbandes** [comment]
Do we have an idea of how important this is to our users?

**Comment by defunctzombie** [comment]
Let's drop it - if we get requests to add it we can come back to it.

**Comment by defunctzombie** [comment]
We got a request to add this so we've brought it back in scope.

**Comment by defunctzombie** [comment]
Related: https://github.com/foxglove/studio/pull/3926

**Comment by defunctzombie** [comment]
John: search for "unfollow pose snapshot"
