### ISSUE TITLE
[New3D] Labels should be above (+Z) coordinate frame axes in the fixed frame, not the local frame

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3716]
We currently set the `FrameAxisRenderable` label child to <0, 0, 0.4>. This works in simple cases, but if the child->parent transform has a rotation, the label will not be 0.4 units above the `Axis`. The proper solution is likely more involved since it would require updating per frame.

The 0.4 constant is worth reconsidering as well. Now that labels and frame axes can be resized, maybe it should be based on the frame axis scale or label size.

<img width="1166" alt="Screen Shot 2022-06-25 at 5 27 30 PM" src="https://user-images.githubusercontent.com/195374/175794568-9d37a28b-adbb-45da-9e11-7b64aeb7889a.png">

**Comment by jtbandes** [comment]
Is there a story that demonstrates this issue already?
