### ISSUE TITLE
Incorrect error message for mcap file with no messages using experimental mcap player

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3731]
When dropping this file into Studio, I get "The mcap file is unindexed. Only indexed files are supported."

[bad.mcap.zip](https://github.com/foxglove/studio/files/8996255/bad.mcap.zip)

However, the file is in fact indexed, so the error message is wrong.

![image](https://user-images.githubusercontent.com/14237/176053933-3d2ee10c-4cf6-4f04-bb7f-03b980324999.png)

**Comment by defunctzombie** [comment]
When I try loading this same file in the non-experimental player I see this warning:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/84792/176573404-11470d1f-e732-4228-9e40-443650a45731.png">

It also thinks the file is un-indexed.

Here is how we are identifying indexed files right now:

https://github.com/foxglove/studio/blob/main/packages/studio-base/src/players/IterablePlayer/Mcap/McapIterableSource.ts#L25

Is there something wrong with this logic? I copied it from the non-experimental player.

**Comment by jtbandes** [comment]
Yeah, probably both are wrong. I guess they don't account for _empty_ files as a special case.

**Comment by defunctzombie** [comment]
I can make a fix here if you think there is a fix we should make? Should we add logic to detect what we think to be an empty file? Or do we keep the existing error message?
