### ISSUE TITLE
Misleading/meaningless message frequency shown for small mcap file

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3732]
Drop the following files into the app:

[array_of_bytes.mcap.zip](https://github.com/foxglove/studio/files/8996447/array_of_bytes.mcap.zip)

[array_of_bytes_unindexed.mcap.zip](https://github.com/foxglove/studio/files/8996448/array_of_bytes_unindexed.mcap.zip)

The indexed file shows a meaningless large number for the message frequency:
![Screen Shot 2022-06-27 at 5 00 21 PM](https://user-images.githubusercontent.com/14237/176059259-eec2c092-3d31-47f8-bf75-202535e42d8e.png)

The unindexed file shows "Infinity Hz" with the non-experimental player (and is not supported with the experimental player):
![Screen Shot 2022-06-27 at 5 01 26 PM](https://user-images.githubusercontent.com/14237/176059253-f5932b46-0e1f-4ddd-9c9d-fec5cbafbb02.png)

**Comment by foxymiles** [comment]
What do you think we should do in the first case?

**Comment by jtbandes** [comment]
We shouldn't show a frequency if we can't compute one, so either show "–" or just show nothing

**Comment by foxymiles** [comment]
In the first case we do have a message count and a timespan it just results in a crazy value since the timespan is so short. 

In the second case showing a dash seems like a good solution.

**Comment by jtbandes** [comment]
Not sure what you mean – the two cases are the same (just indexed vs unindexed). Both of them contain a single message so the time range is zero. That shouldn't result in a random integer being shown for the rate – Infinity makes more sense mathematically since the denominator is zero, but I think it would be better to show a dash than Infinity.

**Comment by foxymiles** [comment]
In the first case the message pipeline is calculating a non-zero time. Maybe that's the logic we need to fix?
