### ISSUE TITLE
Cant access begining of path if very long path exists in plot

### ISSUE THREAD

**Issue by clementchef** [foxglove/studio#3743]
**Description**
Small UI glitch. Can go further left than this in this long topic path  (diagnostics one). Im trying to go at the beginning to add /old/ but I cant.
![image](https://user-images.githubusercontent.com/66749666/176244714-3034c221-36d2-4e03-81f4-97dc566fddaa.png)

Path was `/diagnostics.status[:]{hardware_id=="none"}{name=="m01/conveyor_speed_node: Overall health"}.values[:]{key=="Elaspsed (s): conveyor_speed_estimation"}.value`

- Version:1.13.2
- OS:ubuntu
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by foxymiles** [comment]
@clementchef Do you mean that using the arrow keys you're not able to navigate to the beginning of the path and make edits? Is it possible for you to try a more recent version of the app? So far I'm not able to reproduce this in 1.16.0.

**Comment by defunctzombie** [comment]
👍 Thanks - yea even using the arrow keys doesn't work. The input did not scroll over to follow the cursor.

**Comment by foxymiles** [comment]
@clementchef Working on a fix now. Looks like as a workaround you can manually scroll the input using the scrollbar at the bottom.

**Comment by foxymiles** [comment]
Looking into this more I think the problem is that the input itself is a scroll container and the legend is a scroll container and at least on linux navigating the inner scroll container doesn't quite force the outer container to scroll. I'm still looking for a fix.
