### ISSUE TITLE
Will 3D-Grid be imported to 3d-pannel in the future?

### ISSUE THREAD

**Issue by AndyYangjd** [foxglove/studio#3757]
I want to have a 3d grid box which can set the inverval and length.

Below is the photo from [varyar](https://www.vayyar.com.cn/technology.html)
![image](https://user-images.githubusercontent.com/44262434/176568533-567484ff-dd0a-485a-ae76-7518c6e206e8.png)

**Comment by defunctzombie** [comment]
The 3d panel supports [cube markers](https://foxglove.dev/docs/studio/panels/3d#marker). These markers can have any color and opacity you want so you can already accomplish this today.

**Comment by AndyYangjd** [comment]
I means whether the default grid in 3d-pannel can be extended to three dimension. Also, the new 3d-grid have the some config to  current 2d-grid.
