### ISSUE TITLE
Studio crashes when opening the Diagnostics panel

### ISSUE THREAD

**Issue by IonyM-BWR** [foxglove/studio#3785]
**Description**
When connecting to live connection or bag (ROS1) Studio crashes when adding a Diagnostics panel.

The app displays the message
"Cannot read properties of undefined (reading 'length')"

- Version: 1.16.0
- OS: Ubuntu 20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS1 native (python node) , bag (ROS1)
- ROS distro (if applicable): noetic

**Steps To Reproduce**
dummy diagnostics publishing node:

```python
#!/usr/bin/env python
"""Example Python node to publish on a specific topic."""

import rospy
from diagnostic_msgs.msg import DiagnosticStatus, KeyValue


class Diagnosticator(object):
    """Node example class."""

    def __init__(self):
        self.rate = rospy.Rate(10)

        self.publisher = rospy.Publisher("/diagnostics", DiagnosticStatus, queue_size=10)

    def _publish(self):
        _diagnostic_msg = DiagnosticStatus(
            level=DiagnosticStatus.OK,
            name='diagnostic message',
            message='diagnostic message',
            values=[KeyValue()]
        )

        self.publisher.publish(_diagnostic_msg)

    def update_step(self):
        self._publish()
        self.rate.sleep()

if __name__ == '__main__':
    rospy.init_node("diagnostic_test")
    diagnosticator = Diagnosticator()

    while not rospy.is_shutdown():
        diagnosticator.update_step()
````

Crashed app final view:
![image](https://user-images.githubusercontent.com/63537843/177812612-81a7afb9-510d-4a86-b3c8-f581956ede10.png)

**Expected Behavior**
To display the Diagnostics panel and to be able to select the relevant topic

**Actual Behavior**
Crash: "The app encountered an unexpected error"

**Comment by foxymiles** [comment]
@IonyM-BWR Can you please click on the "show details" button there and share what extra information about the error is revealed?
