### ISSUE TITLE
New layout deleted on internet reconnection

### ISSUE THREAD

**Issue by bertaveira** [foxglove/studio#3810]
**Description**
I was connected to a network without internet. I created a new layout in my local foxglove app. Proceeded to edit is a lot. At the end of the day when I got back to a network with wifi I opened foxglove and it showed a message saying something similar to "The layout was deleted" and the new layout I had made was no longer opened or present in my system.

Seems like since I had no internet it did not get uploaded to my account and then when I got back to a wifi with internet it proceeded to overwrite it. And then I got the warning message on open since it was trying to open the last layout but it was not present since it got deleted by the synchronisation with the account layouts.

- Version: 1.17
- OS: MacOS

**Comment by jtbandes** [comment]
I've been able to reproduce this with the desktop app by toggling offline mode via the Network settings. Will investigate.
