### ISSUE TITLE
[New3D] Support new foxglove.FrameTransform message

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3850]
FrameTransform was modified to include direct `translation` and `rotation` fields: https://github.com/foxglove/schemas/pull/46

We need to update 3D panel to support this. It should be done in a backwards compatible way (i.e. still supporting a nested `transform` field if one exists).

@defunctzombie questions:
- Does Old3D need to support the new FrameTransform fields?
- Is it sufficient for New3D to only support the new fields, or do we need backwards compatibility in New3D as well?

**Comment by defunctzombie** [comment]
> * Does Old3D need to support the new FrameTransform fields?

Yes. We have users who produce protobuf data and want to use our app. Now that this schema breaking change merged we need to support it in Old3d and New3d. If we had waited until we were further along in old3d cycle then we could avoid doing that.

> * Is it sufficient for New3D to only support the new fields, or do we need backwards compatibility in New3D as well?

We need backwards compatibility in new3d. Our current docs still reference the old format and people will have data in the old format. We do not break the display of your data.

IMO this change to the schemas was rushed. There is no real problem it solves other than for us to now be in a weird state where repo is out of sync with docs and what studio supports. It's already a lift to bring your data into studio and this adds more confusion to doing so.
