### ISSUE TITLE
Make the sidebar easier/quicker to close

### ISSUE THREAD

**Issue by DavidXenakis** [foxglove/studio#3873]
**Description**
The only way to close the sidebar is to click on the sidebar tab you're currently on. This is especially frustrating when it is accidentally opened, say, by fat-fingering the kebab icon next to the panel settings icon in panel headers. Having a quicker, more natural way to close the sidebar would streamline my usage of Studio.

- Version: Latest
- OS: Any
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Any
- ROS distro (if applicable): Any

**Steps To Reproduce**
See description.

**Current Experience**
See description.

**Desired Experience**
Proposed ideas, non-exclusive:

- Create a keyboard shortcut, e.g. 'esc' or 'ctrl-b', to close the sidebar. This could be the default keybinding to close any sort of menu within the application.
- When clicking on the panel settings icon in the panel header, the settings menu opens up. Clicking on the same settings button again should close the sidebar. With the sidebar open, clicking on a different panel's settings icon would open up the settings for that panel.

**Comment by amacneil** [comment]
Referencing my prior suggestion of `Ctrl-B` in https://github.com/foxglove/studio/issues/1717
