### ISSUE TITLE
"Reset to defaults" is broken for extension panels

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3890]
**Description**

Settings "reset to defaults" doesn't do anything for extension panels such as `3D (Beta)`. The panel shouldn't have any say in this - would be better if we completely unmounted and recreated the panel, to completely flush all state.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/637671/180088752-a913287c-96a0-4c52-87b4-5743b2ad0ede.png">

**Comment by jhurliman** [comment]
To clarification for whoever tackles this bug, Reset to defaults does correctly clear the config for the panel and persist the empty `{}` config object. But the panel is never unmounted/remounted or notified of this, so you don't see the change until the app is reloaded.

I agree that force remounting is a better generic solution for extension panels than firing an event and hoping the panel correctly handles every edge case.
