### ISSUE TITLE
Add ros2/rcl_interfaces to bundled messages

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3901]
[ros2/rcl_interfaces](https://github.com/ros2/rcl_interfaces) contains some common message definitions, e.g. as used by Turtlebot.

We should bundle these message definitions with Foxglove Studio (like we do for [ros2/common_interfaces](https://github.com/ros2/common_interfaces)), so that they work with db3 files and native ROS 2 connections.

**Comment by amacneil** [comment]
Related / possible duplicate of https://github.com/foxglove/rosmsg-msgs-common/issues/2

**Comment by jhurliman** [comment]
https://github.com/foxglove/rosmsg-msgs-common/pull/9
