### ISSUE TITLE
Self-hosting doesn't work with Chrome

### ISSUE THREAD

**Issue by suho0515** [foxglove/studio#3907]
**Description**

Hello, I'm trying to run basic container following the manual like below.

`docker run --rm -p "8080:8080" ghcr.io/foxglove/studio:latest`

but when I run the above command, I can only see white screen in chrome browser.

**Chrome**

![image](https://user-images.githubusercontent.com/20294721/180227956-0e6ebbaa-a89d-49e5-8726-8ba20de792b3.png)

But it works well in edge browser.

Microsoft Edge

![image](https://user-images.githubusercontent.com/20294721/180228130-ade31b1a-09a1-4433-b5b2-6b6829eaf1b9.png)

Do I need any preliminaries to work this out with chrome?

thanks.

- Version: 1.18
- OS: Window 10
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): None
- ROS distro (if applicable): None

**Comment by foxymiles** [comment]
@suho0515 Could you please open the dev console in chrome and refresh the page and see if there are any errors displayed there?

**Comment by defunctzombie** [comment]
@suho0515 Were you able to look into this more using dev console in chrome?

**Comment by suho0515** [comment]
Sorry for late respose.
I was busy with other projects.

I've check it out, and result is below.

![image](https://user-images.githubusercontent.com/20294721/181871552-5fe96795-e81c-40c3-a5f3-0948f45f4ee2.png)

`<!doctype html><html><head><meta charset="utf-8"><link rel="apple-touch-icon" sizes="180x180" href="[apple-touch-icon.png](http://localhost:8080/apple-touch-icon.png)"/><link rel="icon" type="image/png" sizes="32x32" href="[favicon-32x32.png](http://localhost:8080/favicon-32x32.png)"/><link rel="icon" type="image/png" sizes="16x16" href="[favicon-16x16.png](http://localhost:8080/favicon-16x16.png)"/><title>Foxglove Studio</title><script defer="defer" src="[main.06fdb4eaf19e1fec0d86.js](http://localhost:8080/main.06fdb4eaf19e1fec0d86.js)"></script></head><script>global = globalThis;</script><body><div id="root"></div></body></html>`

Hope to hear any evidence to solve it out.

Thanks again.

**Comment by defunctzombie** [comment]
Those are chrome extension errors and nothing specific to do with Studio.

It sounds to me like this is something specific to your environment/setup. Since Edge is working I'd recommend using Edge for now. Since Edge is based on Chrome/v8 you should be able to use all the features of Studio available in chrome.
