### ISSUE TITLE
Data platform experimental player preloads block data in 5 second bits rather than large spans

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3911]
**Description**
Performance for loading data for a plot (preloading) even with a lightweight topic is severely degraded by loading data in 5 second increments rather than one long request.

The experience is far worse than the existing player for preloading data because of this.

**Comment by amacneil** [comment]
For preloaded topics, can we just make a request for the entire time range? Presumably that could happen in parallel to requests for smaller time ranges of regular topics.
