### ISSUE TITLE
ROS Market text_view_facing

### ISSUE THREAD

**Issue by adrianfyh** [foxglove/studio#3923]
Hello ,

I just found the text_view_facing type Market could not be scaled in 3D panel.
No matter what number which i give to the the text market scale.z, the  size in 3D panel is always same.

Did anyone meet the same problem? How did you solve it?

Thank you very much.

**Comment by defunctzombie** [comment]
We do not support scaling text markers in the 3D panel. However 3D beta does support scaling markers. Please give 3D beta a try if you'd like to have your text markers scale.
