### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by tomy983** [foxglove/studio#3931]
**Description**
I am unable to publish to a remote robot. I verified the connection and followed the instructions  at http://wiki.ros.org/ROS/NetworkSetup and both computers can communicate using their hostname.
Reading at #3182 I also tried replace the ROS_HOSTNAME with the ip address, without success.
No errors are given in the problems tab.
**I can see the messages actually published in the Raw Messeges panel and also in the Data Source Panel** but it does not reach the remote machine where I am using rostopic echo to visualize incoming messages, so the data shown there is probably just "local" and not actually coming from ROS robot machine.

I can communicate to the same robot remotely using another pc with rviz and rqt and also an android app.

- Version: Studio 1.18.0 on Windows 11, ROS Noetic on Ubuntu 20.04

**Steps To Reproduce**
Successfully connect to remote robot (live connection, ROS1) using ROS_HOSTNAME actual hostname or IP address, publish a message or pose from 3D panel (also beta)

**Expected Behavior**
Message reach robot or error reported.

**Actual Behavior**
Message does not reach robot and is shown in Raw Messeges panel and Data Source Panel. No errors reported.

**Comment by defunctzombie** [comment]
@tomy983 Please try using the rosbridge connection option. It is much easier to get that setup and working correctly than the ROS1 native option which requires that all TCP ports are open between machines, that your Studio instance ROS_HOSTNAME is resolvable by the receiving robot, and that its hostname is resolvable by studio. If you still encounter problems I recommend jumping into our community Slack for more assistance. Unfortunately there's not enough in this bug report for us to reproduce the issue.
