### ISSUE TITLE
[3D Beta] Override marker colors

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3943]
In the current `3D` panel, I can override marker colors (both regular and mesh markers):

<img width="469" alt="image" src="https://user-images.githubusercontent.com/637671/180935011-57fdf8ef-2e34-48f2-ac2a-9dc6283e157d.png">

In `3D Beta`, this does not seem possible (no arrow to expand settings).

<img width="392" alt="image" src="https://user-images.githubusercontent.com/637671/180934893-c5402431-d2fe-40fe-9d23-7dea0301d030.png">

We should implement this for feature parity.

**Comment by defunctzombie** [comment]
Regarding the "form polygons" feature this screenshot shows - we've decided to leave it out of the GA and see if someone asks for it.

We still need the override marker colors. That was asked for by a user.
