### ISSUE TITLE
Arrow right auto play at low replay speed on bag

### ISSUE THREAD

**Issue by clementchef** [foxglove/studio#3980]
**Description**
Pressing the right arrow on keyboard triggers auto play (instead of just moving right).
This only happen at low replay speed (eg: 0.05x) on bag, when paused.

- Version:
- OS:
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment]
Confirming I can reproduce by selecting a slow speed and hitting the right arrow. Will look into this.
