### ISSUE TITLE
Plot: Option to set "x min" and "x max"

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3991]
Ability to set "x min" and "x max" in addition to "y min"m and "y max" (already supported).

This is important for consistent/comparable plots.

It could be added to the plot settings:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/637671/181682409-dc28c2e1-a94a-4311-83ec-9e191147ee3d.png">

Extracted from https://github.com/foxglove/studio/issues/3990 (@ljburtz fyi)

**Comment by foxymiles** [comment]
@amacneil Would these new settings also go under `Time series only`?

**Comment by amacneil** [comment]
I think we could create some new groups for `X axis` and `Y axis` (or google sheets calls them `Horizontal axis` and `Vertical axis`):

<img width="338" alt="image" src="https://user-images.githubusercontent.com/637671/182421649-50dd1126-ff1e-4b04-bcca-71ba3186fdf7.png">

**Comment by defunctzombie** [comment]
Might be nice to also hide settings if they are not relevant. It was harder to do this before but seems sensible now.
