### ISSUE TITLE
Replace momentjs

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#4035]
**Description**
Momentjs is now considered a legacy project. We should replace it with a better maintained library.

**Steps To Reproduce**
https://github.com/moment/moment-timezone/blob/develop/README.md

```
Moment-Timezone is an add-on for Moment.js. Both are considered legacy projects, now 
in maintenance mode. In most cases, you should choose a different library.
```

**Comment by jtbandes** [comment]
Moved to Linear
