### ISSUE TITLE
Timezone data not found in time formats

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#4036]
**Description**
momentjs timezone data seems to be unavailable to the app.

- Version: studio.foxglove.dev
- OS: mac/chrome
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): nuscenes

**Steps To Reproduce**
1. Change your timezone in the preferences panel to any specific timezone.
2. Load nuscenes.
3. Hover over the playback bar.

**Expected Behavior**
The timezone data should be found and used.

**Actual Behavior**
Console logs numerous errors like this:

```
Moment Timezone has no data for zone:Africa/Algiers.
```

**Comment by jtbandes** [comment]
```
e1850a9009a335056e5c0e43834a296f60c9235e is the first bad commit
commit e1850a9009a335056e5c0e43834a296f60c9235e
Author: Miles Egan <93935560+foxymiles@users.noreply.github.com>
Date:   Wed Aug 3 09:56:58 2022 -0600

    Remove fluent from preferences sidebar (#4026)
```
