### ISSUE TITLE
Remote file access without the actual file name and suffix

### ISSUE THREAD

**Issue by tgoelles** [foxglove/studio#4048]
I would like to access data which on a server, without the actual file name in the form of:

`https://example.com/api/access/datafile/40?gbrecs=true`

This is currently not possible since foxglove needs the file name and suffix. If I use the url from above in a browser the download immediately starts so it should be possible. I cloud also pass some more information to floxglove is needed.

I want to yous foxglove as a previewer for data in a data managment system (dataverse).

**Comment by tgoelles** [comment]
definitely related so the issue could be merged or closed

**Comment by foxymiles** [comment]
Closing in favor of #3992
