### ISSUE TITLE
Initial messages are sometimes skipped when looping with new player

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4057]
**Description**

I ran into this issue while troubleshooting another unrelated bug report. In the attached mcap, there are 101 evenly spaced (in time) `/tf` messages and 3 `/cubelist` messages at t=0.01, t=2, and t=4. While playing back with looping enabled, it seems like the initial message is often missed (my layout has one New3D panel and one Raw Message panel).

[filled-empty-filled.mcap.zip](https://github.com/foxglove/studio/files/9264872/filled-empty-filled.mcap.zip)

**Comment by defunctzombie** [comment]
The initial message on which topic? The `/cubelist` topic or `/tf` ?

**Comment by jhurliman** [comment]
@defunctzombie the initial topic on `/cubelist`. It is skipped in both raw messages and New3D so I don't think this is a panel issue, it appears to never come over the message pipeline.

**Comment by defunctzombie** [comment]
Confirming I see this behavior when looking. The initial playback is good but on loop the first message is missing.
