### ISSUE TITLE
onChange event fires twice with enter key in VisibilityToggle

### ISSUE THREAD

**Issue by DoParkEQ** [foxglove/studio#4065]
Hi, I was trying the application on my local machine and found a minor interaction bug. 

**Description**
There is a keyboard interaction bug from Material UI's Button component, which triggers the `onClick` event when `onKeyDown` event is fired by pressing `Enter` key. This bug is initially found from `VisibilityToggle`.

Version: v1.20.1
OS: macOS 11.4

**Steps To Reproduce**

![Screen Shot 2022-08-06 at 8 52 28 AM](https://user-images.githubusercontent.com/59836949/183256367-5a78e970-fc0d-495b-a452-967d43f21535.png)

1. Give focus on visibilityToggle
2. Press `Enter` key

**Expected Behavior**
Pressing enter key should change its visibility state. 

**Actual Behavior**
When `Enter` key is pressed, the onChange event fires twice therefore, the visibility state remains the same.

**Comment by jtbandes** [comment]
Thanks for the report. Would you be willing to create a PR to fix this issue?

This 3D panel is in maintenance mode, we would recommend you use the 3D (Beta) panel.

**Comment by DoParkEQ** [comment]
@jtbandes for sure! I am happy to contribute.
