### ISSUE TITLE
Load data from S3 compatible storage

### ISSUE THREAD

**Issue by dbruggner** [foxglove/studio#4076]
In addition to loading data from a http URL it would be helpful if Foxglove Studio would also support loading data from a S3 compatible storage.

**Comment by defunctzombie** [comment]
We already support loading data from s3 like object storage. You likely need to setup your storage correctly:
https://foxglove.dev/docs/studio/connection/remote-file#setting-up-cors-for-a-remote-file

Alternatively, you can avoid manually setting up and managing storage if you use the data platform product which will simplify this process. That product offers storage options in our cloud or your cloud account.
