### ISSUE TITLE
Extension in container does not work.

### ISSUE THREAD

**Issue by suho0515** [foxglove/studio#4078]
**Description**
Hello team,
Recently, I'm working on creating custom panel in foxglove-studio container.
I tried simple tutorial as below pages.

- https://foxglove.dev/docs/studio/extensions/getting-started
- https://github.com/foxglove/create-foxglove-extension

I had install and build process inside the container made from "[ghcr.io/foxglove/studio:latest](http://ghcr.io/foxglove/studio:latest)" image.
![image](https://user-images.githubusercontent.com/20294721/183679616-421773a9-0152-4dfe-adf9-fd8f75e7ae84.png)

And I commit the container to another image(I'll call it modified image).
after that, I made container with modified image.

But when I checked the extension menu, I can not find any custom panel I built.
![image](https://user-images.githubusercontent.com/20294721/183679930-761a497b-0f2b-46f4-9e42-8892bd298713.png)

Is there any missing process of it? or custom panel can not be used in container?

- Version: 1.20
- OS: Container Environment
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): none
- ROS distro (if applicable): none

**Comment by defunctzombie** [comment]
Extensions are not packaged into the studio app (or container). Extensions are installed via drag-and-drop, double click (if the desktop app is installed), or via your foxglove account automatic org provisioning (https://foxglove.dev/blog/announcing-private-foxglove-studio-extensions-for-your-organization)
