### ISSUE TITLE
migrate panels/log List to MUI

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#4079]
Convert the log panel List to MUI.

Whomever tackles this make sure to test this behavior so we do not regress!
https://github.com/foxglove/studio/issues/2652

**Comment by 2metres** [comment]
Closed by #4094

**Comment by defunctzombie** [comment]
@2metres Is this done? What I've understood from discussion is that we've only partially ported panels/log to MUI. Is there another ticket tracking the remaining work?

**Comment by foxymiles** [comment]
This is the PR that converted the Log panel to fluent: https://github.com/foxglove/studio/pull/2654
