### ISSUE TITLE
Markers of PointsAnnotationType don't show up in ImagePanel

### ISSUE THREAD

**Issue by gayar-helm** [foxglove/studio#4080]
I'm using User Script functionality to generate markers and add them on top of the camera image in Image Panel.
Here is the code to generate a horizontal line of dots in the middle of the frame:

```
import { Input, Message} from "./types";
type Output = Message<"foxglove_msgs/ImageAnnotations">;
type PointsAnnotationMsgType = Message<"foxglove_msgs/PointsAnnotation">;
	
export const inputs = ["/device_0/sensor_1/Color_0/image/data"];
export const output = "/studio_script/point_annotations";  

export default function node(event: Input<"/device_0/sensor_1/Color_0/image/data">): Output {
  const out = {} as Output
  out.points = new Array;
  const line_points = {} as PointsAnnotationMsgType;
  line_points.points = new Array;
  line_points.outline_colors = new Array;
  let x0: number = 0;
  let x1: number = 1920;
  let y0: number = 500;
  let step: number = 10;
  let i: number = 0; 
  while (x0 + i*step <= x1) {
    let xi:number = i*step;
    line_points.points.push({x: xi, y:y0});
    line_points.outline_colors.push({r:1, g:1, b:1, a:1});
    i++;
  }
  line_points.type = 0;
  line_points.timestamp = event.message.header.stamp;
  out.points.push(line_points);
  return out;
};

```

- Version: Foxglove Studio version 1.21.0-dev
- OS: macOS 11.6.2
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS1 bag from [here](https://librealsense.intel.com/rs-tests/TestData/stairs.bag).
- ROS distro (if applicable): N/A, Foxglove Studio runs in Chrome v. 103.0.5060.114

**Steps To Reproduce**

**Expected Behavior**
When type is set to `0` like this ` line_points.type = 0;` we get expected picture:
![image](https://user-images.githubusercontent.com/83242562/183777647-591f60ff-88cf-44fa-9bea-a1548f130e80.png)

**Actual Behavior**
When point type is anything from this [enum](https://foxglove.dev/docs/studio/messages/points-annotation-type) but `0`, nothing appears on the image:
![image](https://user-images.githubusercontent.com/83242562/183778193-cf34bc30-bbd1-4ed3-94fa-d50dc6a6ed38.png)

**Comment by jtbandes** [comment]
Thanks for the report. This seems like a few issues in one. The panel silently displays nothing if there is an odd number of points and the type is `LINE_LIST`. Also, there is a mismatch between the documentation and the app's behavior for `LINE_STRIP` – specifically the `outline_color` and `thickness` properties are required but undocumented.
