### ISSUE TITLE
[3d beta] Option to override opacity and/or color for markers

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4089]
My file (nuscenes example) has opacity set in the markers. I am trying to view the file and decided I don't like the opacity that the message author selected, so I would like to override the opacity. I think it would also be nice to override the colors. 

Personally I would prefer to do this for all namespaces in the marker topic, but I would settle for having it configurable per-namespace if that is easier from a settings UI perspective. 

The old 3D panel allowed overriding colors (but not opacity), so this is a partial regression in functionality.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/637671/183809646-92716e14-b055-429e-a9c9-45305d5d6696.png">

**Comment by jtbandes** [comment]
Duplicate of https://github.com/foxglove/studio/issues/3943? Or are these both halves of the same issue?

**Comment by amacneil** [comment]
Oh yeah I guess I already complained about this :)

I do think it could be useful to override opacity only (rather than both color+opacity), for marker topics that already have colors (like our nuscenes demo). But I will close this and hold my judgement until after https://github.com/foxglove/studio/pull/4054 lands.
