### ISSUE TITLE
Layout sync failure / "offline" icon

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4101]
**Description**
Not sure why I am in this state or how to fix it.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/637671/184021409-1d0d1832-f036-4fb8-a57e-4658c27b2f2c.png">

I was getting 409 Conflict.

Clearing indexeddb solved it.

**Comment by foxymiles** [comment]
Note: this happened when switching between different orgs on data platform.

**Comment by amacneil** [comment]
I'll keep this issue around for a little while and see if I can repro it. If not, will need to close it until we can find clear repro steps.

**Comment by amacneil** [comment]
Closing this and I will reopen if I can repro.
