### ISSUE TITLE
Remove un-actionable topic count from 3d (beta) sidebar.

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4147]
**Description**

The 3d beta panel shows me some topic count in the settings and I have no idea what I am suppose to do with this information.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/84792/184977518-bf63ffd9-8550-4408-8d72-b79234785d6e.png">

**Comment by snosenzo** [comment]
Couldn't this be helpful for giving a user context as to whether they have topics that they want to see but might not realize are off?

**Comment by defunctzombie** [comment]
> Couldn't this be helpful for giving a user context as to whether they have topics that they want to see but might not realize are off?

Those topics would show up in the topics section with a "closed eye" icon on them. From what I can tell the `0/7` in my data tells me that out of 7 total topics in my data, the panel is able to show me 0 of them. Not really that useful since I can already see what topics the panel supports because they would show up in the topics list.
