### ISSUE TITLE
Help Button in Data Source Panel links to 404

### ISSUE THREAD

**Issue by snosenzo** [foxglove/studio#4168]
**Description**
Help Button in Data Source Panel links to 404
https://foxglove.dev/docs/studio/app-concepts/data-sources

- Version:
- OS: web/macos
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): n/a
- ROS distro (if applicable): n/a

**Steps To Reproduce**

 - explore sample data
 - open data source panel
 - click help button in top right of panel

**Expected Behavior**
 - maybe link to this page? https://foxglove.dev/docs/studio/panels/data-source-info

**Actual Behavior**
 - links to this page and it's a 404: https://foxglove.dev/docs/studio/app-concepts/data-sources

**Comment by amacneil** [comment]
This was the intended destination: https://foxglove.dev/docs/studio/connection/data-sources

@esthersweon can you add a redirect on the website repo too
