### ISSUE TITLE
Avatar icon becomes tiny in narrow sidebars

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4194]
**Description**
When I open the "Account settings" sidebar and it happens to open narrow (cause my window is smaller), the icon also shrinks.

![image](https://user-images.githubusercontent.com/84792/185507138-7ab96cd0-54ae-4807-9ada-a2bc9eb60ce6.png)

It seems reasonable that the icon stays the same size and maybe the text goes under it?

**Comment by james-rms** [comment]
😍 so tiny!
