### ISSUE TITLE
Add BirdEyeView support

### ISSUE THREAD

**Issue by jiyongfeng** [foxglove/studio#4200]
today， BEV（BirdEyeView）become more and more important in Automotive dev.

I suggest that studio can support BEV panel to support such as object / Lane to view.

**Comment by amacneil** [comment]
BEV is already supported, just click the `3D` button in the 3D panel to switch into 2D mode:

<img width="1104" alt="Screen Shot 2022-08-19 at 10 17 59 AM" src="https://user-images.githubusercontent.com/637671/185673335-d250d456-5e31-43fc-8b5a-2344e0da3a53.png">
