### ISSUE TITLE
migrate components/StudioToastProvider to MUI

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4206]

**Comment by 2metres** [comment]
Looked into this one today. The removal of @fluentui/react here is fairly straighforward, however [`react-toast-notifications`](https://www.npmjs.com/package/react-toast-notifications) the library we use for toasts is no longer maintained. 

MUI reccomends using a package called [`notistack`](https://github.com/iamhosseindhv/notistack) and we use [`react-hot-toast`](https://www.npmjs.com/package/react-hot-toast) for console should we consider a bit of an uplift here while we're making these changes?
