### ISSUE TITLE
"Data went back in time" problem appears while scrubbing

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#4222]
Foxglove Studio 1.22.0

If I scrub rapidly back and forth through a ROS1 bag file, a red (1) appears on the data source sidebar icon for a fraction of a second. The problem appears to be "data went back in time."

I think this may be related to which parts of the file have been loaded in, and maybe it appears when new data has to be read from disk? Not sure.

**Comment by defunctzombie** [comment]
Adding a bug label because I don't think this should be happening and might be an indicator the message pipeline is not clearing as expected.

If you can reproduce this reliably could you record a video of it happening?

**Comment by rgov** [comment]
https://user-images.githubusercontent.com/108767/185796292-b397f44a-8e29-4675-b12a-13817caef774.mov

**Comment by amacneil** [comment]
It’s not wrong… the data did go back in time 😄

I assume Latching setting is enabled?

**Comment by rgov** [comment]
I didn't know of this setting but it is enabled, although the issue seems to occur regardless of this setting.
