### ISSUE TITLE
Plot panel not resetting to correct range

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4224]
**Description**

When I open the following data source (Foxglove HQ access required)

https://studio.foxglove.dev/?ds=foxglove-data-platform&ds.deviceId=dev_Wm1gvryKJmREqnVT&ds.end=2022-08-22T00%3A02%3A14.251000000Z&ds.start=2022-08-21T23%3A41%3A31.514000000Z&layoutId=8ffa0ab6-3662-4248-a57c-3ba944f4b2d4&time=2022-08-21T23%3A51%3A11.458000000Z

I am able to plot this data using the following plot panel. However, the data shown is not the entire range.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/84792/185817491-078449ca-96c8-42f9-8619-0c513b09a3e4.png">

I can manually zoom out to see the entire range, but when I click "reset view" I am again shown a smaller range.

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/84792/185817508-eb7e40ca-cc05-41f8-8e7c-9a7d1de7931d.png">

**Comment by foxymiles** [comment]
I think this may be fixed in https://github.com/foxglove/studio/pull/4145

**Comment by defunctzombie** [comment]
I had a range of 10 seconds set on my plot panel so this was indeed showing me 10 seconds. 🤦
