### ISSUE TITLE
Plot with auto x range is very narrow

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#4251]
- Version: 1.23.0
- OS: macOS
- Data source: ROS1 bag
- ROS distro: Melodic

I am using `rosbag record` with a split option that produces an hourly file. The system runs for a long time, potentially for weeks. When I load one of these slices, a Plot panel that plots a value vs `header.stamp` with auto *x* range looks like this, with all the data squeezed to the right:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/108767/186462095-7e47432e-519a-4c96-9d77-6037b3027d8d.png">

I assume it's setting the minimum *x* limit to the entire lifetime of the ROS master, and not to just what this bag contains. Is there a better solution?

(Bad title, sorry, feel free to edit.)

**Comment by foxymiles** [comment]
@rgov Can you please check and see if you get the same behavior with this branch? https://github.com/foxglove/studio/pull/4145

**Comment by rgov** [comment]
@defunctzombie checked for me and said it looks better :+1:
