### ISSUE TITLE
3D Beta: Adding Grid or URDF layers makes all other topics disappear

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4267]
**Description**
1. Open bag file with 3D beta panel
2. Add Grid or URDF layer
3. All topics disappear from the settings

<img width="429" alt="image" src="https://user-images.githubusercontent.com/637671/186527842-75a3cb59-c6b5-4472-a9d2-da7463b34067.png">

**Comment by tmp-username** [comment]
I have the same situation, is there any other way to import the urdf model?  I really want to display a car model in my 3d(beta) panel now

**Comment by snosenzo** [comment]
there's a PR out for this now, but as a workaround if you show/hide all topics from the `...` menu in the topics row they should reappear
