### ISSUE TITLE
Inconsistent `:` menus

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4268]
**Description**
Roman would like the `:` menu to always appear on the right. 

Order should be `<eyeball><error><dotdotdot>`

<img width="400" alt="image" src="https://user-images.githubusercontent.com/637671/186528163-440c7cda-897a-4069-a11a-2a3204c93966.png">

**Comment by defunctzombie** [comment]
We need stories for these different states - also showing more than one item so we can catch issues like this. Elevating to a bug because this is not the intended behavior of the context menu placement.

**Comment by foxymiles** [comment]
What should we do if we have two adjacent nodes, both with an error but only one with a context menu? The error indicators will be out of alignment.

**Comment by defunctzombie** [comment]
Related question - if a nested node has an error, does the parent also show an error in the collapsed state?

**Comment by foxymiles** [comment]
> Related question - if a nested node has an error, does the parent also show an error in the collapsed state?

Currently this is the responsibility of the panel author because I haven't figured out a way to implement this generally that wouldn't compromise performance. Maybe there's a pure CSS solution.
