### ISSUE TITLE
Missing end time and duration

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4269]
Steps to reproduce:
- visit studio.foxglove.dev
- load example data

<img width="437" alt="image" src="https://user-images.githubusercontent.com/14237/186530899-f2e71aaf-c7f5-4a99-b156-8e25faee3e77.png">

**Comment by defunctzombie** [comment]
@jtbandes do you happen to know when this regressed? This seems recent.

**Comment by jtbandes** [comment]
I don't know. I didn't notice it until today, but I noticed styling issues (#4130) a little while ago (maybe unrelated?)

As a quick way to check old builds, I usually go back to random PRs from a few days/weeks ago and look at the vercel preview builds.
