### ISSUE TITLE
New 3d Panel: Settings tree jumps on node visiblity toggle

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#4279]
**Description**
When toggling camera visiblity the Settings Sidebar jumps

- Version: Studio website
- OS: MacOS Chrome
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Example Data
- ROS distro (if applicable):

**Steps To Reproduce**

Expand transforms and topics then toggle camera visibility

https://user-images.githubusercontent.com/924528/186796955-22c7ed7a-6b37-4cf8-b88f-93dd4f5c34ae.mp4

**Comment by osaro-imohe** [comment]
Can I have a video file? I don't have enough data to reproduce this.

<img width="423" alt="Screen Shot 2022-09-03 at 1 03 02 AM" src="https://user-images.githubusercontent.com/44953690/188247832-b482cc0d-78a6-4371-857a-3cd6865eaf31.png">

**Comment by osaro-imohe** [comment]
I can't reproduce this. It's working fine for me.

**Comment by snosenzo** [comment]
I wasn't able to reproduce this on my macbook pro display, only on my I was only able to reproduce on my external display. Maybe it has to do with screen size somehow? @foxymiles any ideas?

**Comment by foxymiles** [comment]
I was able to reproduce it but only sporadically after actively clicking a lot of stuff on and off. Maybe something to do with the debounced update to the panel config?

**Comment by defunctzombie** [comment]
I've not been able to reproduce this. @2metres are you still able to reproduce this still?

**Comment by defunctzombie** [comment]
Haven't heard back. Closing.
