### ISSUE TITLE
New3d: Unsetting decay time does not work

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4284]
**Description**

* Open a data set with point cloud data and enable the point cloud topic.
* Turn the decay time up to some number of seconds
* Play the data and let points accumulate
* Edit the decay time back to 0

Notice that the decay time does not reset to 0 and we are still seeing accumulated points. I would expect to no longer be accumulating points during playback.

**Comment by snosenzo** [comment]
I'm not able to recreate this on studio.foxglove.dev with the example data. is there example data file you saw this with?

**Comment by defunctzombie** [comment]
I used the sample data - a local copy of it but it is the same as we currently provide in "explore sample data".

https://user-images.githubusercontent.com/84792/187033970-f6afde78-7e7c-4173-b55a-8ba78d91375f.mov
