### ISSUE TITLE
Convert globalBounds to use Time instead of numbers for min/max

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#4314]
**Description**
Now that globalBounds is available in the timeline interaction store and usable by other parts of the app, we should express the min/max in Time values instead of seconds.

https://github.com/foxglove/studio/blob/563fca8dd580523001f152c844158a248df89ea7/packages/studio-base/src/context/TimelineInteractionStateContext.tsx#L21

**Comment by jtbandes** [comment]
Moved to Linear
