### ISSUE TITLE
3D Beta support for Foxglove image types

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4323]
Add support for RawImage, CompressedImage, and CameraCalibration.
~Blocked on https://github.com/foxglove/schemas/issues/59~

**Comment by defunctzombie** [comment]
What's our plan for tying CameraCalibration to the Image messages? In ROS the typical pattern is sibling topics? Will we support and document the same? Is there another pattern that is useful to support and would we need any other fields in the messages to support such a pattern?

**Comment by jtbandes** [comment]
The easiest solution would be to provide a setting in the sidebar so the user can choose the associated topic.
