### ISSUE TITLE
Blank 3D image panel when clock times are out of sync

### ISSUE THREAD

**Issue by camchambers** [foxglove/studio#4339]
**Description**
The 3D image panel in Foxglove Studio blanks when Foxglove Studio is hosted on a robot and a client's clock time is less than the robot's clock time.

Client time and robot time are in sync: 
<img src="https://user-images.githubusercontent.com/26011644/187985413-81639be1-2a42-442e-9f5d-15dc199a8da2.png" width="400"/> 

Client time is less than the robot's time: 
<img src="https://user-images.githubusercontent.com/26011644/187985774-f23f4303-46e4-4f1d-995a-0aebd0594eac.png" width="400" />

- Version: v1.24.0
- OS: Linux 5.14.0-1050-oem 
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS1

- ROS distro (if applicable): Ubuntu

**Steps To Reproduce**
Run Foxglove Studio on a robot and set your computer's clock back a minute. 

**Expected Behavior**
The 3D image panel renders data appropriately. 

**Actual Behavior**
The 3D image panel renders a blank screen.

**Comment by defunctzombie** [comment]
@camchambers Can you please try the same using the `3D (Beta)` panel. We are moving towards deprecating the `3d` panel in favor of the `3D (Beta)` and can look at this issue if it is still impacting the `3D (beta)` panel.

**Comment by camchambers** [comment]
Looks like this isn't an issue for the 3D  (beta) panel.
