### ISSUE TITLE
Inconsistent time formatting of start & end times

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4341]
When viewing this file: [arrows.mcap.zip](https://github.com/foxglove/studio/files/9473795/arrows.mcap.zip)

The sidebar shows the start time in seconds, but the end time as a date:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/14237/188025252-8037ad57-d6e0-455c-930f-80b92290e3a2.png">

Expected behavior: both should be shown as seconds, because the file was produced using 0-based time and the total duration is <1 min.

Related: #4130

**Comment by osaro-imohe** [comment]
@jtbandes Can I get this?

**Comment by osaro-imohe** [comment]
Also, can I get some help setting up Foxglove Studio. I'm running into a generic network error when I try to run Fox Glove Studio web. It seems can't find some UI fonts.  

<img width="1440" alt="Screen Shot 2022-09-02 at 1 43 53 AM" src="https://user-images.githubusercontent.com/44953690/188035766-9a43dc6e-205d-4e21-b77e-79f04f2b8f4e.png">

**Comment by foxymiles** [comment]
Closed by https://github.com/foxglove/studio/pull/4346
