### ISSUE TITLE
Scaling one synced plot resets manually adjusted Y axis of other synced plots

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#4351]
**Description**
Plot syncing and y axis scale do not behave as expected.

- Version: studio.foxglove.dev
- OS: any
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): nuscenes
- ROS distro (if applicable): -

**Steps To Reproduce**
1. Open nuscenes.
2. Create a new layout with two plots.
3. Manually adjust the vertical scale of one plot by holding down the V key and zooming.
4. Zoom the other plot.

https://user-images.githubusercontent.com/93935560/188710183-782746d3-afee-4cd9-b155-71b92e299f7f.mov

**Expected Behavior**
1. The manually adjusted Y scale should not be overridden.

**Actual Behavior**
Both the X and Y axis of the manually zoomed plot are controlled by zooming in the other plot.

**Comment by defunctzombie** [comment]
@foxymiles Were are we with this issue? Are you still looking at it?

**Comment by foxymiles** [comment]
Yeah I have a fix that seems to work. I've been trying to find something a bit more elegant but I can put up a PR with what I have if you want to take a look.
