### ISSUE TITLE
Previous GeoJson data is not cleared from Map panel after new dynamic GeoJson message

### ISSUE THREAD

**Issue by felixf4xu** [foxglove/studio#4360]
**Description**
I'm sending out dynamic GeoJson data message (https://foxglove.dev/docs/studio/messages/geo-json, protobuf version) to Map panel, the content of the GeoJson is dynamic ( dynamic LineString) and changing over time.

- Version: 1.24
- OS: Windows
- Data source (): websocket server

**Expected Behavior**
When new content of GeoJson is received, the old GeoJson lines/points should be cleared.

**Actual Behavior**

Old GeoJson lines/points are not cleard.

But if I zoom in/out the map panel, or drag the panel, or switch from fullscreen, the old GeoJson data will be cleared. 

It seems to me that the map panel is not refreshed on new GeoJson message and so the old data is not cleared.

**Comment by foxymiles** [comment]
Is it possible for you to provide a minimal bag or mcap file that demonstrates the issue?
