### ISSUE TITLE
Plot panel settings series sidebar should save input when I click away

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4368]
Believe it or not, this is in edit mode:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/637671/188990011-b2170ee4-105f-4fce-8b99-45ea5258f4e3.png">

When I click away, it should save the value. Ideally it would look and work consistently with renaming layouts.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/637671/188990164-7560a2e4-8731-452f-b7c7-0cf90787399c.png">

**Comment by foxymiles** [comment]
A clarification: the value is being saved on every keystroke. The issue is that it's not leaving the editing state on blur.

**Comment by defunctzombie** [comment]
> A clarification: the value is being saved on every keystroke. The issue is that it's not leaving the editing state on blur.

Should we save on every keystroke or go into an edit mode that you can "esc" out of to undo?

**Comment by foxymiles** [comment]
> Should we save on every keystroke or go into an edit mode that you can "esc" out of to undo?

Not sure which is better from UX point of view but in general all settings updates are immediate currently. We can certainly handle this differently of course.

**Comment by amacneil** [comment]
If we save on every keystroke then why do we need the checkbox thing at all?

I don't particularly care whether we save on every keystroke or not (seems like an implementation detail), but I agree with Roman that it would be nice to hit Esc to cancel/revert the changes.

**Comment by foxymiles** [comment]
Currently the purpose of the checkbox is to exit edit mode. I agree it's probably a bit confusing and suggests that your changes aren't saved until you click it.

**Comment by defunctzombie** [comment]
A) If we go the immediate save route then lets remove the checkbox since that to me is something I see when I need to confirm my changes not when they've already been saved.

B) If we go the route of matching layout rename workflow then we should avoid saving until the change is accepted so the user can 'esc' to cancel the change.

I am 👍 on us going with A for now since it is visually the least disruptive to the existing workflow and we can explore B as an enhancement pending more feedback.

**Comment by foxymiles** [comment]
If we go with A then how should the user exit edit mode? Only on enter?

**Comment by defunctzombie** [comment]
Played with this feature some more and I think my only real complaint is that it should exit edit mode of "blur" or loss of focus on the input. If it did that I think it would behave mostly as expected.

**Comment by foxymiles** [comment]
@defunctzombie It should be exiting edit mode on blur in that PR. Was that not working for you?

**Comment by defunctzombie** [comment]
@foxymiles I had tried on main - didn't notice the PR. I tried the PR 👍 :shipit:
