### ISSUE TITLE
3d (beta) panel goes blank when split

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4373]
**Description**

Splitting the 3d (beta) panel causes the panel to go blank.

https://user-images.githubusercontent.com/84792/189009801-396a0ea6-3e0a-4b6d-9e77-e64bc61dd247.mov

**Comment by jtbandes** [comment]
Guessing this is related to https://github.com/foxglove/studio/pull/3636 – we currently reset panels when the `path.length` changes.

**Comment by defunctzombie** [comment]
Agreed. Demoting this to a ux issue so we can remember this and close it out once we have tf preloading.

**Comment by defunctzombie** [comment]
Now that we have preloading I would have expected this to work better but when I split the panel I am still not seeing my topics even tho some of them should have loaded as the last latched topic. Do we think this _should_ work now?

**Comment by defunctzombie** [comment]
@jtbandes @jhurliman lets look into this now that tf preloading is merged. I suspect there is a problem with how the 3d panel is handling topic data when mounted? Or maybe a problem with how extension panels are provided data when they are remounted.

**Comment by defunctzombie** [comment]
I played around with this some more and there are behaviors that I would definitely put more in the bug category - certainly more surprising behavior than I'd think we would have with how we feed messages to panels:

- Working with an mcap file with a single topic `/LIDAR_TOP` still results in the 3d panel going blank when I split it. This behavior surprises me since there is only a single frame to display `LIDAR_TOP` and our player delivers the last message on any subscribed topic. So the 3d panel should have this last message.
- Using the same single topic mcap I can use the "select a point" feature to view the details of a point. There is a "popout" icon in the object selector which opens a raw message panel to view the message details. This results in the 3d panel going blank. Rather unpleasant since I wanted to view the message alongside the 3d view I was just looking at.

Understandably there are some scenes that may not properly reconstruct unless all the state is preserved, but with a single topic single frame data source I would expect the panel to be able to display the scene even through these various splits and changes. Marking this as a bug given this new information about the single frame case.

**Comment by defunctzombie** [comment]
John: maybe something in message pipeline?
Jacob: maybe we shouldn't be resetting the panel on splitting?
Roman: notably the raw message panel on split works as expected
