### ISSUE TITLE
Remove ThreeDimensionalViz imports from New3D panel

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4381]
The new 3D panel imports a couple of things from ThreeDimensionalViz:

https://github.com/foxglove/studio/blob/0c96c6644b18c091f8e5241bbd92d542068851be/packages/studio-base/src/panels/ThreeDeeRender/Interactions/InteractionContextMenu.tsx#L8

https://github.com/foxglove/studio/blob/0c96c6644b18c091f8e5241bbd92d542068851be/packages/studio-base/src/panels/ThreeDeeRender/Interactions/Interaction.stories.tsx#L18-L22

These need to be removed before we can remove the old 3d panel.

**Comment by snosenzo** [comment]
looks like there's a lot more imports outside of `ThreeDeeRender` -- do we want to remove these too?
<img width="543" alt="image" src="https://user-images.githubusercontent.com/10187776/189398290-16125a83-873e-46e7-bb3f-e59abaa6d4f3.png">

**Comment by jtbandes** [comment]
Yes, we will need to. It looks like the majority of those are TextMiddleTruncate, which I guess should be extracted from the old3d code and just become one of our common components. The LinkedGlobalVariable stuff can probably be deleted at the same time as we remove the panel itself.
