### ISSUE TITLE
Avoid subscribing to unnecessary topics in 3d panel.

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4393]
From a slack converstation:

The 3D panel always subscribes to camera info topics even when no camera image or camera info is turned on. If a user is not visualizing any camera stuff in the 3d panel we don’t want to be streaming the camera information back to the app. Just like we don’t want to be streaming camera images or other random topics that are not being put towards visualizing the scene.

We've agreed that the 3D panel should avoid subscribing to these topics when it does not need to use them.

**Comment by defunctzombie** [comment]
@jtbandes I am changing this to a bug. When topics are _off_ in the 3d panel we do not subscribe to them. The camera info topics violate this behavior.

**Comment by jtbandes** [comment]
Are we aware of any topics _other_ than cameras which have this problem?

**Comment by defunctzombie** [comment]
> Are we aware of any topics _other_ than cameras which have this problem?

I am not aware of any other topics having this problem. I think we've learned in the codebase that the _force_ property for subscriptions is only used for the camera info topics when activating the camera topics.
