### ISSUE TITLE
3D (Beta) Does Not Respect Collada up_axis

### ISSUE THREAD

**Issue by cody-sheff** [foxglove/studio#4416]
Currently, there's no option to have the 3D (Beta) tab respect the Collada up_axis argument like the 3D tab does, which can lead to issues when importing those meshes.

**Comment by jtbandes** [comment]
Prior work on this issue:

- https://github.com/foxglove/studio/issues/2706
- https://github.com/foxglove/studio/pull/2749

**Comment by defunctzombie** [comment]
Added the bug label because this is a regression in explicitly added and supported functionality in the 3d panel.

**Comment by jtbandes** [comment]
Fixed in https://github.com/foxglove/studio/pull/4442
