### ISSUE TITLE
Developer console logs are very noisy by default

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4431]
**Description**
Developer console should not show info-level logs by default, only errors + warnings.

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/637671/190329557-e57f3d8a-c8b7-4e99-aa4d-65515269179d.png">

User impact is that this makes extension development difficult due to all the noise.

**Comment by jtbandes** [comment]
> should not show info-level logs by default, only errors + warnings

Seems like this isn't something we have control over? Did you mean that we should downgrade some of our 'info' logs to 'debug' logs?

**Comment by defunctzombie** [comment]
My plan is to default disable all logs except _errors_ and _warnings_ in production. The new `Studio Logs Settings` panel will have a toggle to turn on the other log levels in production for inspection and debugging.



> Seems like this isn't something we have control over? Did you mean that we should downgrade some of our 'info' logs to 'debug' logs?

We do have control over this. All our logging happens through @foxglove/log and I will add a way for that to filter out specific levels. It already has a way to disable specific log categories.
