### ISSUE TITLE
Custom drag and drop is not working anymore

### ISSUE THREAD

**Issue by schmogmog** [foxglove/studio#4444]
Hello,

I have written a custom panel with which you can load files into foxglove via drag and drop.
But since version v1.25.0 this drag and drop element does not work anymore. Only the Foxglove application is focused when you drag a file into the application. Before, files could be loaded in foxglove via drag and drop, but if I dragged files over my own drag and drop element, it was focused and files could be loaded over it.

So I was wondering if this is a bug or whether this feature was intentionally removed.

Best Regards
Steven

**Comment by defunctzombie** [comment]
We only support drag & drop for all of foxglove not over a specific panel. If this worked in the past it was not an intentional feature to drag & drop on specific panels.
