### ISSUE TITLE
Cannot tab between settings sidebar fields

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4451]
**Description**

- Version: main
- OS: all
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): all
- ROS distro (if applicable): n/a

**Steps To Reproduce**

1. Select an editable field in the 3D panel settings sidebar that is followed by another editable field, such as "Translation Offset (X)" for a coordinate frame (with editing enabled).
2. Press tab

**Expected Behavior**

The following field in the sidebar becomes focused.

**Actual Behavior**

The following field in the sidebar does not gain focus.

**Comment by foxymiles** [comment]
I think fixing this should be as simple as setting `tabindex=0` on all inputs:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
