### ISSUE TITLE
Encoding Error ,cannot support Chinese character in RawMessage panel

### ISSUE THREAD

**Issue by hql420621** [foxglove/studio#4473]
**Description**

- Version: 1/24
- OS: ubuntu20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**
+ step1 add two panel ,Raw message  and Publish panel
+ step 2  choose a topic in Publish panel and change the value to Chinese Character
+ step3 subscribe the  same topic in Raw message,

**Expected Behavior**
the Chinese Character encoding show correct

**Actual Behavior**
error encoding
![image](https://user-images.githubusercontent.com/57355203/191886791-a51c94c7-a95b-4b30-938a-110647beb042.png)

**Comment by jtbandes** [comment]
Please fill in information about your data source. This is likely a problem with rosbridge.

**Comment by hql420621** [comment]
there is output of "rostopic echo ", it seems the rosbridge translate "中国" to "\u4E2D\u56FD" encode
![image](https://user-images.githubusercontent.com/57355203/191896617-531cafe5-a6c7-4bef-b900-dd20ed465b95.png)

**Comment by jtbandes** [comment]
Thank you for the report! The issue should be fixed now on studio.foxglove.dev and will be published in the next release.
