### ISSUE TITLE
Unintended placement of UI elements in panel full-screen mode

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#4478]
Likely related to @jtbandes' work in https://github.com/foxglove/studio/pull/4459.

**Description**
- Strange and likely unintentional placement of UI components in panel full-screen mode (see playback bar and panel settings below):

<img width="1512" alt="Screen Shot 2022-09-25 at 12 45 36 PM" src="https://user-images.githubusercontent.com/6993359/192162372-0732ff0e-2531-4d19-a7bf-149df1b3944d.png">

- Version: 1.25
- OS: MacOS Monterey 12.0
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Sample data
- ROS distro (if applicable): N/A

**Steps To Reproduce**

- Open Studio with sample data
- Full-screen the 3D panel

**Expected Behavior**
- Going into full-screen mode should close sidebar or at least completely cover it
- Going into full-screen mode should probably cover all or none of the sidebar menu as well (one visible cog icon is strange)
- Playback bar should take up full width of app if sidebar is closed

**Actual Behavior**
- Parts of sidebar menu and panel are visible
- Playback bar is weirdly floating on top of panel UI

**Comment by defunctzombie** [comment]
Related to this - I'm tempted to say that maybe "full screen" should mean "panel area" rather than sidebar? I think a useful workflow is to "full screen" a panel to configure it. For this we need sidebar visibility.

**Comment by foxymiles** [comment]
We should add a story for this too as part of the fix.

**Comment by jhurliman** [comment]
> Related to this - I'm tempted to say that maybe "full screen" should mean "panel area" rather than sidebar? I think a useful workflow is to "full screen" a panel to configure it. For this we need sidebar visibility.

As long as there is a "full full screen" option available.
