### ISSUE TITLE
Add ARGB (RViz-compatible) point cloud byte order option

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4483]
Add an ARGB byte order option to point clouds in the 3d Panel.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/84792/192318419-88627d8c-b830-44c7-939b-6c850fb3f042.png">

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/blob/58455bbe367d9e2b8067082e0178312916d2824a/packages/studio-base/src/panels/ThreeDeeRender/renderables/pointClouds/colors.ts#L81

**Comment by jtbandes** [comment]
For reference, this ARGB mode seems to be what rviz does by default:

https://github.com/ros-visualization/rviz/blob/a60b334fd10785a6b74893189fcebbd419d468e4/src/rviz/default_plugin/point_cloud_transformers.cpp#L400-L404

https://github.com/ros-visualization/rviz/blob/6a234b4404c5ee71051f0b338ab8d5d2d931c27b/src/rviz/default_plugin/point_cloud_common.cpp#L189-L196

**Comment by defunctzombie** [comment]
@jtbandes I am changing this issue to a bug. It seems we overlooked porting this mode to the new 3d panel and have regressed this functionality.

Below is the dialog from the legacy 3d panel point cloud settings:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/84792/197293391-18be820d-d15c-45f3-a617-4213fe5ab991.png">

**Comment by jtbandes** [comment]
Looks like we had 3 modes in the old 3d panel too, and they were named in opposite ways. I guess when they were ported over, we ended up with a different set of 3 modes and lost the rviz compatible mode.

This is a screenshot with old3d in "RGBA" mode and new3d in "ABGR" mode, and they match.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/14237/197295919-e8a294c1-8325-422d-8e8e-a7bb20da012a.png">

**Comment by jtbandes** [comment]
There is a branch to implement this 4th option: https://github.com/foxglove/studio/compare/aschimmichanga/issue4483. It will need to be rebased on top of #4687 before it can merge.

**Comment by defunctzombie** [comment]
@jtbandes I've re-assigned this to you. Let's get this regression fixed asap.
