### ISSUE TITLE
Editing a marker color hides the color input as it is still being edited

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4487]
In the 3D panel I've expanded the settings for a marker message and started to edit the color. After a second the color picker disappears and the settings are collapsed. I am not able to continue selecting the color I want.

https://user-images.githubusercontent.com/84792/192557977-1ed5401a-b23e-4d33-8b4f-db0427bbf98e.mov

**Comment by foxymiles** [comment]
This seems to have regressed in https://github.com/foxglove/studio/pull/4460.
