### ISSUE TITLE
Remove old3d

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4493]
Once the new 3D panel has been announced, and the old panel has been under a feature flag with a migration banner for a while, we plan to delete all the code for the old 3D panel.

At this time we can also delete the `panel: 3d legacy` issue label.

**Comment by defunctzombie** [comment]
I've moved this issue into the `remove fluentui/react` epic as it now only blocks items in that epic

**Comment by defunctzombie** [comment]
Blocked by: https://github.com/foxglove/issues/issues/119

**Comment by jtbandes** [comment]
Proposal is to merge this before the 11/28 release: https://github.com/foxglove/issues/issues/119#issuecomment-1302810324
