### ISSUE TITLE
App crashes when pasting color value into Gradient picker

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4497]
The app crashes when pasting a color value into the Gradient picker (settings editor)

1. Open the `Colors` storybook: https://603ec8bf7908b500231841e2-ftdjtiqpey.chromatic.com/?path=/story/components-settingstreeeditor--colors
2. Click on the first gradient color box
3. Copy the hex color value
4. Click on the second gradient color box
5. Paste the color value

https://user-images.githubusercontent.com/84792/192801718-1cdb6294-c1ee-4788-81b6-e917a8c56dde.mov

```
Minified MUI error #9; visit https://mui.com/production-error/?code=9&args[]=000000ff for the full message.
```

**Comment by jtbandes** [comment]
You can also reproduce this by simply typing 000000ff into the box.

**Comment by 2metres** [comment]
I think the error is coming from `getContrastText()` we need to sanitize the color before we pass it to the swatch
