### ISSUE TITLE
Allow filtering of events by metadata in Studio

### ISSUE THREAD

**Issue by bryfox** [foxglove/studio#4541]
We should include a single text field that allows a user to filter events based on metadata, using a simple `key:value` format (or a wildcard bare-value search of metadata). The filter should apply to the timeline and panel displays.

Use case: a user may want to limit the events shown on the timeline, especially when many events (or events with long durations) are displayed on the timeline.

**Comment by bryfox** [comment]
https://github.com/foxglove/studio/pull/4550

**Comment by foxymiles** [comment]
Sorry I should have linked this one to the PR. Closing now.
