### ISSUE TITLE
Put old3d under a feature flag

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4543]

**Comment by defunctzombie** [comment]
Adrian: we should wait 2 weeks after the banner goes out in a release.
Jacob: wait until after the Oct 10th release
Adrian: Merge ~Oct 17th

**Comment by amacneil** [comment]
The new release is out so this can be merged any time this week (before the 10/17 release).

We should only hide 3D Legacy from the panel list, it should otherwise continue working as usual for now. When you enable the feature flag we restore it to your panel list.
