### ISSUE TITLE
Mesh Import Discrepancy Between 3D and 3D (Legacy)

### ISSUE THREAD

**Issue by cody-sheff** [foxglove/studio#4552]
Currently there is a mismatch between the orientation that meshes are imported in the 3D tab, and the 3D (Legacy) tab. Attached is a .dae file that demonstrates the issue; when imported in the 3D and 3D (Legacy) tab, there seems to be a 90-degree difference about the z-axis between them.

Sample mesh to demonstrate the issue: [ybase.zip](https://github.com/foxglove/mcap/files/9708097/ybase.zip)

**Comment by jtbandes** [comment]
After creating a sample mcap file to show this mesh in the 3d panel, it looks like this:

[mesh.mcap.zip](https://github.com/foxglove/studio/files/9710472/mesh.mcap.zip)

<img width="426" alt="image" src="https://user-images.githubusercontent.com/14237/193921709-c2b172cb-25c3-409c-9485-16a3b583434f.png">

Which is the same as Blender: 
<img width="811" alt="Screen Shot 2022-10-04 at 1 19 58 PM" src="https://user-images.githubusercontent.com/14237/193921857-687f8432-5fd1-44be-84fa-6b3a1457a816.png">

So this is behaving as intended.

**Comment by horverno** [comment]
I can confirm the 90 deg roll error in Foxglove Studio 1.29.0 compared to rviz.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/11504709/197197655-8a05a69d-7dfa-493e-b1d1-871fe6bdf22d.png)

![image](https://user-images.githubusercontent.com/11504709/197197436-e1d2c9fd-c072-4ed5-97f3-36524f575a1c.png)

**Comment by jtbandes** [comment]
Please try this new setting: https://github.com/foxglove/studio/pull/4577

**Comment by horverno** [comment]
> Please try this new setting: #4577

Thank you @jtbandes New3D panel>>Settings>>Scene>>Mesh up axis set to `Z-up` solves the problem :+1: 

![image](https://user-images.githubusercontent.com/11504709/197483462-d4afeb71-2d62-44e7-9448-c7bdf9202e4a.png)
