### ISSUE TITLE
Fields Change Spacing when opening first topic in 3D Panel 

### ISSUE THREAD

**Issue by snosenzo** [foxglove/studio#4566]
**Description**
 - probably applies to all panels with nodes that have children, but opening the first topic/child in the 3D panel changes the spacing of fields elsewhere in the panel (in the scene) as shown below
 

![3dpaneluibug](https://user-images.githubusercontent.com/10187776/193931721-9e5f72ff-05bd-4a16-b5f1-cef695aac766.gif)

- Version: 1.27.0-dev
- OS: mac/web
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): nuscenes example

**Comment by foxymiles** [comment]
I personally do not consider this a bug. You can have dynamic spacing to accommodate all visible labels or fixed spacing which is generally worse in most cases but not both.
