### ISSUE TITLE
Can't connect to ROS Master or ROS Websocket Bridge

### ISSUE THREAD

**Issue by dignakov** [foxglove/studio#458]
Stuck connecting when trying to open a connection to ROS on localhost (v0.3).

![image](https://user-images.githubusercontent.com/810523/113481549-2dc00280-9468-11eb-8921-6a7899aaf30a.png)

**Comment by defunctzombie** [comment]
Few questions to help me debug this with you:

* What Operating System are you using?
* Is ROS running on your host machine or in a virtual machine? docker?
* Do you see any errors in any other part of the app?
* Could you open `View -> Advanced -> Toggle Developer Tools` and report and errors you see there.

Let's start with those and see if we learn anything new.

**Comment by dignakov** [comment]
Thanks for looking into this. Happy to provide as much debugging info as I can, foxglove looks awesome and I'd love to use it.

OS: Ubuntu 20.04
ROS: Noetic, running locally
Foxglove: deb from the site

Error/Warnings/Output:

when launching foxglove
```
$ foxglove-studio 
APPIMAGE env is not defined, current application is not an AppImage
```

other terminal output:
```
[13729:0403/112908.175627:ERROR:CONSOLE(1)] "Session is unregistering, can't dispatch pending call to Debugger.setBlackboxPatterns", source: devtools://devtools/bundled/sdk/sdk.js (1)
[13729:0403/112950.161437:ERROR:CONSOLE(6)] "Uncaught TypeError: e.consoleMessage is not a function", source: devtools://devtools/bundled/console/console.js (6)
```

developer console (sorry, I'm not sure how to copy that so I took a screenshot instead):

![image](https://user-images.githubusercontent.com/810523/113483174-1422b900-9470-11eb-918f-8a1ebe60e3a3.png)

Hope this helps.

**Comment by amacneil** [comment]
Interesting. Is that the last error in the developer console if you scroll down? Usually when it is connecting, we see a message each time it attempts a connection. 

Do you see any other messages in the console when you try a rosbridge/websocket connection?

**Comment by dignakov** [comment]
Sorry, I think it was the last error, but now I'm not sure...

I actually can't connect to websockets either. I opened a second issue for that (#459). But this is what the console displays before any connections and after attempting to connect to a websocker or ros. Nothing after this comes up on the console if I leave it alone and it just shows the wheel as it's trying to connect.

start:
![before_connection_attempt](https://user-images.githubusercontent.com/810523/113485389-3968f480-947b-11eb-87f2-a5bd7459900c.jpg)

websocket:
![after_websocket_attempt](https://user-images.githubusercontent.com/810523/113485408-53a2d280-947b-11eb-8207-056b1c6b6ceb.png)


ros (closed foxglove, reopened and tried connecting to ros):
![after_ros_attempt](https://user-images.githubusercontent.com/810523/113485414-57365980-947b-11eb-959c-102b81434d1d.jpg)

**Comment by defunctzombie** [comment]
@dignakov I suspect I've traced down what the issue might be - and we have a fix in our main branch which has not made it into a release yet. We will release a patch version this weekend (latest Monday) for you to try.

**Comment by amacneil** [comment]
@dignakov could you test this version?

https://storage.googleapis.com/foxglove-releases/v0.3.0-nightly.20210404.3dc0144/foxglove-studio-0.3.0-nightly.20210404.3dc0144-linux-amd64.deb

**Comment by dignakov** [comment]
Still can't seem to connect.

start:
![v0 3-nightly-start](https://user-images.githubusercontent.com/810523/113515707-2a01ae00-9544-11eb-9d07-047a952591d3.png)

connecting to ros:
![v0 3-nightly-ros](https://user-images.githubusercontent.com/810523/113515714-37b73380-9544-11eb-9286-f38181d9538d.png)


connecting to websocket:
![v0 3nightly-websocket](https://user-images.githubusercontent.com/810523/113515730-4e5d8a80-9544-11eb-82e2-ff9ac8082a37.png)

**Comment by defunctzombie** [comment]
@dignakov if you'd like to jump into our slack https://github.com/foxglove/studio#support I can get some more details there and try a few additional troubleshooting items.

**Comment by defunctzombie** [comment]
Closing this. We've fixed some more issues with the app connections and startup. Let me know if this continues to not work for you.
