### ISSUE TITLE
Can't connect to websocket

### ISSUE THREAD

**Issue by dignakov** [foxglove/studio#459]
It seems that I can't connect to a web socket source either (v0.3) . . .

I tested with webviz, and it seems to work fine, but foxglove gets stuck connecting.

Some more information:
OS: Ubuntu 20.04
ROS: Noetic
Foxglove: deb from the site
Webviz: docker (works when connecting to the ws server running locally and in a docker container)

![foxglove_localhost](https://user-images.githubusercontent.com/810523/113481776-8cd24700-9469-11eb-875d-23634c4f8124.jpeg)
![webviz_localhost](https://user-images.githubusercontent.com/810523/113481778-8d6add80-9469-11eb-8e9a-a41a982d8a93.jpg)

dev console:
![image](https://user-images.githubusercontent.com/810523/113483459-7def9280-9471-11eb-9831-33de7ef0997f.png)

**Comment by defunctzombie** [comment]
Closing this in favor of https://github.com/foxglove/studio/issues/458 which has some additional details. I think these two issues are related so we can discuss in once place.
