### ISSUE TITLE
Image display snap image to panel size

### ISSUE THREAD

**Issue by KerstinKeller** [foxglove/studio#4608]
When arranging multiple images in a layout, one wants to see as much of the image as possible.
However, as you can see in the short video, we have a lot of "dead" space in the layout, it's impossible to zoom the displayed images so they make most of the available panel size.
It would be great to either have a setting that snaps the displayed image size to the panel size, or allow more fine grained scrolling, 

https://user-images.githubusercontent.com/13848742/194878218-6e417b8d-f6f0-4180-82d8-e2a1504a61c1.mp4

**Comment by jtbandes** [comment]
Have you tried the "zoom to fit" and "zoom to fill" options under the 🔍 menu?

<img width="225" alt="image" src="https://user-images.githubusercontent.com/14237/195459421-89718e16-5069-429e-ae06-aa70f0ae3698.png">

**Comment by KerstinKeller** [comment]
Ahhh, I never noticed the  🔍 as they only pop up, when you hover over the panel. And if I did, I didn't make the connection.
I expected zoom to be part of the settings, like the flip vertical / horizontal / rotate, but couldn't find anything.

But now it works perfectly, thanks!
