### ISSUE TITLE
Style uplift on Studio Readme

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#4615]
Feedback from @amacneil:
> Really nice readme hero image, badges and links. we could do something similar for mcap + studio repos: https://github.com/prisma/prisma#readme

<img width="934" alt="Screen Shot 2022-10-12 at 7 38 46 am" src="https://user-images.githubusercontent.com/924528/195193690-0b541b3b-d9b9-4c1d-969b-2386350378b8.png">

**Comment by 2metres** [comment]
Might be worth reconsidering the content of the Readme at this momemnt as well

**Comment by amacneil** [comment]
Don't overthink it, just a nice header image, centered title, and links is a great improvement.

**Comment by ocin-rye** [comment]
Uploading header image here to reference GitHub image URL in the readme file.

![readme-header](https://user-images.githubusercontent.com/14011012/195717422-bfcc5a12-0281-4f30-b310-9322f6fdd660.png)
