### ISSUE TITLE
Missing thumbnail image for "Parameters" panel in new layout view

### ISSUE THREAD

**Issue by banisadr** [foxglove/studio#4625]
**Description**
Very minor, as described in title - just need to create art & add

**Steps To Reproduce**
Go to studio.foxglove.dev, create new layout

**Expected Behavior**
All panel preview tiles in the new layout landing page should have sample images.

**Actual Behavior**
![image](https://user-images.githubusercontent.com/12058745/195452954-36fd6810-6ceb-4f57-947d-8e5ec3f90ead.png)

**Comment by defunctzombie** [comment]
What type of image would speak "parameters" to you?

**Comment by banisadr** [comment]
Something marginally less bland than a grey void. My is something similar to the top half of the Data Source Info thumbnail image crossed with this random list of params I just pulled from the ROS Docs?

<img width="805" alt="image" src="https://user-images.githubusercontent.com/12058745/195959149-30498cc8-5260-42ba-9066-4ad4bf8dfc0d.png">

**Comment by defunctzombie** [comment]
@2metres sending your way to scope and resolve. I agree that every built-in panel should have a thumbnail.

**Comment by jtbandes** [comment]
While we’re at it maybe we can get light mode versions of the thumbnails 😀

**Comment by defunctzombie** [comment]
> While we’re at it maybe we can get light mode versions of the thumbnails

Scope creep. This is how it starts.
