### ISSUE TITLE
Looping toggle does not persist when restarting Studio

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4644]
The "loop playback" toggle always resets to off when restarting Studio, regardless of user setting. The playback rate control on the same playback bar does get remembered across sessions, though.

**Comment by jtbandes** [comment]
Duplicate of https://github.com/foxglove/studio/issues/2594. Should we reopen that issue?

**Comment by jtbandes** [comment]
Duplicate of #2594
