### ISSUE TITLE
diagonal and blocky artifacts with overlapping foxglove.Grid instances

### ISSUE THREAD

**Issue by james-rms** [foxglove/studio#4647]
**Description**
A continuation of #4641 - I tried shortening the far clipping plane of the camera by a factor of 50 (which should increase the bit depth of the Z-buffer by the same factor) but this made no improvement on the number of block artifacts that I previously attributed to z-fighting. There are also some diagonal lines appearing in the artifacts which shouldn't happen as a result of Z-fighting. Some screenshots:

![image](https://user-images.githubusercontent.com/18162835/196089491-3cd51fa5-0db8-4a87-8181-74d3dcc40321.png)
![image](https://user-images.githubusercontent.com/18162835/196089521-380f0534-1d58-4755-a336-cf07a9cc8900.png)

- Version: studio.foxglove.dev
- OS: Chrome Version 106.0.5249.103 (Official Build) (arm64)
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): check the NuScenes sample data for a good example
- ROS distro (if applicable):

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by snosenzo** [comment]
Would a possible solution to this to be to change the example file to put the driveable_area on a coordinate frame as a child of `map` that has a translation like .05 above the map? (that way it can also be adjustable to users)

**Comment by jtbandes** [comment]
I played with this a bit more and I saw that adjusting the near plane seemed to have the desired effect of removing the artifacts. So I do believe that we are seeing "regular" z-fighting here. I'm making a PR to allow enabling logarithmic depth: #4662

https://user-images.githubusercontent.com/14237/196517231-d46ffcbf-cf64-491b-9389-ccad8302b5bd.mov
