### ISSUE TITLE
Re-enable transform preloading in 3D panel

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4657]
Context: https://github.com/foxglove/studio/pull/4656

**Comment by defunctzombie** [comment]
Escalating to a bug so we can discuss. This is a feature we've shipped and also started to inform customers about. We need to think through how to bring this back ASAP. I don't think we've updated documentation for transform preloading details yet so we are ok on that front but generally a revert of a supported workflow needs escalated follow-up so we make sure we cleanup docs or other references.

**Comment by defunctzombie** [comment]
When we re-enable using preloaded transforms we need to ensure we avoid this bug: https://github.com/foxglove/studio/issues/4605

**Comment by defunctzombie** [comment]
Closing this out. We've created a linear project tracking adding this back in and have prioritized it. I consider us tackling this high priority and we've noted that in the planning of our projects.
