### ISSUE TITLE
Cannot use ROS1 native connection as data source in the latest release

### ISSUE THREAD

**Issue by maetulj** [foxglove/studio#4677]
**Description**
I am experiencing troubles connecting to a ROS 1 interface using Foxglove-Studio 1.29.0. When I try to open a connection to a robot using ROS 1 the application just stays loading, never finishing or showing any errors. This is only happening with recent release.
When I use Foxglove-Studio 1.27.0 the connection is established. Also native ROS installation on my PC can reach the topics on the robot.

- Version: 1.29.0
- OS: Ubuntu 20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS 1 native
- ROS distro (if applicable): Melodic/Noetic

---

**Steps To Reproduce**
Open a new connection to ROS1, set the ROS_MASTER_URI and ROS_HOSTNAME. Press "Open".

---

**Expected Behavior**
Connection is opened, topics can be seen.

---

**Actual Behavior**
The app stays loading (with the spinner active) without any information on what is happening.

**Comment by jtbandes** [comment]
Hi, thanks for the report. We have made some recent improvements (since v1.29) around ROS 1 connections:
- #4634 

Could you please try out this build (made from `main`)? https://drive.google.com/file/d/1PME2V3aFwVMZ4JVHFANf9KlttNvtKt6I/view?usp=sharing
