### ISSUE TITLE
Can't open UDP port for Velodyne LIDAR on the V1.29.1

### ISSUE THREAD

**Issue by jessaggie** [foxglove/studio#4689]
**Description**
When trying to open the UDP port connection to the Velodyne Lidar, nothing happens when pressing open. 

- Version:
- OS:  Windows 10
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):  Velodyne Lidar connection
- Foxglove version V1.29.1

**Steps To Reproduce**

1. Add a data source
2. click open connection
3. click Velodyne LIDAR
4. type in any port
5. press open

**Expected Behavior**
At this point, the port should open and the open new connection window should close

**Actual Behavior**
The open new connection window does not close and nothing happens when you click open.

**Comment by defunctzombie** [comment]
Are you able to open the Velodyne management webpage in your web browser?

Is your wired network configured correctly (with the correct IP and subnet)?

**Comment by amacneil** [comment]
@jtbandes: When the lidar is not reachable we never close the dialog making it look like we never handled your click on the "open" button?

@defunctzombie: I will check this behavior.
