### ISSUE TITLE
Visualization_msgs/Marker cube_list not updating correctly

### ISSUE THREAD

**Issue by wouter-heerwegh** [foxglove/studio#4699]
When using a cube_list as visualization_msgs/Marker, the cubes do not get updated correctly in the 3D panel. They keep the position of the first position that is published. When looking at the raw data, the cubes do get different coordinates.

- Version: 1.29.1
- OS: Ubuntu 20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): both native ROS1 and rosbag
- ROS distro (if applicable): Noetic

**Steps To Reproduce**

- Download [this bag](https://drive.google.com/file/d/1QTNDHmvmkDr-Y06nWjY3xnajivH0knNQ/view?usp=sharing)
- Subscribe to the `/conestreamer/ground_truth_track`
- Show this topic in the 3D panel

**Expected Behavior**
Constantly updating positions of the cubes

**Actual Behavior**
Cubes not moving, some are disappearing and coming back in the same position.

**Comment by snosenzo** [comment]
Hey, just landed a fix. Should be out in the next release! Thanks for filing and let us know if you have any more issues!

**Comment by wouter-heerwegh** [comment]
Tested with 3089eadac185f934ea6bc37c890fe11080cefd5b, works correctly. Thanks for the fix!
