### ISSUE TITLE
DP playback issuing many requests and not proceeding under some condition

### ISSUE THREAD

**Issue by wkalt** [foxglove/studio#4744]
Repro steps:

1. Open this link in studio (must be signed into Foxglove HQ):
https://studio.foxglove.dev/?ds=foxglove-data-platform&ds.deviceId=dev_Wm1gvryKJmREqnVT&ds.end=2022-08-22T00%3A02%3A11.940Z&ds.start=2022-08-21T19%3A59%3A22.201Z&layoutId=9c6018d1-2b91-42ff-af34-4f6e4df6f68b&time=2022-08-21T19%3A59%3A53.022858460Z
2. Configure a single raw message panel and set it to display /imu
3. Hit play

Playback will make no progress. Observe in the network tab that we will make hundreds of tiny requests receiving no data back. There is legitimately no data in the small time window being requested.

Set the topic instead to /rosout and see that playback works.

It seems like we are hitting some condition where we enter a retry loop if no messages exist in the requested window. This can happen if your request falls between messages, and is more likely if the number of topics being requested is few.

**Comment by defunctzombie** [comment]
Url for myself to test in hq dev: http://localhost:8080/?ds=foxglove-data-platform&ds.deviceId=dev_GLQsznQJcUbZvyf1&ds.end=2022-08-21T20%3A19%3A55.540Z&ds.start=2022-08-21T19%3A57%3A49.954Z&layoutId=a7ddb3bd-1bb1-4469-9ec0-a899b690b055&time=2022-08-21T20%3A02%3A49.738824292Z
