### ISSUE TITLE
add support to load pcl data with field count > 1

### ISSUE THREAD

**Issue by oosthoek** [foxglove/studio#4746]
i have rosbag with pointfield "timestamp" that has count > 1.
when trying to visualize, i get `PointCloud field "timestamp" has invalid count 8. Only 1 is supported`
i am not trying to visualize this field, but want to visualize the xyz fields also in the pcl. 
can support be added to still load the pcl?

i have attached sample bag 

[sample.zip](https://github.com/foxglove/studio/files/9924628/sample.zip)

**Comment by jtbandes** [comment]
Thanks for the report. I'm upgrading this to a bug because the app should still be usable as long as you are not using this field.

Out of curiosity, why does the field have count `8`? Does it really contain 8 values? How did you create this point cloud?
