### ISSUE TITLE
Weird UI when hovering over message in RawMessagePanel

### ISSUE THREAD

**Issue by KerstinKeller** [foxglove/studio#4749]
**Description**

I saw a strange flickering when hovering over messages in the RawMessagePanel.
It occurs when the message panel is just barely wide enough to show the data.
When you then hover the mouse over any data element, it just goes back and forth.

I guess what actually happens, when you hover some additional stuff is displayed on the item, which introduces a line break and expands, but then as soon as it is expanded, the mouse is no longer hovering, so it collapses again. and this just repeats infinitely.

The video does not quite capture the actual speed at which it flickers.

Foxglove version 1.30.0

**Expected Behavior**
No jumping back and forth

**Actual Behavior**

https://user-images.githubusercontent.com/13848742/199702196-075e7a33-3ef0-46e8-aae4-3095c4a54a71.mp4

**Comment by snosenzo** [comment]
Thanks for filing! I'm able to reproduce and will work on a fix now.
