### ISSUE TITLE
How to display multiple mesh models simultaneously

### ISSUE THREAD

**Issue by chengchi-qy** [foxglove/studio#4757]
**Description**
I'm having a problem when showing the car models(OBJ,dae）.
I am displaying multiple mesh models simultaneously. But when I play it, the positions of the different models blend together.

Right display
![image](https://user-images.githubusercontent.com/108607842/199879052-3663b527-f414-4e80-ac03-87f989ceaf21.png)

When it starts playing, some of the mesh appears in the wrong place
![image](https://user-images.githubusercontent.com/108607842/199879313-7502553f-d96e-4799-988c-0032ee754ccf.png)

Could you tell me some examples for  displaying multiple mesh models simultaneously, thanks.

**Comment by defunctzombie** [comment]
Thanks for the bug report. There are many potential causes for what could be happening and the best way we can help resolve this is with a file to reproduce the issue. If you have sensitive data in the file please omit that or create a sample file reproducing the issue.

Other helpful information once we have the file are the frame you are viewing data in and where in the data we can experience the issue.

**Comment by defunctzombie** [comment]
Closing this issue for lack of follow-up response. We're happy to take a look but need a better issue description and some sample data that reproduces the issue. If these are provided we can re-open and investigate.
