### ISSUE TITLE
Add "Open from Data Platform" to Studio Welcome Dialog

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#4759]
![Image](https://user-images.githubusercontent.com/6993359/200681280-81af639b-80e9-4b2d-96f8-434e52fa78fb.png)

Would open Console's "Recordings" page.

**Comment by amacneil** [comment]
What words are we planning to use?

Needs mockup.

**Comment by esthersweon** [comment]
My proposal:

![Image](https://user-images.githubusercontent.com/6993359/200681115-6c790b18-f585-4410-9e2f-04a12fca4ce8.png)

This would link directly to Console's "Recordings" page (or sign in page, if not yet logged in).

Thoughts @amacneil @ocin-rye?

**Comment by jtbandes** [comment]
Should we give it some different/brighter styling as a way to upsell more? Also does Data Platform have a logo we can use instead of the "file with globe" icon?

**Comment by esthersweon** [comment]
@jtbandes - I prefer the overall option looking similar to the other ones, just so we're not pushing paywalled tools in users' faces. But I'm open to the designers' thoughts. I think a DP-specific icon would be subtle enough though.

Opened PR at https://github.com/foxglove/studio/pull/4785.

**Comment by amacneil** [comment]
How about "Browse data"? It's not perfect, but if you are in the mindset that Foxglove hosts data it's sensible.

"Open remote recording" sounds clunky to me, what is a remote recording?

Also, we should link to whatever page in console is the default (currently timeline). If we don't think the default page in console is the best place to browse data, we should fix that separately.

**Comment by ocin-rye** [comment]
![studio foxglove dev__layoutId=15a0784c-c1c6-447c-98c8-377426f17af7 (1)](https://user-images.githubusercontent.com/14011012/200892189-1bad949d-8874-40c7-bad5-5afa81a094a2.png)


Maybe "Browse remote data"? I like "Browse data" and I think "remote" would help clarify that this option is not related to browsing local data.

@esthersweon I like the idea of linking a non logged in users to a sign-in/sign-up page when they select that option. This could be a clear way to communicate the limitations of not signing up for Data Platform.

**Comment by esthersweon** [comment]
@amacneil @ocin-rye - We currently use "Open ..." for the other 2 data source options, so I wanted to keep that prefixing consistent. Maybe "Open remote data", if we think "recording" is confusing.

> Also, we should link to whatever page in console is the default (currently timeline). If we don't think the default page in console is the best place to browse data, we should fix that separately.

Why do you feel that this entry point needs to link to the default page for Console? If the CTA is to "Open remote data", I think we should take users to a page where it requires the least amount of work do just that (i.e. 1 click to "View in Studio" from the "Recordings" page). 

The "Timeline" page is a little more removed from that action, so it feels more confusing (more potential for user drop-off). With that said, it still makes sense as the high-level view that a user logging into Console first should see.

**Comment by amacneil** [comment]
> The "Timeline" page is a little more removed from that action, so it feels more confusing (more potential for user drop-off). With that said, it still makes sense as the high-level view that a user logging into Console first should see.

This begs the question why the Timeline view is the default in Console, if we expect the main thing people want to do is browse data, and we think the Timeline view is not good for browsing data. Maybe we should change that, but my point is that I don't see why it should be different for Studio users vs people navigating directly to Console.

**Comment by esthersweon** [comment]
@amacneil - I'd assume that a user logging directly into Console would more often want a birds' eye view of their data coverage. The app focuses on data management, organization, and tagging, so knowing at a glance what the overall makeup of your imported data looks like would be useful.

On the other hand, someone coming in through Studio is interested in drilling down into specific segments of data – for visualization, analysis, etc. I'd assume that user would be less interested in overall coverage, and more so on worthwhile segments to play back.

**Comment by amacneil** [comment]
@esthersweon ok that's fair.
