### ISSUE TITLE
the URDF viewer in latest web browser can not load the urdf model but the deskapp can 

### ISSUE THREAD

**Issue by hql420621** [foxglove/studio#4795]
**Description**
the URDF viewer in latest web browser can not load the urdf model but the deskapp can ,,actualy my path of model is correctly,
how the web browser load local urdf model, does web browser app can realize the path of local path

- Version:latest
- OS:ubuntu 20.0
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**

step : drag urdf model into urdf viewer

**Expected Behavior**
can show the urdf model correctly

**Actual Behavior**
![image](https://user-images.githubusercontent.com/57355203/201060836-f93863b0-1b44-456b-97f0-4f8f5d57257e.png)

**Comment by jtbandes** [comment]
> does web browser app can realize the path of local path

No, it is not possible for the web browser to fetch from local file paths, for security reasons. You will need to use the desktop app: https://foxglove.dev/docs/studio/getting-started#desktop-only-features
