### ISSUE TITLE
Flashing OccupancyGrid on live connections with multiple renderables

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4798]
**Description**

- Version: main
- OS: Ubuntu 22.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): foxglove_bridge
- ROS distro (if applicable): Galactic

**Steps To Reproduce**

1. Clone the foxglove_bridge repo, build, run the script to download test data
2. `ros2 bag play -l -s mcap src/ros-foxglove-bridge/data/nuScenes-v1.0-mini-scene-0061-ros2.mcap`
3. `ros2 run foxglove_bridge foxglove_bridge`
4. Connect studio to ws-protocol in a layout with only a 3D panel
5. Enable only the `/map` topic, observe the OccupancyGrid appears and stays on the screen
6. Enable a high-bandwidth topic such as `/LIDAR_TOP`, observe the OccupancyGrid periodically disappears and reappears

Note this repro is very timing sensitive, attempting to capture a screen recording on Ubuntu 22.04 slowed rendering down enough that the bug would not reproduce. Hence the cameraphone screen capture.

https://user-images.githubusercontent.com/195374/201184039-411d6532-058c-4d50-b4a4-56eb8f6d1d56.mp4

**Expected Behavior**

OccupancyGrid should never disappear. It is not skipped over in the rendering loop, and visibility is not set to false anywhere.

**Comment by jtbandes** [comment]
Sounds like this might be related to timestamps going backward. Need protocol-level changes to handle this any better.
Related: https://github.com/foxglove/ws-protocol/issues/256
