### ISSUE TITLE
ws-protocol data source does not adjust start timestamp when an earlier timestamp is received

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4804]
**Steps To Reproduce**
1. Start rosbag playback with --clock 100 and -l and start foxglove_bridge
2. Connect to the bridge when playback is partway through the file
3. Wait for playback to loop, and observe a negative duration in the Data source sidebar

**Expected Behavior**

The start time is updated whenever an earlier message timestamp is received

**Comment by jhurliman** [comment]
In addition, I think end time should be the max observed timestamp instead of the current time.

**Comment by jtbandes** [comment]
I noticed this too while working on https://github.com/foxglove/ws-protocol/pull/270. The duration would be negative after playback looped.
