### ISSUE TITLE
I'm unable to render the visual collision scene assets(format STL) on the 3D panel, similar to what I would see on Rviz

### ISSUE THREAD

**Issue by kevin-kindred** [foxglove/studio#4808]
**Description**
I'm unable to render the visual collision scene assets(format STL) on the 3D panel, similar to what I would see on Rviz

- Version: 1.31.0
- OS: MacOS 12.6.1
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): rosbridge
- ROS distro (if applicable): ROS2 Humble

**Steps To Reproduce**
1. Start a ROS2 application that publishes assets & robot description on the topic /robot_description(This is for a serial manipulator and using MoveIt)
2. Install ros-humble-rosbridge-suite & start rosbridge-server using `ros2 launch rosbridge_server rosbridge_websocket_launch.xml`
3. Open connection to robot using rosbridge on native client/browser
4. Create a 3D panel

**Expected Behavior**
I can see the serial manipulator similar to how it's seen in Rviz
![6301abc3-6cdf-4430-a8fd-bea97106f56e](https://user-images.githubusercontent.com/72746526/201576962-0e975436-26ed-46e0-a329-cb94cb6e12e5.png)

**Actual Behavior**
I see just the links & their reference frames
![Screen Shot 2022-11-13 at 11 40 31 PM](https://user-images.githubusercontent.com/72746526/201576678-43d2ddbe-651f-4f79-ac2a-b94403e626c5.png)

I also see this error on the 3D panel settings
![Screen Shot 2022-11-13 at 11 41 40 PM](https://user-images.githubusercontent.com/72746526/201576810-f6f1f64d-bb84-4e3f-ac76-dd5700ca99ce.png)

**Comment by jtbandes** [comment]
> Open connection to robot using rosbridge on native client/browser

Please note that package:// urls only work in the Desktop app, as documented here: https://foxglove.dev/docs/studio/panels/3d#add-unified-robot-description-format-urdf

Additionally, you may need to configure the ROS_PACKAGE_PATH here:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/14237/201734792-860c14af-58e8-4377-af19-f618a5db807b.png">

**Comment by jtbandes** [comment]
@kevin-kindred Any update on this? Were you able to get it working properly?

**Comment by jtbandes** [comment]
I'm going to close out this issue since we haven't heard back in a few weeks. Let us know if you are still having trouble and we can continue helping out.

**Comment by kevin-kindred** [comment]
Apologies for not getting back earlier. I believe `ROS_PACKAGE_PATH` is not a variable that ROS2 supports anymore https://github.com/ros/ros_environment/issues/25

Also for a bit more context, I'm trying to visualize the manipulator from UR using their ROS2 description https://github.com/UniversalRobots/Universal_Robots_ROS2_Description
