### ISSUE TITLE
Allow customizing `selected_id` variable for different topics in 3D panel

### ISSUE THREAD

**Issue by asyncanup** [foxglove/studio#4826]
In the new 3D panel, when you select an object and then hover over its id field, there is no button for setting it as a var. Instead, `selected_id` var is filled in automatically.

We can no longer split IDs by type. For example, previously when selecting a non-TopicA object, the selected_topic_a_id linked variable would stay at the ID of the last selected TopicA marker.
But with the new 3D panel, if I select an unrelated object, the `selected_id` var will be updated and other open panels (say, State Transition panel) will try to display data for a TopicA object with this ID, which leads to random TopicA data being displayed in the open (State Transition) panel.

Old code was here: https://github.com/foxglove/studio/blob/main/packages/studio-base/src/panels/ThreeDimensionalViz/threeDimensionalVizUtils.ts#L152:L152

- Version: 1.31.0
- OS: All
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**
Described in description above.

**Expected Behavior**
Old 3D panel behavior, with separate `selected_<topic>_id` variables, instead of all selected objects from all topics overriding a single `selected_id`

**Actual Behavior**
Single global `selected_id` var gets overwritten with id from unrelated topics, leading to open panels displayed random or missing info.

**Comment by jtbandes** [comment]
UX decision from slack: The variable name will be exposed as a setting under each SceneEntity/Marker topic in the 3D panel's settings sidebar.
