### ISSUE TITLE
Link 3D Panels

### ISSUE THREAD

**Issue by banisadr** [foxglove/studio#4846]
Ability to sync or "lock" multiple 3D panels together in a layout such that pan/zoom in one does the same in the other linked panels. Needs both the ability to do 1-time sync of panels as well as ability to lock panels together.

**Comment by foxymiles** [comment]
Do we want to sync the complete camera state or just pan zoom? If we only sync pan and zoom that might not make sense for different views with different initial camera states right?

**Comment by foxymiles** [comment]
Also if there is a mix of 3d and 2d views in a layout how should we sync them?

**Comment by foxymiles** [comment]
Screenshot of the feature in the old 3d panel:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/93935560/202965004-415c4f0e-1370-4892-902b-9afef78e2927.png">

**Comment by jtbandes** [comment]
Assigning to @snosenzo to get #4859 over the finish line with the changes requested in https://github.com/foxglove/studio/pull/4859#issuecomment-1322801204
