### ISSUE TITLE
Image rendering does not update when CameraCalibration changes

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4851]
**Steps To Reproduce**
- Run this script: https://gist.github.com/jtbandes/b549f560679708507b13fb1633c4fac0
- Connect Studio using Foxglove WebSocket connection, open a 3D panel, turn on both the RawImage and CameraCalibration topics
- Edit the script to change `fx` and `fy`
- Kill the script and run it again, allowing studio to auto-reconnect

**Expected Behavior**
Image and camera frustum should always match

**Actual Behavior**
Image does not update but frustum does.
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/14237/202587484-f6002ddd-6d95-4dc4-87f6-356dee08c297.png">

**Comment by danielgordon10** [comment]
If you change the distance then the image also goes back to working as expected.
<img width="349" alt="Screenshot 2022-11-17 at 4 41 10 PM" src="https://user-images.githubusercontent.com/7245472/202590184-dda00f3f-2c0d-4b25-b7e4-b14875d14666.png">
