### ISSUE TITLE
Data are accumulated on the source frame instead of the display frame when decay time > 0

### ISSUE THREAD

**Issue by cedrusx** [foxglove/studio#4892]
**Description**
In the 3D panel, the accumulation of laser scan (not sure about other types) seems to be problematic when setting a positive value of decay time. I expect its points to be accumulated on the display frame, like in RViz. But it seems to be accumulating on the data source frame or other way. 

- Version: 1.32.0-dev
- OS: Windows 11
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**

Open a bag that has a laser scan topic, where the scan data are associated on a sensor frame (e.g. "laser"), and the sensor frame is moving w.r.t. a world frame (e.g. "world"), with correct transformations on /tf.
Open a 3D panel, in its settings, set the Display frame to be the world frame and the Follow mode to be Fixed. Then turn on the scan topic, and set its decay time to a positive number such as 100.

**Expected Behavior**
The scan points are accumulated on the world frame, so that they form the shape of the environment when the robot is moving.

**Actual Behavior**
The accumulated points move with the robot.

See an example below: 
(on the right hand side there is the accumulation of the same data in RViz, for comparison)

![foxglove3](https://user-images.githubusercontent.com/17380916/204307685-f85cc709-d9e4-4d56-b296-d4c60ec730c1.gif)

**Comment by jtbandes** [comment]
Hi @cedrusx, would you be able to provide a sample bag we can use to test the issue?

This is probably related to the fact that we treat point clouds & laser scans as "frame_locked=false", meaning their locations are set in the fixed frame when they are received.

**Comment by jtbandes** [comment]
Another simpler sample file that can be used to reproduce the issue: [gh4892_decay_time.mcap.zip](https://github.com/foxglove/studio/files/10233026/gh4892_decay_time.mcap.zip)

**Comment by jtbandes** [comment]
Thanks for the report. I've fixed some issues in #4986 and I believe it's now behaving correctly! Here's what your sample data looks like now:

https://user-images.githubusercontent.com/14237/207955675-0ffb7406-3bff-4a8e-8db9-2ffaca5133f8.mov

**Comment by cedrusx** [comment]
Awesome! Thank you for the quick fix!
