### ISSUE TITLE
Opening Timeline Recording to Desktop on Windows Fails

### ISSUE THREAD

**Issue by banisadr** [foxglove/studio#4896]
**Description**
Opening a recording from timeline to desktop on Windows results in a blank studio client.

- Version: 1.33.0
- OS: Windows

**Steps To Reproduce**
1. Set Studio to open links in desktop 
![image](https://user-images.githubusercontent.com/12058745/204601989-e8f99f2d-aa0d-4847-bba2-0940ef3c0c67.png)
2. Select recording time-range in Console
3. Attempt to open time-range

**Expected Behavior**
Recording range opened in studio

**Actual Behavior**
Blank window

cc: @amacneil @rrryanc

**Comment by amacneil** [comment]
cc @jtbandes can you have someone take a look

**Comment by foxymiles** [comment]
I'm not able to install studio on an ARM Parallels windows VM. I think somebody with a real windows install will have to take a look at this.

**Comment by jtbandes** [comment]
Seeing this error message:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/14237/206043630-a9b64d91-c952-4fe3-9f91-1b389357b052.png">
