### ISSUE TITLE
[3D] Shared geometry needs an overhaul

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4899]
The current architecture of individual `Renderable` classes exposing static methods for creating shared static geometry has a few issues. One is that static geometry is never disposed, causing references to the renderer to be held across panel instantiations. Another is that geometry should not be shared across WebGL contexts, and currently, multiple 3D panels use the same static geometry. This is probably undefined behavior.

One option is to eliminate the static member variables and have the static geometry methods instantiate new geometry each time they're called. This would mean each renderable has its own GPU allocation(s) for geometry, which would negatively impact VRAM usage and could result in a performance drop for some scenes.

Another option is a SharedGeometry class that would be instantiated and exposed as a public member of Renderer, where any Renderable can use it to lazily create and use shared geometry that is scoped to the current Renderer instance. It would need to dispose all the geometry it created when Renderer.dispose() is called.

**Comment by snosenzo** [comment]
should be fixed in #4922
