### ISSUE TITLE
Studio uses the incorrect schema name for protobuf Schema MCAP records

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4909]
**Description**

Studio data source sidebar shows the wrong schema name in the case of a disagreement between a protobuf descriptor and it's encompassing Schema record's `schema_name`.

**Steps To Reproduce**

Create an MCAP file with a protobuf Schema record using:

```
syntax = "proto3";

message foo.Bar {
  optional x string = 1;
}
```

And set the MCAP Schema record `schema_name` to `"Bar"`. Open this file in Studio and observe `foo.Bar` is shown as the schema name instead of `Bar`.

**Comment by jtbandes** [comment]
Relevant code:

https://github.com/foxglove/studio/blob/fc20bc0d271b48e7ddf6e91e1f8e1ade8f48440e/packages/mcap-support/src/parseChannel.ts#L142-L143

Perhaps the `fullSchemaName` concept can go away?

Note that there may be existing WebSocket (or MCAP) users working with Protobuf who are depending on this behavior, although we never really documented it.
