### ISSUE TITLE
Desktop Upgrade Prompt

### ISSUE THREAD

**Issue by banisadr** [foxglove/studio#4916]
* Prompt users with old version of desktop to Upgrade
* Allow users to enable auto-upgrade

**Comment by jtbandes** [comment]
- https://github.com/foxglove/studio/issues/737
- https://github.com/foxglove/studio/issues/1025

**Comment by jtbandes** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/14237/205167178-9a72cff6-5a63-4269-919b-d3269f3c352a.png">

**Comment by jtbandes** [comment]
Duplicate of #737
