### ISSUE TITLE
Remote rosbag in url gives "Unknown data source: ros1-remote-bagfile"

### ISSUE THREAD

**Issue by RileyEv** [foxglove/studio#4937]
**Description**
Since v1.34.0 remote rosbags do not open giving message "Unknown data source: ros1-remote-bagfile"

Possibly related to #4928

- Version: 1.34.0
- OS: docker - ghcr.io/foxglove/studio:1.34
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ros1-remote-bagfile

**Steps To Reproduce**
Loading bag with url, for example using the demo dataset as a rosbag https://studio.foxglove.dev/?ds=ros1-remote-bagfile&ds.url=https%3A%2F%2Fassets.foxglove.dev%2Fdemo.bag&layoutId=07c2457d-9a4d-48b1-888e-e2e21177737f

**Expected Behavior**
As like in v1.33.0 the bag should load without issue

**Actual Behavior**
In v1.34.0 the bag does not load and gives this message 
![image](https://user-images.githubusercontent.com/10366028/205934214-4c88c9c8-ee6d-470d-94bd-0531cb9e116f.png)

**Comment by jtbandes** [comment]
Thanks for the report. It seems like the url param changed, so it needs to be `ds=remote-file` now. We'll look at fixing so the old urls continue to work.

**Comment by RileyEv** [comment]
Ahh, it might be worth updating the docs to reflect and maybe a note in the release notes.

**Comment by defunctzombie** [comment]
Regressed in: https://github.com/foxglove/studio/pull/4928
