### ISSUE TITLE
Can't load panels 

### ISSUE THREAD

**Issue by iceuw** [foxglove/studio#495]
System: Windows 10
Describe: After launch program, all panels disappear after a flash
![屏幕截图 2021-04-07 121452](https://user-images.githubusercontent.com/23731407/113809523-e6ed4800-979a-11eb-9b41-0a96bf7cdd0f.png)

**Comment by amacneil** [comment]
That's very strange. Which version are you using? Can you try v0.4.0 we released today?

**Comment by iceuw** [comment]
I tried v0.4.0. And then there is nothing remains in the program window. And I tried the v0.3.0 with the Console in the Debug. It shows this error
![屏幕截图 2021-04-07 131121](https://user-images.githubusercontent.com/23731407/113813890-536c4500-97a3-11eb-81c5-89938484d134.png)

**Comment by iceuw** [comment]
And I found this file called "app.asar". But the "app.asar" is a file ranther then a directory. Is there any wrong?

**Comment by amacneil** [comment]
Ok thanks. No, the `app.asar` is just how we package the app, and those `failed to load SourceMap` warnings you see are also normal and not causing the error.

I think I have an idea what is causing this, let me get back to you with troubleshooting steps.

**Comment by thoys** [comment]
I've got the same issue myself

**Comment by amacneil** [comment]
Are either of you using a non-English language setup in Windows? We're seeing some `DWriteFont::Create` errors which might be related, but unclear what the cause of them is.
