### ISSUE TITLE
Cannot publish /clicked_point msg with ROS 1 native connection

### ISSUE THREAD

**Issue by qdhuxp** [foxglove/studio#4959]
**Description**
When connect foxglove to ROS1(noetic) with **http://xxx:11311**,  foxglove cannot publish **/clicked_point** msg to ROS Master. But if connect foxglove to ROS1(noetic) with rosbridge, it works.  In Ros master machine, you can use "**rostopic echo /clicked_point**" to monitor the received messages.

- Version: latest
- OS: Ubuntu/windows
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): **ROS 1 native**
- ROS distro (if applicable): **noetic**

**Steps To Reproduce**

1. Connect foxglove to ROS1(noetic) native with http://xxx:11311;
2. In Ros Master machine, use "rostopic echo /clicked_point" to monitor the received messages;
3. In 3D panel, use publish function to publish /clicked_point msg to ROS Master;

**Expected Behavior**
Ros master echo command should print /clicked_point messages.

**Actual Behavior**
Ros master echo command cannot print anything.

**Comment by foxymiles** [comment]
This sounds like it might be a networking issue. Can you please double check that the hostname you entered for `ROS_HOSTNAME` in this connection dialog is reachable from your ros nodes?

<img width="470" alt="Screenshot 2022-12-12 at 10 15 28 AM" src="https://user-images.githubusercontent.com/93935560/206941460-300d63db-5a55-4520-8ff1-5debdf1708c8.png">

**Comment by qdhuxp** [comment]
Thanks @foxymiles , but I am sure I use the correct ROS_HOSTNAME, otherwise, foxglove will not receive msgs from Ros master at all, right? BTW, I use ROS_IP and ROS_MASTER_URI in .bashrc to make foxglove connectable to Ros master. 
![image](https://user-images.githubusercontent.com/6842643/208358821-e10e2117-51f7-4b1f-929c-0c0b31750897.png)

**Comment by foxymiles** [comment]
Thanks for the extra information @qdhuxp . Can you please try publishing from a teleop panel and see if that works in your setup?

**Comment by jtbandes** [comment]
Closing out this ticket for now since we haven't received any further information.
