### ISSUE TITLE
Map panel only shows the last point for data converted with MessageConverter

### ISSUE THREAD

**Issue by romainreignier** [foxglove/studio#4966]
**Description**
When loading a bag file with custom GPS data and using the following custom MessageConverter extension:

```ts
import { ExtensionContext } from "@foxglove/studio";

export function activate(extensionContext: ExtensionContext): void {
  extensionContext.registerMessageConverter({
    fromSchemaName: "pheno_msgs/PhenoGpsData",
    toSchemaName: "foxglove.LocationFix",
    converter: (msg) => msg,
  });
```

(My custom `pheno_msgs/PhenoGpsData` has the same `latitude` and `longitude` fields than `foxglove.LocationFix` so the convertion is implicit)

Only the last point is drawn on the map and not all the points, as done with `sensor_msgs/NavSatFix`.

- Version: 1.34.1
- OS: Ubuntu 18.04
- Data source : ROS 1 bag file
- ROS distro : melodic

**Steps To Reproduce**

1. Install a custom extension with the above source code
2. Load a bag with custom GPS message. For example, [this one](https://github.com/foxglove/studio/files/10209855/foxglove_issue_simple.bag.gz)
3. Add the Map panel

**Expected Behavior**

All the points should be drawn, as done with `sensor_msgs/NavSatFix`:
![image](https://user-images.githubusercontent.com/8845664/207094526-4f65a087-8317-44d5-8961-f14bb795b021.png)

**Actual Behavior**
Only the last position is drawn:
![image](https://user-images.githubusercontent.com/8845664/207095199-b8cd5c92-6310-432c-81f6-2921fc60b65f.png)

**Comment by jtbandes** [comment]
Thanks for the report! Should be fixed in #4973
