### ISSUE TITLE
Unable to load local extension when org extension installed/cached

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4967]
hello again! has anyone experienced caching old code after publishing an extension, or know how I can load new local updates to an extension? Here is what I tried:
1. publish an extension to org
2. make new (local) changes to extension
3. attempt to load new local code by running `yarn local-install` + refresh Studio. (old code (version published to org) is still running when I open the [local] version)
4. try bumping `package.json` version, deleting everything in `.foxglove-studio/extensions/` , log out, quit and reopen Foxglove Studio app, and retry step 3 but changes are still not loaded
before this, yarn local-install + refresh studio had worked to reload changes, so not sure what happened, or if I’m missing a step. thank you in advance!

[Slack Message](https://foxglove.slack.com/archives/C028UEY858S/p1670873520807189?thread_ts=1670873520.807189&cid=C028UEY858S)

**Comment by defunctzombie** [comment]
FG-934

**Comment by defunctzombie** [comment]
FG-934
