### ISSUE TITLE
Expected 1 top level type definition for 'some_topic' but found 2

### ISSUE THREAD

**Issue by yairBAR-caja** [foxglove/studio#497]
Hi,

1. Love foxglove, it is awesome!
2. im having issues when connecting to my robot via websocket. when i connect and all of the nodes load foxglove shows an error:
Expected 1 top level type definition for 'BaseRecoverResult' but found 2

BaseRecoveryResult.msg is made up of a bool field and a string field. this msg is used in a result topic of an action server.

here is a screen snap:
![image](https://user-images.githubusercontent.com/71432666/113873731-be2a7a00-97bd-11eb-89a8-98e220036168.png)

anyone know whats up?

**Comment by defunctzombie** [comment]
@yairBAR-caja Do you possibly have two nodes publishing different versions of BaseRecoveryResult?

**Comment by yairBAR-caja** [comment]
Yes you were right...

The action for base recovery auto-magically generates a msg with the same.
After changing the name of my custom msg the issue is resolved.

Thanks,
YAir
