### ISSUE TITLE
Opening a layout with certain panels immediately marks the layout as "unsaved"

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4985]
I've made several layouts in studio with a variety of panels. When I switch to some of these layouts they immediately get marked as unsaved even tho I've not made any changes.

After tracing down some differences in the configs before/after here are some items which are changed:

```
map.center = undefined
map.zoomLevel = undefined
RawMessages.expansion = undefined
3D.followTf = undefined
StateTransition.isSynced = true
Plot.title = 'Plot'
```

The ideal behavior is that opening a layout does not immediately mark it as dirty.

**Comment by foxymiles** [comment]
I'm not seeing this at least with simple 1-panel layouts. Any more detailed steps to repro or a specific layout that demonstrates the issue?


https://user-images.githubusercontent.com/93935560/207973493-5d3c7dfd-4c89-43e7-bc1d-f077b029eae7.mov

**Comment by defunctzombie** [comment]
For the map panel - can you load some data and then maybe try opening the layout with and without data after having had data? Thinking about what might cause _center_ to be set vs not set.

Have you tried the 3d panel? State transition panel?

**Comment by foxymiles** [comment]
The sample layout is sort of a special case because of the way we handle it. I'll try to repro with a custom layout.

**Comment by jtbandes** [comment]
We can update the sample layout so it doesn't trigger this problem and close out this ticket.
