### ISSUE TITLE
User script changes do not update until another message arrives

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4989]
**Description**
I've created a layout with two raw message panels and a user script panel. I've written a basic user script using the default "new script" template which outputs `hello: world`. My script has one input topic and one output topic. One raw message panel is subscribed to my input topic and one to my output topic.

I now load a data source that contains messages on my input topic. I play through the data some and pause. The raw message panel shows me the expected output `hello: world`. I update the user script to change the string `world` to something else and click `save`. My output raw message panel does not update with the new message. If I start to play the output raw message panel finally updates.

**Expected Behavior**
The output raw message panel updates with the new message. I believe this behavior use to work (it does seem to work with webviz).

Maybe we've changed something in our user script panel or in our message pipeline that does not allow us to re-transmit the same "frame" again but it is worth investigating why we regressed.

**Comment by jtbandes** [comment]
It appears that webviz was triggering a backfill when variables changed in the OrderedStampPlayer:

https://github.com/cruise-automation/webviz/blob/4ed917d47e57d4286d7aa4b5c783e3f26420446e/packages/webviz-core/src/players/OrderedStampPlayer.js#L183-L188

**Comment by jtbandes** [comment]
Related: https://github.com/foxglove/studio/issues/1910
