### ISSUE TITLE
useConfirm doesn't work in dev mode

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#5041]
Double-invoke of effects in Strict Mode causes the prompt to dismiss prematurely due to this code:

https://github.com/foxglove/studio/blob/341f69488fd6fb5e4c2af969966a69fbcafdfd26/packages/studio-base/src/hooks/useConfirm.tsx#L57-L61

The same issue probably affects usePrompt.

It would be better to get rid of ModalHost and set both of these up to return an element that the caller has to render in the react tree themselves.

**Comment by foxymiles** [comment]
Do we even need that `useEffect`? I think the MUI dialog will still call `onClose` if the user closes via ESC key.

**Comment by jtbandes** [comment]
I think the original reason for adding it was to handle if the parent component unmounts without the user pressing esc.

**Comment by foxymiles** [comment]
In that case is it still important to invoke the callback?
