### ISSUE TITLE
display the topic of navigation path，it will show the type “axis” as default on the panel of 3D，expected to be of type "line"

### ISSUE THREAD

**Issue by smbera** [foxglove/studio#5169]
**Description**
When I display the topic of navigation path，it will show the type “axis” as default on the panel of 3D，expected to be of type "line".

- Version: 1.30.0-dev
- Platform: web

Here is the PR for this bug. https://github.com/foxglove/studio/pull/5170

**Steps To Reproduce**

![110](https://user-images.githubusercontent.com/23401125/213107759-67b34280-7852-4a8c-b564-4884239520f3.png)

**Expected Behavior**
![110](https://user-images.githubusercontent.com/23401125/213108134-df8177ac-94b3-41a6-98b5-cb33aac3564f.png)

**Comment by defunctzombie** [comment]
Fixed via #5170
