### ISSUE TITLE
Scene Entity Deletions Conflicting with Parallel Message Conversions

### ISSUE THREAD

**Issue by turtle-operator** [foxglove/studio#5175]
**Description**

Generally, when publishing scene updates to visualize (a lot of) scene entities in the 3D panel, one has to also do some cleaning up in terms of publishing scene entity deletions, as otherwise entities which are not present in the scene anymore would still be visualized (using the `lifetime` attribute is considered to be inaccurate for this purpose in some use cases, since during the creation of the scene entity the future lifetime of that entity might not be known).

To do the cleaning up, there seem to be two potentially viable approaches:
1. Keep track of scene entities over conversion cycles and remove entities which do not exist anymore in new update cycles (`SceneEntityDeletionType.MATCHING_ID`).
2. Re-generate all scene entities on every update (i.e., delete all via `SceneEntityDeletionType.ALL` and add some new).

Well, the second approach is not doable with the current version of Foxglove Studio, because first new scene entities are handled, and only afterwards it is taken care of the scene entity deletions. That means, all added scene entities are directly deleted again in the same cycle (see [here](https://github.com/foxglove/studio/blob/5e819eaf8095f55fbf366643c9be2d64f52c71a5/packages/studio-base/src/panels/ThreeDeeRender/renderables/SceneEntities.ts#L135-L155)).

The first approach however seems to also not be doable, since when using a message converter extension with multiple topics of the same message type to be converted in parallel, static variables seem not to be instantiated per topic type, but rather there exists only a single instance of the message converter doing the conversion for multiple topics. Since it is likely (or at least hard to be avoided) that scene entities generated from the different topics have the same ID, the book keeping is not safely possible.

- Version: 1.37.0
- Platform: -

**Steps To Reproduce**

```
import {ExtensionContext} from "@foxglove/studio";
import type {SceneEntity, SceneEntityDeletion} from "@foxglove/schemas";

let LAST_SCENE_ENTITY_IDS = new Set<string>([]);

// ...

function buildSceneEntityDeletions(scene_entities: SceneEntity[]): SceneEntityDeletion[] {
  let current_scene_entity_ids = new Set(scene_entities.map(e => {
    return e.id;
  }));

  // find scene entity IDs that are not updated anymore
  let obsolete_scene_entity_ids = [...LAST_SCENE_ENTITY_IDS].filter(e => {
    return !current_scene_entity_ids.has(e)
  })

  return obsolete_scene_entity_ids.map(id => {
    return {
      timestamp: {sec: 0, nsec: 0},
      type: SceneEntityDeletionType.MATCHING_ID,
      id: id,
    }
  });
}

function rememberSceneEntityIDs(scene_entities: PartialSceneEntity[]): void {
  LAST_SCENE_ENTITY_IDS = new Set(scene_entities.map(e => {
    return e.id;
  }));
}

export function activate(extensionContext: ExtensionContext): void {
  extensionContext.registerMessageConverter({
    fromSchemaName: "custom_msgs/MyCustomMsg",
    toSchemaName: "foxglove.SceneUpdate",
    converter: (message: Message) => {

      // build some scene entities
      let scene_entities: SceneEntity[] = [];
      // ...

      // remove obsolete scene entities
      let scene_entity_deletions = buildSceneEntityDeletions(scene_entities);
      rememberSceneEntityIDs(scene_entities);

      return {
        deletions: scene_entity_deletions,
        entities: scene_entities,
      };
    }
  });
}
```

**Expected Behavior**

1. Any message converter extension is instantiated per topic and thus conversion cycles of different topics of the same type do not interfere with each other.
2. Scene entity deletions are handled before new scene entities are added.

... or am I getting something wrong?

**Comment by jtbandes** [comment]
👍 #2 makes sense. Created a PR: https://github.com/foxglove/studio/pull/5176
