### ISSUE TITLE
Plots titles resets when saving layout

### ISSUE THREAD

**Issue by iftahnaf** [foxglove/studio#5262]
**Description**
When saving shared layout, the plot titles resets to default (`Plot`).

- Version: 1.39.0
- Platform: Ubuntu 22.04

**Steps To Reproduce**
1. Set `Title` to the `Plot` panel.
2. Save the organization layout.
3. The `Title` resets.

**Expected Behavior**
The title should not be reset after saving the layout.

**Comment by snosenzo** [comment]
should be fixed in: https://github.com/foxglove/studio/pull/5282
