### ISSUE TITLE
Tried to use PanelContext outside a <PanelContext.Provider />

### ISSUE THREAD

**Issue by ShuoShenDe** [foxglove/studio#5278]
**Description**
Tried to use PanelContext outside a <PanelContext.Provider />
When I clone the repository from github and run `yarn web:serve:local`, and the wesite gives the error as follows
![image](https://user-images.githubusercontent.com/31400000/216094911-315dd09c-6d81-4532-8b6c-387333d881c8.png)

- Version: latest
- Platform: windows

**Steps To Reproduce**

1. Clone repo
2. Run `corepack enable` and `yarn install`
3. Launch the development environment:
4. Run `yarn web:serve:local`

**Expected Behavior**
It seems like the error of code, please check them.
![image](https://user-images.githubusercontent.com/31400000/216095839-ab970581-37e7-49ca-833a-f1e9c0644fec.png)

**Comment by RomainLLC** [comment]
Could you update .deb packages so the issue is solved also with precompiled Foxglove ?

Thanks !
