### ISSUE TITLE
unable to detect topics published through unicast

### ISSUE THREAD

**Issue by FrankBu0616** [foxglove/studio#5291]
Hi, thank you for making this amazing visualization software for ROS.

I am running into this interesting issue when I turned off multicast on my host machine.
On my host machine, I turned off multi-cast and enabled unicast as instructed [here](https://iroboteducation.github.io/create3_docs/setup/xml-config/). 
![foxglove_issue](https://user-images.githubusercontent.com/20778137/216723170-115f91cb-d3a9-4962-95de-ecf30264e2b0.png)

On my client machine, I can receive published messages from my host machine in terminal, but it is not shown in foxglove studio. 

I am using ROS 2 humble with Fast-DDS. Thank you for your help.

**Comment by jtbandes** [comment]
Please try out the [Foxglove Bridge](https://github.com/foxglove/ros-foxglove-bridge) for your ROS 2 connection. The native connection is now deprecated (https://github.com/foxglove/studio/pull/5017).
