### ISSUE TITLE
User script panel resets cursor to start of editor

### ISSUE THREAD

**Issue by vivek-rane** [foxglove/studio#5303]
**Description**
After switching to a new script if I delete something, the cursor gets reset to the start of the script. See attached video for details.

- Version: `1.39.1 (darwin)`
- Platform: `MacOS Monterey 12.5.1` on Apple M1 Max

**Steps To Reproduce**

1. Create 2 new user scripts
2. Switch to a different script
3. Delete something
The cursor resets to the beginning of the file

**Expected Behavior**
Cursor stays where it is.

https://user-images.githubusercontent.com/25373098/217401006-4001c6f1-c70e-4b16-8c7a-c724f83046db.mov

**Comment by foxymiles** [comment]
Note - this seems to be reproducible on current studio.foxglove.dev as well.
