### ISSUE TITLE
Last seen image marker persists when turned off during playback

### ISSUE THREAD

**Issue by vivek-rane** [foxglove/studio#5371]
**Description**
When a 2D image marker is turned off during playback, the last seen marker continues to be drawn on the screen. This finally disappears when the marker is turned back on. This does not happen if the playback is paused.

- Version: 1.39.1 (darwin)
- Platform: macOS Monterey (12.5.1)

**Steps To Reproduce**
1. Download the test mcap from https://github.com/foxglove/mcap/blob/main/testdata/mcap/demo.mcap
2. Add the following user script:
```
import { Input, Message } from "./types";

export const inputs = ["/image_color/compressed"];
export const output = "test marker";

type ImageMarker = Message<"foxglove.ImageAnnotations">;

var color_val = { r: 1, g: 0, b: 0.5, a: 1 };

export default function node(
  event: Input<"/image_color/compressed">
): ImageMarker {
  return {
    circles: [
      {
        timestamp: event.receiveTime,
        thickness: 2,
        position: { x: (event.message.header.seq - 100) * 10, y: 300 },
        outline_color: color_val,
        fill_color: color_val,
        diameter: 100,
      },
    ],
    points: [],
  };
}
```
3. Open an image panel and point it to `/image_color/compressed`
4. Turn on the marker called "test marker" from our script
5. Start playback, and turn the marker off. The marker will continue to be displayed in the position it was when turned off.
6. Turning the marker back on will update it to the right place.

**Expected Behavior**
When marker is turned off, it should disappear from the image.

https://user-images.githubusercontent.com/25373098/218605788-5686b20c-a94e-40e8-8029-ec6b8ca4985a.mov

**Comment by defunctzombie** [comment]
@vivek-rane We've transferred this issue to the Studio repo as this is a studio bug not an mcap bug.
