### ISSUE TITLE
ros1 map (occupancyGrid data) can not updated when its TF changed

### ISSUE THREAD

**Issue by YunxianHua** [foxglove/studio#5394]
**Description**
The ROSBAG contains two frames of MAP data. After the first frame of MAP is received, the TF changes, but the MAP did not update with the TF until the second frame of MAP is received.
In RVIZ, MAP can be updated with TF changes

bag file download link: https://drive.google.com/file/d/1HZZMf2H-v4xFRxnlbJzktK4I2Ns_isUH/view?usp=sharing
map data arrived in 1676540920 (first frame), 1676541119 (second frame)
TF changed in 1676540922

- Version: foxglove studio 1.40.0, also happened in online web
- Platform: Ubuntu 20.04

**Steps To Reproduce**

**Expected Behavior**
  the map will be update after TF changed

**Comment by jtbandes** [comment]
Hi, thanks for the report. I think you can get your desired behavior by changing the "Frame Lock" setting to "on".

Currently, the frame lock setting is hidden unless the "color mode" setting is set to "custom". This is a bug which we'll fix asap.

https://user-images.githubusercontent.com/14237/220451296-25f8af59-1f75-4fd8-86f6-78e42ff73a6c.mov
