### ISSUE TITLE
Tiny Dropdown UI for adding topics

### ISSUE THREAD

**Issue by antrose99** [foxglove/studio#5396]
**Description**
When adding new topics to a plot window the UI for the drop down is very small and only shows 2 or 3 options. It is also impossible to scroll further down and expose more of the options. It would be nice to be able to scroll further down below the current topics to expose more of the options. See example:
![image](https://user-images.githubusercontent.com/93656450/219869625-b71d2db5-5a7e-4cee-a6ea-7d1ebaa73699.png)

If I instead add a bunch of empty topics below it gets much easier to choose the appropriate topics:
![image](https://user-images.githubusercontent.com/93656450/219869668-9a23ce38-db8e-4880-aca5-9d43746b0383.png)

- Version: 1.40.0
- Platform: Linux (amd64)

**Steps To Reproduce**
1. Open an MCAP file
2. Add plot panel
3. Add topics until it fills settings screen
4. Add a new topic and try to scroll in the drop down

**Expected Behavior**
A way to increase the drop down to easier be able to choose the topics you want to add. The older version of foxglove where the topics where added in the legend of the plot were great for this.

**Comment by foxymiles** [comment]
Closed by https://github.com/foxglove/studio/pull/5609

The menu placement logic is better now and will put it above the autocomplete if near the bottom of the screen.
