### ISSUE TITLE
3D panel image rendering reduces app frame rate compared to Image panel

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#5398]
**Description**

The Image panel and 3D panel both use `@foxglove/den/image/decodings` to convert binary blobs into renderable image data, but the image panel runs these methods on a web worker while the 3D panel runs on the main thread. This can cause significant app slowdown when rendering an image format not natively supported by the browser.

**Comment by defunctzombie** [comment]
We have our internal feature ticket tracking potential improvements to rendering. The 3d panel renders on the main thread by design.
