### ISSUE TITLE
3D panel selection rendering issues

### ISSUE THREAD

**Issue by harip3rla** [foxglove/studio#5426]
**Description**
In the 3D panel window of Foxglove studio when the user selects an object to view it's properties, the 3D panel/view goes blank. Only way to bring it back is to switch to a different layout/panel and return to the 3D panel

- Version:1.42
- Platform: Studio

**Steps To Reproduce**

**Expected Behavior**
When selecting an object in the 3D panel, the object properties should be displayed and the screen should not go blank

**Comment by jtbandes** [comment]
Thanks for the report. This regression seems to have been caused by https://github.com/foxglove/studio/pull/5045.
