### ISSUE TITLE
non verbose error message on opening an mcap fros2 bag without permissions

### ISSUE THREAD

**Issue by fnobis** [foxglove/studio#5471]
Opening a db3 ros2 bag with root permissions as a standard user gives the following error message:
`Error initializing: abort(NotReadableError: Failed to execute 'readAsArrayBuffer' on 'FileReaderSync': The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.). Build with -s ASSERTIONS=1 for more info.`

Opening an mcp ros2 bag with root permissions as a standard user gives the following error message:
`Error initializing: network error`

The mcap error message makes it hard to narrow down the problem to a file permission problem. 

**Steps To Reproduce**

- Take any bag and apply `sudo chown root BAGFILE`
- Open file the in foxglove

foxglove studio version:
v1.42.1

**Expected Behavior**
Verbose error message

**Comment by jtbandes** [comment]
Thanks for reporting this. A fix is now live on studio.foxglove.dev and will be in the next release.
