### ISSUE TITLE
No Plotting of Signals at Player Time When Buffer is Full

### ISSUE THREAD

**Issue by turtle-operator** [foxglove/studio#5500]
**Description**

The Plot panel does not load data for the current player time if the buffer is full. Thus, for large data files, there will never be data plotted starting at the time when the buffer reached its limits.

I think a change (in my opinion a regression) was introduced with https://github.com/foxglove/studio/pull/5212. Seems like [this issue](https://github.com/foxglove/studio/pull/5212#issuecomment-1402494604) has not eventually been correctly addressed.

- Version: 1.42.1
- Platform: Web
- Data source format: rosbag

**Steps To Reproduce**

Load a large data file in the web version of Foxglove Studio and add a Plot panel for an arbitrary signal.

**Expected Behavior**

The Plot panel always plots the required data around the current player time, potentially removing any "irrelevant" data (i.e., data far from the current player time) when the buffer reaches its limit.

![image](https://user-images.githubusercontent.com/109816930/223358125-a0e51d04-26b6-44c1-a5dd-8ee110399e67.png)

**Comment by defunctzombie** [comment]
For panels which need to preload data we only have one set of logic and caching that handles all preloaded topics. This is true for preloading data for plots as well as preloading data for transform messages in the 3d panel. These different use-cases are sometimes at odds with each other - for example in the old logic when we had to evict data from preloading this would sometimes evict transforms the 3d panel needs. It would also sometimes cause plots to change from under you as you go through the data.

Another downside of the previous approach was that it would buffer from the current time to the end and then resume from the start which might result in missing plot data right _before_ a time you want to seek to. Arguably, if you know this behavior you can re-seek to an earlier time to re-buffer so there was an out that does not exist now.

Ultimately the answer to what is "irrelevant" data is not an easy one and so for now we've settled on an approach that is easier to reason about: "preload from the start until you fill up your buffer". Where I do think we need to be better is messaging when the buffer is full (something that is maybe not obvious today). We do revisit such changes and if we are able to come up with a strategy that balances the needs of 3d transform preloading with other panels we might change our approach.

> Also, I think it is quite annoying to have to wait until all data from the beginning of the file is loaded, even when directly jumping to a later point of the time series data.

This depends on the data source - for some data sources like our data platform we have separate paths for preloaded data which loads quicker.

**Comment by defunctzombie** [comment]
Notes: https://github.com/foxglove/studio/blob/main/packages/studio-base/src/panels/Plot/index.tsx#L388-L389

These lines prevent any active data from being used when preloaded data is available.

**Comment by foxymiles** [comment]
Closing after fix in #5694. You can now playback sections of the file with nothing plotted to load more messages.
