### ISSUE TITLE
How to hide this yellow line？

### ISSUE THREAD

**Issue by 263868161** [foxglove/studio#5538]
**Description**

How to hide this yellow line？

- Version:1.43.1
![image](https://user-images.githubusercontent.com/20036253/224518854-7e56234f-4d45-4fcd-ba5b-aaa1637a76fc.png)

**Comment by foxymiles** [comment]
You can turn these on and off with the visibility icons in the panel settings under `Transforms`:

https://user-images.githubusercontent.com/93935560/224578544-b761105b-226d-42e4-93c5-216d25f8202c.mov
