### ISSUE TITLE
A very big value of a uint64 / int64 field in a protobuf message of a mcap file will be parsed to a fault value.

### ISSUE THREAD

**Issue by lizhucheng** [foxglove/studio#5577]
**Description**
a uint64 field in a proto will be parsed to fault value when  the value is big;
e.g. 2394304762687298819 -> 2394304762687299000

- Version: all
- Platform: all system, browser

**Steps To Reproduce**
1. create a proto file  declare a uint64 field;
test.proto
 message Test {
   uint64 a = 1;
}
2. write a messge to a pb file, let the value of the field to be  2394304762687298819;
3. create a mcap file which contains pb data and schema above;
4. play the mcap file in foxglove studio.
5. check the message in a raw panel.
6. 2394304762687298819 -> 2394304762687299000

**Expected Behavior**
2394304762687298819 -> 2394304762687298819

[Related articles](https://github.com/protobufjs/protobuf.js/issues/1838)

**Comment by defunctzombie** [comment]
Can you please provide a sample file where you experience this issue. That will help us make sure we are looking at the same type of data you are.

**Comment by jtbandes** [comment]
Hi @lizhucheng, please try out this version of the app https://studio-j53ommwbi.foxglove.party/ (from #5727) and let me know if it works for you.

**Comment by lizhucheng** [comment]
> Hi @lizhucheng, please try out this version of the app https://studio-j53ommwbi.foxglove.party/ (from #5727) and let me know if it works for you.

Yes，it works for me. Good job and Many thanks.
