### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by namrata-jangid** [foxglove/studio#5591]
Hi, 

Our team (@kis-balazs) is having an issue with running Foxglove Studio on an Ubuntu 20.04 machine. We had opened an issue previously as well (https://github.com/foxglove/studio/issues/5564).

Attaching a few screenshots to further elaborate on the issue:

- Ubuntu version:
![ubuntu_version](https://user-images.githubusercontent.com/128360488/226284868-ccda728a-bb86-426b-937a-e7f3b8f78a79.png)

- Installing Foxglove Studio:
![install_foxglove](https://user-images.githubusercontent.com/128360488/226284920-51a22133-cafa-4be0-835d-7ad16d998d52.png)

- 'foxglove-studio' command does not run as expected:
![foxglove_command](https://user-images.githubusercontent.com/128360488/226285257-6b260588-8c02-4631-ba0e-84db59652bab.png)

Requesting your help on this. 

Thank you! :)

**Comment by jtbandes** [comment]
We're going to need more information to be able to help. The app works fine with my ubuntu 20.04 VM on arm64. Do you get any error messages?

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/14237/226421740-9323c326-c4f4-49f2-8c26-78cfe174294d.png">

**Comment by kis-balazs** [comment]
Hi!
Weird thing is exactly what you asked, there is nothing popping up as an error, and neither ```htop``` shows any significant move regarding a "foxglove-studio" executable (see last image)

We are running it on a Jetson Xavier, with JetPack 5.0.2, Ubuntu 20.04 as specified in the initial image. Can maybe this trigger such unusual behavior?

How could we figure this out better?

Thanks,
 Balazs

**Comment by jtbandes** [comment]
Are you able to run other apps built with Electron? https://github.com/electron/electron  You could also try https://www.electronjs.org/fiddle/. It sounds like there are some more logs you can enable as well: https://www.electronjs.org/docs/latest/api/command-line-switches#--enable-loggingfile

**Comment by kis-balazs** [comment]
Hi there!
We have run fiddle, and it has the same behavior, even though it shows up in the htop window, as being present... very weird behavior, and I believe it is an electron-related issue in this case. Do you have any idea how to solution this?
Please see screenshots below.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/25155919/227157746-34b3cc49-ca7f-4acc-aaa5-95c1b3eaa940.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25155919/227157752-ce80cecc-9c97-4ea4-b312-a41c2238f96a.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/25155919/227157757-ccc00214-a0f4-426f-a24e-59d5ff64945d.png)
low.

**Comment by jtbandes** [comment]
Sorry, I've never experienced this problem before. I don't have any particular advice other than to search through the electron community to see if others have experienced this problem. I'm going to close this issue because we've determined the bug is not related to Foxglove Studio, but feel free to post further updates and we can reopen it if anything changes.

**Comment by kis-balazs** [comment]
Yeah well this wasn't useful. Then please take out the arm64 support from the foxglove website until the error gets solved, since you are in fact, not supporting arm64 architecture fully :)

**Comment by jtbandes** [comment]
Did you try running with `--enable-logging`? Any interesting log messages? https://www.electronjs.org/docs/latest/api/command-line-switches#--enable-loggingfile
