### ISSUE TITLE
`Cannot read properties of undefined (reading 'name')`

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#5646]
"load a geojson multipolygon that does not have custom properties"

[Slack Message](https://foxglove.slack.com/archives/C028UEY858S/p1680023075521009?thread_ts=1680023075.521009&cid=C028UEY858S)

Fix: https://github.com/MetaverseIndustries/sviz/commit/78134e12f928e6fe4e07dee3045cd70e62cae984

**Comment by foxymiles** [comment]
Fixed by https://github.com/foxglove/studio/pull/5648
