### ISSUE TITLE
Cannot double-click to open a bag file

### ISSUE THREAD

**Issue by ACE-830** [foxglove/studio#5690]
**Description**
In the latest version 1.47.0, double-clicking a .bag file only opens the Studio and it does not open the file, whether when the Studio is already open or closed.

- Version: Latest
- Platform: Ubuntu, Windows
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): bag

**Comment by jtbandes** [comment]
Thanks for reporting! This is fixed in https://github.com/foxglove/studio/pull/5693
