### ISSUE TITLE
Incorrect error message for corrupt MCAP file

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#5733]
**Description**

Trying to load an MCAP file that has not been properly closed, I see the problem reported as "Unable to stream MCAP file; too large" which is odd since the file is not very large. Opening the dev console, I can see the actual error was caught and logged to console but the file too large error is what appeared in the UI.

- Version: `main`
- Platform: Windows
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): MCAP local file

**Steps To Reproduce**

1. Open an MCAP where some amount of the end of the file has been sliced off.

![Screenshot 2023-04-08 115115](https://user-images.githubusercontent.com/195374/230738200-840b81a5-ad6e-40fe-92bb-c6649396126e.jpg)

**Comment by wimagguc** [comment]
As it turns out, this error was displayed because the file is indeed too large. The `McapStreamingIterableSource` provider has a limit of 1GB as per its comment:

> This provider uses a simple approach of loading everything into memory up front, so we can't handle large files
