### ISSUE TITLE
[3D] The default scale of foxglove.PosesInFrame is shown as `3`, but is actually much smaller

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#5755]
**Description**

Open an MCAP with a `foxglove.PosesInFrame` topic and visualize in the 3D panel. The settings sidebar shows it has a scale of `3`, but the actual rendered size is much smaller (1?). Type in `3` and you can see the scale increase. Remove the typed in `3`, replacing it with a default value `3` and observe the scale decrease.

**Comment by foxymiles** [comment]
Do you have a sample mcap that demonstrates this? When I use nuscenes and a converter screen from `/pose` the default scale is 0.2 which seems to correspond with what's actually being rendered.

<img width="1266" alt="Screenshot 2023-04-24 at 7 03 53 AM" src="https://user-images.githubusercontent.com/93935560/233873896-8d7e4409-ee62-4f19-9159-30ec41dc6d1f.png">

**Comment by snosenzo** [comment]
@foxymiles John mentioned the issue is with `foxglove.PosesInFrame` not `foxglove.PoseInFrame` (singular). It looks like your convert script outputs a `PoseInFrame`, which would be why your repro isn't showing the issue.

**Comment by foxymiles** [comment]
> @foxymiles John mentioned the issue is with `foxglove.PosesInFrame` not `foxglove.PoseInFrame` (singular). It looks like your convert script outputs a `PoseInFrame`, which would be why your repro isn't showing the issue.

Thanks I misread that.
