### ISSUE TITLE
Incorrect visualization when plotting data with the `[:]` accessor

### ISSUE THREAD

**Issue by vhwanger** [foxglove/studio#5862]
**Description**
I have data of the form:

```
  1 syntax = "proto3";
  2
  3
  4 message ThreeTuple {
  5     float a = 1;
  6     float b = 2;
  7     float c = 3;
  8 }
  9 message DataCollection {
 10     repeated ThreeTuple data = 1;
 11 }
```

When I try and plot `/data.data[:].a` with the X-axis value using `Index` and I scrub around, the plot seemingly starts accumulating all the lines over the times I scrub over. The expected behavior is that it only plots the lines over the current timestamp of the log

![image](https://user-images.githubusercontent.com/2358630/235008675-eb3bf54f-56eb-4255-b288-78079e711faa.png)

- Version: 1.51.0
- Platform: Mac
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
mcap file

**Expected Behavior**
The expected behavior is shown below.
<img width="767" alt="Screenshot 2023-04-27 at 4 02 02 PM" src="https://user-images.githubusercontent.com/2358630/235008736-a005fd2d-2a4c-43e9-8da6-1dddaf0e7055.png">

**Comment by vhwanger** [comment]
I have a layout and an mcap available for reproducing if needed.

**Comment by foxymiles** [comment]
Thanks for the detailed bug report. I'm seeing some strange behavior too but a bit different from what you describe. Does what you're seeing resemble this?

https://user-images.githubusercontent.com/93935560/235024939-8d47b596-1586-45b7-b9ea-52455ca3a1bf.mov

**Comment by vhwanger** [comment]
That's actually what the data looks like. Now if you scrub back and forth in the window, does it look the same?

**Comment by foxymiles** [comment]
Yes I see what you mean. Scrubbing on the timeline back and forth results in these lines accumulating like this.

**Comment by foxymiles** [comment]
@vhwanger Could you please try the deployment from this PR: https://github.com/foxglove/studio/pull/5868 and see if it fixes your problem? You can try it here: https://studio-8uik5ytns.foxglove.party/

**Comment by vhwanger** [comment]
This looks like it fixes it on my fake data file, thank you so much! I'll have to wait for the desktop deployment to try it on the actual log I have.

**Comment by foxymiles** [comment]
Looks like I inadvertently broke this as part of recent optimization work.
