### ISSUE TITLE
Constant error when connected to wifi without internet

### ISSUE THREAD

**Issue by bertaveira** [foxglove/studio#6062]
**Description**
We connect to our robots wifi where we use Foxglove Bridge. The problem is that this wifi does not have an internet connection. Because of this I get a constant error like this:
<img width="909" alt="image" src="https://github.com/foxglove/studio/assets/9644729/2e200ba0-df0f-4ee3-936c-866fe6b732b9">

It becomes quite disturbing to have to close it every few seconds

- Version: 1.53.1
- Platform: MacOS
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Foxglove Rosbridge

**Comment by foxymiles** [comment]
Handing off to @2metres for UX inspiration here.

**Comment by 2metres** [comment]
I think we should persistant errors into the Problems sidebar instead of pushing to a toast

**Comment by foxymiles** [comment]
These will show up as items in the problems sidebar instead of as a snackbar in the next studio release.
