### ISSUE TITLE
Char arrays not displaying properly

### ISSUE THREAD

**Issue by viveksood97** [foxglove/studio#6169]
**Description**
Char arrays are being processed and displayed as uint8 arrays Check the name field
![image](https://github.com/foxglove/studio/assets/48154838/61fa53ce-6107-408f-9276-a29e5a851bb7)

Echoing the topic in CLI displays the same field correctly. Check the name field
![image](https://github.com/foxglove/studio/assets/48154838/59b510b7-cc2b-4573-8d94-70a205a59d6a)

- Version:
- Platform:
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

**Expected Behavior**
Display char arrays as char arrays

**Comment by defunctzombie** [comment]
Please clarify what you mean by "char arrays"? Which serialization format are you using? What does your message schema/definition look like?

**Comment by jtbandes** [comment]
Please remember to fill out all fields of the issue template when filing a new issue.

**Comment by viveksood97** [comment]
@defunctzombie 
1. By char arrays I mean: 
```
# Task (abbreviated) name, including null termination character
char[6] name
```
2. I am not sure about the serialization format. If you could shed a little bit more light on how to figure that out, I'd be happy to provide that information.
3. Here's the output of rosmsg show:
![image](https://github.com/foxglove/studio/assets/48154838/0d586646-f374-4d3e-a9be-b58a1f4f2c8a)

**Comment by jtbandes** [comment]
According to http://wiki.ros.org/msg, `char` is a "deprecated alias for uint8". This is why the app displays `char[]` as a Uint8Array. Generally, arrays of uint8 values may not form a valid string. For strings, use the `string` primitive type.

**Comment by viveksood97** [comment]
Closing the issue, thanks!!
