### ISSUE TITLE
The plot render two frame data once

### ISSUE THREAD

**Issue by zhangfei56** [foxglove/studio#6264]
The X Axis I choose Index.
The Message path I set one array data: speedPoint[:].a

Then I Seek backward and forward more then once, the  plot may be render two frame data once.

![plot_index_error](https://github.com/foxglove/studio/assets/4465548/59ed9abd-ecb8-4396-a8a2-7e42169ba418)

**Comment by foxymiles** [comment]
Is it possible for you to share a sample data file that demonstrates the issue?

**Comment by foxymiles** [comment]
So far I haven't been able to reproduce this with test data here. Could you please try this again on studio.foxglove.dev and see if the problem persists? If so could you please also provide some test data to reproduce the issue?

**Comment by foxymiles** [comment]
I haven't been able to reproduce this so I'm going to close it. I'm happy to reopen it if you can provide more detailed reproduction steps.
