### ISSUE TITLE
Is this a mistake? there is no uyuy, does it mean uyvy?

### ISSUE THREAD

**Issue by sgf201** [foxglove/studio#6271]
**Description**
![image](https://github.com/foxglove/studio/assets/5253415/c4dfbf19-f335-47fc-814e-917e262a966c)
Is this a mistake? there is no uyuy, does it mean uyvy?

- Version:
- Platform:
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

**Expected Behavior**
uyvy

**Comment by sgf201** [comment]
https://foxglove.dev/docs/studio/panels/image

**Comment by jtbandes** [comment]
Thanks for raising this issue!
