### ISSUE TITLE
Unable to Select Colour Using Keyboard

### ISSUE THREAD

**Issue by camchambers** [foxglove/studio#6275]
**Description**
Typing a hex colour in the colour picker and pressing enter does not select the colour. 

![color-selection](https://github.com/foxglove/studio/assets/26011644/cd06649c-1be1-493e-8d2f-ed8e9e2668be)

- Version:  1.54.0
- Platform: Ubuntu Linux
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): rosbridge

**Steps To Reproduce**
- Configure a topic containing a colour picker
- Enter a hex value into the colour field
- Press enter

**Expected Behavior**
- The colour entered is updated in the UI

**Comment by jtbandes** [comment]
Hi, I believe this is happening because the color picker requires 8 digits, `#RRGGBBAA`. However, I agree that it should be possible to enter 6 values and automatically set the alpha to FF.

**Comment by camchambers** [comment]
Right. The field requires an alpha value (suggested by the placeholder value). Defaulting the alpha would be a nice feature.

**Comment by foxymiles** [comment]
I'm going to reclassify this as an enhancement request.

**Comment by camchambers** [comment]
Absolutely.
