### ISSUE TITLE
Same problem as in #5877

### ISSUE THREAD

**Issue by caro-merz** [foxglove/studio#6398]
i have the same problem as mentioned in #5877.

The indicator panel always takes the "Otherwise" rule. 

- Version: 1.60.2
- Platform: Studio
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): foxglove bridge / ROS1

![image](https://github.com/foxglove/studio/assets/129984192/c8d6abbc-c7a3-444b-ae3c-9945eda82c3c)

**Comment by jtbandes** [comment]
You need to use /prediction.data as the message path, not just /prediction.
