### ISSUE TITLE
Log names have a newline character in them

### ISSUE THREAD

**Issue by MattOslin** [foxglove/studio#6403]
**Description**

Highlighting/copying the log name text always results in a newline character in the middle of the name, even though the logname is a filename with no newline character in it.

This behavior existed in previous versions of studio as well, for the log name in the left hand side panel. The log name in the titlebar on the latest foxglove has the same issue.

<img width="287" alt="Screenshot 2023-07-07 at 11 19 26 AM" src="https://github.com/foxglove/studio/assets/16124164/6144c63e-9067-4cb0-9d42-9e2b13feef53">

- Version: 1.58.0
- Platform: osx
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

Load an mcap file, select name in title, copy, paste

**Expected Behavior** 
name should paste exactly as the filename that was loaded

**Comment by foxymiles** [comment]
I can reproduce this here. Working on a fix.
