### ISSUE TITLE
Mesh Error

### ISSUE THREAD

**Issue by cody-sheff** [foxglove/studio#6519]
**Description**

- Version: 1.62+
- Platform: Ubuntu 20
- Data source: MCAP file/websocket

**Steps To Reproduce**
We've been sending geometry messages using ROS Markers that have a path to a local mesh. As of 1.62, Foxglove is consistently registering those filepaths as non-existant. To reproduce, send ROS marker messages with the mesh filename as a path to a local file. You may need to send several different meshes; it seems to *sometimes* work, but not consistently.

**Expected Behavior**
ROS Marker messages with a local filepath will be usable in Foxglove. We've verified that 1.62+ is what breaks this; rolling back to 1.61.1 restores functionality.

**Comment by achim-k** [comment]
>  To reproduce, send ROS marker messages with the mesh filename as a path to a local file.

What do you mean with a path to a local file? `file://` or `package://` ?

Are you using Studio Desktop? Could share a MCAP file to reproduce this issue?

**Comment by achim-k** [comment]
> Just a standard filepath, `/path/to/local/mesh.dae` style. Is the `file://` prefix needed now?

Pretty sure it works with the `file://` prefix, but let me check. If it worked before without it, then that's clearly a regression

**Comment by cody-sheff** [comment]
Looks like adding the `file://` prefix does work!

**Comment by achim-k** [comment]
> Looks like adding the `file://` prefix does work!

I recommend to use that from now on. I have submitted #6522 to restore the original behavior, but using a valid url (e.g. `file://`) is definitely more future proof.

**Comment by achim-k** [comment]
> > Looks like adding the `file://` prefix does work!
> 
> I recommend to use that from now on. I have submitted #6522 to restore the original behavior, but using a valid url (e.g. `file://`) is definitely more future proof.

Update: We agreed to not support invalid URIs, so you will have to add the `file://` prefix from now on. Mesh resources have to be referenced by a valid URL, see also https://wiki.ros.org/rviz/DisplayTypes/Marker#Mesh_Resource_.28MESH_RESOURCE.3D10.29_.5B1.1.2B-.5D:

> The format is the URI-form used by [resource_retriever](https://wiki.ros.org/resource_retriever), including the package:// syntax.
