### ISSUE TITLE
Unable to save extension panel changes to layout

### ISSUE THREAD

**Issue by rcarnemollaBE** [foxglove/studio#6606]
**Description**
I am using the service panel example from the below repository and I am unable to save changes made to the extension panel. Service name and data won't appear when closing and reopening my layout.

- Version: 1.63.0
- Platform: Ubuntu 
- Data source rosbridge, ROS 2 humble:

**Steps To Reproduce**
Installed extension, opened studio, added service call panel, set service name, saved, closed, reopened, saved configuration not there

**Expected Behavior**
Expected saved layout to persist.

**Comment by jtbandes** [comment]
You didn't provide a link, but are you talking about [this example code](https://github.com/foxglove/create-foxglove-extension/blob/main/examples/call-service-panel-example/src/CallServicePanel.tsx)? The code does not make any attempt to save changes to the layout. You would need to use the [`context.saveState`](https://foxglove.dev/docs/studio/extensions/panel-api#savestate) method to save state.
