### ISSUE TITLE
3D panel stopped working: THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

### ISSUE THREAD

**Issue by jplapp** [foxglove/studio#6617]
**Description**
3d panel not working, error THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

- Version: I tried 1.60.2 , 1.62, 1.63, 1.65
- Platform: ubuntu 22
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): any rosbag I tried

**Steps To Reproduce**
Open any rosbag
Open 3d panel
-> no 3d shown
-> errors in logs 
![image](https://github.com/foxglove/studio/assets/17068999/117cf6b5-cd7f-40f0-a5b7-67e67e959b2a)

**Expected Behavior**
3d shown

**Comment by jtbandes** [comment]
> any rosbag I tried

This isn't really enough information for us to be able to reproduce this issue. Could you provide more details?

**Comment by jtbandes** [comment]
Going to close out this ticket since we haven't gotten any response, but feel free to comment with more details and we can reopen it.
