### ISSUE TITLE
v1.66 freezes after a few seconds - ubuntu 22.04

### ISSUE THREAD

**Issue by iftahnaf** [foxglove/studio#6654]
**Description**
the app freezes a few seconds after booting.

- Version: 1.66
- Platform: ubuntu 22.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): main app

**Steps To Reproduce**
```
$foxglove-studio
initializing Sentry in main
Foxglove Studio 1.66.0
Could not set app as handler for foxglove://
Elapsed (ms) until new StudioWindow: 58
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
New Foxglove Studio window 1
Starting update loop
window.loadURL(file:///opt/Foxglove Studio/resources/app.asar/renderer/index.html)
[22780:0816/101836.753213:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
load-pending-files
injectFilesToOpen: no files - skipping
[22780:0816/101837.177342:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
window URL loaded
[22780:0816/101837.204880:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

**Comment by achim-k** [comment]
> the app freezes a few seconds after booting.

It freezes without you loading any mcap/bag file or connecting to a live data?

Is this a snap install or from apt?

**Comment by iftahnaf** [comment]
> > the app freezes a few seconds after booting.
> 
> It freezes without you loading any mcap/bag file or connecting to a live data? 
> 
> Is this a snap install or from apt? apt. it worked fine until the update to 1.66

Yes, it freezes without loading or connecting to anything.
Installed with apt, worked fine until 1.66

**Comment by achim-k** [comment]
I have just tested this locally but I can't reproduce the freezing behavior. Could you try again after temporarily renaming the config folder `~/.foxglove-studio` such that Studio doesn't find it?

**Comment by iftahnaf** [comment]
The path is `~/.foxglove-studio`? I got nothing there.
I tried to reinstall with `apt` but it still not working.

**Comment by YazanRihan** [comment]
I have the same issue and that was after the the recent update through apt

**Comment by achim-k** [comment]
When the app freezes, can you still open the developer tools (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>)? 
What are the memory / cpu stats of the process?

**Comment by blauenase** [comment]
My frozen app uses 0,0% CPU and ~150MB Memory. I can open the Dev Tools window on startup, but after the crash it says: "DevTools was disconnected from the page". I can close but not open the DevTools after the crash.

**Comment by achim-k** [comment]
We have upgraded the electron version to 26.0 in the last release, it might be that.

Could you check if an empty electron window already freezes on your system? With https://www.electronjs.org/fiddle one can check for various electron versions:

Link to gist used in the gif below: https://gist.github.com/achim-k/40e54478a617c46fd83e320f71e2ced6

![Peek 2023-08-17 13-10](https://github.com/foxglove/studio/assets/9250155/7dad6a26-055b-4adf-a0dd-57a0e69c151d)

**Comment by blauenase** [comment]
The test with your posted gist and with electron 26.0.0 is working without crashes

**Comment by achim-k** [comment]
> I can open the Dev Tools window on startup, but after the crash it says: "DevTools was disconnected from the page". I can close but not open the DevTools after the crash.

Do you see anything suspicious in the dev tools javascript console before the crash? Does clearing the `localStorage` help?

**Comment by jtbandes** [comment]
@iftahnaf @blauenase  We've rolled back the electron version but it would still help a lot if you can provide more information about the hardware you are using (and other questions @achim-k posted above).

**Comment by iftahnaf** [comment]
@jtbandes v1.67 works, thanks!
When the app froze, I saw nothing informative with `ctrl` + `shift` + `i`, not much CPU usage.
I'm using ASUS TUF f15, with RTX3070, i7 12 gen, and 16 GB RAM.

**Comment by iftahnaf** [comment]
> Could you try enabling some [electron debug logging](https://www.electronjs.org/docs/latest/tutorial/application-debugging#v8-crashes) to see if there is any more info that appears when the app crashes?
> 
> Does it only crash if you perform certain actions in the UI (like loading a data source or choosing a layout)?

I can revert to v1.66 tomorrow (GMT +2 here) and try again.

It crashed immediately regardless of what I'm doing.

**Comment by jtbandes** [comment]
You can also try deleting or renaming the `~/.config/Foxglove Studio` folder to reset the app to the default state

**Comment by iliabaranov** [comment]
Note: I tried moving the above folder, though it reset the layout entirely, crash still occurs
