### ISSUE TITLE
Images broken on studio 1.68, PopOS 22.04 (Linux x86_64), Nvidia driver  535.104.05

### ISSUE THREAD

**Issue by venabled** [foxglove/studio#6706]
**Description**

Upgraded from v1.65 to v1.68, and Image panel no longer shows images working. Rostopic info on the image topics shows foxglove studio or rosbridge subscribed to those topics, but image panel is blank. No camera info topic is selected. Raw image data is available in the `Raw` panels. Downgrading to 1.65 fixes it.

- Version: 1.68
- Platform: Linux (AMD64) Desktop, PopOS 22.04 LTS, NVIDIA gfx version  535.104.05
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS1 native, ROS1 rosbridge

**Steps To Reproduce**
```
sudo apt update && sudo apt upgrade
```

**Expected Behavior**
Expect images to show up in image panel.

**Comment by jtbandes** [comment]
This sounds like it is probably related to https://github.com/foxglove/studio/pull/6665. Please double check the `step` value in your raw images and ensure it is correct. You should see an error message in the panel settings with more details.

**Comment by venabled** [comment]
It also doesn't work with compressedImage which is just jpeg, which is
interesting.

Will double check here with the step when I get a moment.

**Comment by jtbandes** [comment]
Could you share if there are any warnings or errors that appear in the dev console? (ctrl+shift+i)

**Comment by venabled** [comment]
For reference these are mono8,mono16 images for the most part. Step == 640 for mono8, 1280 for mono16.

**Comment by venabled** [comment]
![image](https://github.com/foxglove/studio/assets/1444624/1d4dd824-b47d-4c62-8921-bbead7f5fba9)

**Comment by jtbandes** [comment]
Do you get the same error on studio.foxglove.dev in Chrome?

**Comment by venabled** [comment]
No, I'm able to see both 16 and 8 bit mono as well as compressed using the
web instance.

**Comment by jtbandes** [comment]
What version of chrome is that?

**Comment by venabled** [comment]
`Version 116.0.5845.140 (Official Build) (64-bit)`

**Comment by jtbandes** [comment]
Could you try with Chrome 114? (That's the same version used by the desktop app currently.) Might also be worth trying 117 (latest beta) and 118 (latest dev, will be used in next electron release). See also: https://chromestatus.com/roadmap, https://www.electronjs.org/docs/latest/tutorial/electron-timelines

**Comment by venabled** [comment]
Still broken on 1.71 

![image](https://github.com/foxglove/studio/assets/1444624/d7030265-51b6-4f0d-99f8-93c5199248d6)

**Comment by jtbandes** [comment]
Yeah, we haven't changed the version of Electron/Chromium used in the app recently. This seems like an incompatibility with your drivers or hardware. I would be interested to learn if older or newer versions of the Chrome browser have different behavior – we can upgrade Electron again, but we previously had reports of other Linux users running into complete app crashes on the newer version (https://github.com/foxglove/studio/issues/6654) so I am hesitant to upgrade unless we can get confirmation that things are working.

**Comment by venabled** [comment]
Remind me again why I have an NVIDIA card on Linux.

**Comment by emersonknapp** [comment]
Just adding another datapoint that we're also seeing this issue

Version: 1.71.0
Platform:
```
$ uname -a
Linux my-hostname 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

```
NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2
NVIDIA GeForce RTX 4070
```


Data source: websocket

Downgrading to 1.65 solves it for now.

**Comment by jtbandes** [comment]
@emersonknapp Thanks for adding more details – could you also confirm whether this occurs with the sample dataset (and with which panels/layouts) or share an example data file that reproduces the issue?

**Comment by venabled** [comment]
This is fixed with 1.72.0, NVIDIA drivers `535.113.01`

**Comment by acowley** [comment]
I believe I am also seeing this problem with Foxglove Studio 1.75.0 on Ubuntu 20.04.6 and Nvidia drivers 535.129.03. Symptoms are blank Image and 3D panels.

```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Program binary could not be loaded. Binary is not compatible with current driver/hardware combination. Driver build date Oct 19 2023. Please check build information of source that generated the binary.
```

**Comment by jtbandes** [comment]
I think this will be fixed in https://releases.electronjs.org/release/v27.0.4
