### ISSUE TITLE
Plotting a negative duration wraps around

### ISSUE THREAD

**Issue by luisrayas3** [foxglove/studio#6727]
**Description**

In the "Plot" window type, plotting a duration field and publishing a negative value (e.g. secs=-1) results in 4294967295 = 2^32 - 1. The ROS docs state unambiguously that duration can be negative: http://wiki.ros.org/rospy/Overview/Time

- Version: 1.61.1
- Platform: Linux (Ubuntu)
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ROS1 native

**Steps to reproduce**

```
$ rostopic pub -r 1 /foo std_msgs/Duration '{data: {secs: -1}}'
```

![Screenshot from 2023-09-01 17-57-48](https://github.com/foxglove/studio/assets/5175205/77e68fb5-9455-4886-9146-0b685c7d28ac)

Result:
![Screenshot from 2023-09-01 18-00-29](https://github.com/foxglove/studio/assets/5175205/cb53c22e-61ca-4c81-a621-32b651a8d96b)

**Expected behavior**

Plot a negative value

**Comment by jtbandes** [comment]
Fixed in https://github.com/foxglove/studio/pull/6757
