### ISSUE TITLE
File open options do nothing

### ISSUE THREAD

**Issue by MattOslin** [foxglove/studio#6736]
**Description**

File > `Open...`
File > `Open local file...`
File > `Open connection...`

No longer work. Only able to get the open dialog by opening a new window.

- Version: 1.68.0
- Platform: macos 13.3.1 (a)
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

Open studio, load a local file or connection. Click File > Open. Nothing occurs.

**Expected Behavior**

A dialog box opens to allow the user to open a file or connection.

**Comment by jtbandes** [comment]
What browser are you using? 

> Only able to get the open dialog by opening a new window.

Does this mean the issue resolves itself once you refresh or restart your browser?

**Comment by MattOslin** [comment]
> What browser are you using?
> 
> > Only able to get the open dialog by opening a new window.
> 
> Does this mean the issue resolves itself once you refresh or restart your browser?

There is no browser involved, I am using the macos app. The issue does not resolve itself, I can no longer open logs without opening new windows.

**Comment by MattOslin** [comment]
I have found a workaround, this menu works for me, but only when not in fullscreen mode. In fullscreen mode clicking it does nothing (it used to work).
<img width="456" alt="Screenshot 2023-09-05 at 5 54 32 PM" src="https://github.com/foxglove/studio/assets/16124164/115cd448-89bf-4af8-9333-28aad058f333">

**Comment by MattOslin** [comment]
In fullscreen mode there is no hover-over response or click response from the foxglove logo
<img width="409" alt="Screenshot 2023-09-05 at 5 55 54 PM" src="https://github.com/foxglove/studio/assets/16124164/c275c6a7-b348-4d84-866b-e9b4b4c4528c">

**Comment by jtbandes** [comment]
I am able to reproduce the native File menu not working. However, I am not able to reproduce the issue with the foxglove logo not being clickable in fullscreen mode. Which macOS version are you using?

**Comment by MattOslin** [comment]
> I am able to reproduce the native File menu not working. However, I am not able to reproduce the issue with the foxglove logo not being clickable in fullscreen mode. Which macOS version are you using?

13.3.1 (a)
