### ISSUE TITLE
App window is unresponsive for several seconds after starting

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#678]
Since v0.5 the app window is black and completely unresponsive (not even draggable) for 6-7 seconds).

@defunctzombie thinks it is due to loading all the panel code up front now.

**Comment by defunctzombie** [comment]
This commit helped some by breaking up some of the larger script files which allowed us to turn on minification. https://github.com/foxglove/studio/commit/fed04ec37c6b0bb88153eb52ad56b4331846ca84

The next change would be to avoid loading the panel code altogether. I've created https://github.com/foxglove/studio/issues/747 to track that.

**Comment by amacneil** [comment]
This is still a problem with prod builds on latest main. It takes about 6 seconds from when the app is displayed until when the app is responsive. Until that time, it's not even possible to drag the application window.

**Comment by amacneil** [comment]
I tested some older versions:

- v0.4: startup freeze for 1-3 seconds
- v0.5 and above: startup freeze for 6-7 seconds

**Comment by amacneil** [comment]
Fixed by https://github.com/foxglove/studio/pull/863
