### ISSUE TITLE
WebGL error when coloring point cloud by point data

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#681]
Sample bag: https://storage.googleapis.com/cartographer-public-data/bags/backpack_3d/with_intensities/b3-2016-04-05-14-14-00.bag

Repro by turning on `horizontal_laser_3d` topic and coloring by intensity.

![image](https://user-images.githubusercontent.com/637671/116292328-6a6ed900-a74a-11eb-8c66-5213e34a89b5.png)

This bag also has issues coloring `/scan_cloud_aggregated` by z, although x and y work: 
https://storage.googleapis.com/cartographer-public-data/bags/taurob_tracker/taurob_tracker_simulation.bag

via @jtbandes

**Comment by amacneil** [comment]
Can't repro in latest version, both bags color fine for me.

![image](https://user-images.githubusercontent.com/637671/126216071-afd9b4ab-269d-4bc2-af05-a955ce3a9708.png)

The first bag does seem to cause our app to crash on my machine, I will open a separate ticket.

**Comment by jtbandes** [comment]
Did you check the console to see whether there are WebGL errors (rather than just looking at 3D view visually)?

**Comment by amacneil** [comment]
Yes. No console errors for me on either bag following the instructions above. Maybe good if you test as well to ensure it's not a platform specific thing?

**Comment by jtbandes** [comment]
I still see the error on mac. Layout: 

```
{
  "configById": {
    "3D Panel!1avl4ju": {
      "checkedKeys": [
        "name:Topics",
        "t:horizontal_laser_3d"
      ],
      "expandedKeys": [
        "name:Topics"
      ],
      "followOrientation": false,
      "cameraState": {
        "distance": 75,
        "perspective": true,
        "phi": 0.7853981633974483,
        "target": [
          0,
          0,
          0
        ],
        "targetOffset": [
          0,
          0,
          0
        ],
        "targetOrientation": [
          0,
          0,
          0,
          1
        ],
        "thetaOffset": 0,
        "fovy": 0.7853981633974483,
        "near": 0.01,
        "far": 5000
      },
      "modifiedNamespaceTopics": [],
      "pinTopics": false,
      "settingsByKey": {
        "t:horizontal_laser_3d": {
          "colorMode": {
            "mode": "rainbow",
            "colorField": "intensity"
          }
        }
      },
      "autoSyncCameraState": false,
      "autoTextBackgroundColor": true,
      "diffModeEnabled": true
    }
  },
  "globalVariables": {},
  "userNodes": {
    "7662ada8-06c0-4969-a77d-64a151101dd8": {
      "sourceCode": "import { Input, Messages } from \"ros\";\n\ntype foo_msgs__Bar = {\n  a: string;\n  b: number;\n  // z?: 3;\n  // (x: 3): foo_msgs__Bar;\n  // @ts-ignore\n  // qza;\n};\ntype GlobalVariables = { id: number };\n\nexport const inputs = [\"/radar/tracks\"];\nexport const output = \"/studio_node/test\";\n\n// Populate 'Input' with a parameter to properly type your inputs, e.g. 'Input<\"/your_input_topic\">'\nconst publisher = (\n  message: Input<\"/radar/tracks\">,\n  globalVars: GlobalVariables\n): foo_msgs__Bar => {\n  return {\n    a: \"12\",\n    b: 2,\n  } as foo_msgs__Bar;\n};\n\nexport default publisher;\n",
      "name": "/studio_node/7662ada8"
    }
  },
  "linkedGlobalVariables": [],
  "playbackConfig": {
    "speed": 1,
    "messageOrder": "receiveTime",
    "timeDisplayMethod": "ROS"
  },
  "layout": "3D Panel!1avl4ju"
}
```

**Comment by amacneil** [comment]
No error for me with 0.13.1 on linux - interesting. Seems odd that it would be platform dependent.

Will assign to you since you can repro.

**Comment by jtbandes** [comment]
Not the first platform dependent WebGL bug :trollface:  https://github.com/cruise-automation/webviz/pull/24
