### ISSUE TITLE
Handle ros1 publishers coming online and going offline

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#683]
via @jhurliman:

We need to handle the XMLRPC calls coming in from rosmaster in addition to the TCP disconnect handling

**Comment by defunctzombie** [comment]
@amacneil In what way does this manifest as a bug? When you shutdown a node and re-launch it studio does not reconnect?

**Comment by amacneil** [comment]
Not sure @jhurliman wrote this, I just imported it. Should document the user facing issue.
