### ISSUE TITLE
Title copying still broken

### ISSUE THREAD

**Issue by MattOslin** [foxglove/studio#6878]
**Description**
Similar to https://github.com/foxglove/studio/issues/6403, but now the behavior is that when you click on title text it highlights the first half, but ctrl+c gives you the full title text. There is no way to select a portion of the text and copy it, like normal text.

- Version: 1.68.0 (darwin)
- Platform: osx
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**
Open an mcap file. Try to select part of the file name in the title and copy.

**Expected Behavior**
You can select text to copy it. Instead you get the full title/filename always

**Comment by defunctzombie** [comment]
Internal tracking issue: https://linear.app/foxglove/issue/FG-5085/title-copying-still-broken-[foxglovestudio-6878]
