### ISSUE TITLE
no such Type or Enum '.google.protobuf.Timestamp' in Type .foxglove.RawImage

### ISSUE THREAD

**Issue by Danvil** [foxglove/studio#6958]
**Description**
When loading an MCAP file with a single stream of `RawImage.proto` Foxglove Studio gives the following error:
```
no such Type or Enum '.google.protobuf.Timestamp' in Type .foxglove.RawImage
```

- Version: Foxglove Studio 1.72
- Platform: Windows
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): MCAP file

**Steps To Reproduce**
Load the following file in MCAP studio: [oak_viewer.zip](https://github.com/foxglove/studio/files/12824240/oak_viewer.zip). Images are not shown and an error message is printed under "Problems".

**Expected Behavior**
The file loads correctly and images contained in the file are displayed.

**Comment by jtbandes** [comment]
Hi,
I get a similar error from the mcap cli:

```
$ mcap cat --json oak_viewer.mcap 
Error: failed to print messages: failed to create file descriptor: proto: could not resolve import "google/protobuf/timestamp.proto": not found
```

This likely means that you created the MCAP file with a protobuf binary FileDescriptorSet that does not include all dependencies. If you are using `protoc --descriptor_set_out`, then make sure to also use `--include_imports`. If you are doing it yourself, follow the examples here: https://foxglove.dev/docs/studio/connection/custom#protobuf

**Comment by jtbandes** [comment]
Good point, will update the docs. We do include in in this old blog post but it should be on the docs page as well: https://foxglove.dev/blog/using-protobuf-data-with-the-foxglove-websocket-connection
