### ISSUE TITLE
Cannot view compressed images in image panel - Unsupported format: "rgb8; jpeg compressed bgr8"

### ISSUE THREAD

**Issue by bernard-bear** [foxglove/studio#6964]
**Description**

Hello! I've been using the rosbridge connection on Foxglove Studio Web for a few months now, and there were previously no issues with viewing compressed Astra rgb images via the Image Panel. However, today I just encountered an error:

Error in Image Panel, next to the topic: `Error decoding image: Unsupported format: "rgb8; jpeg compressed bgr8"`

![image](https://github.com/foxglove/studio/assets/138452214/c28e2cd7-2425-4b8d-9481-cfad7321eb8c)

Console shows: `Error: Unsupported format: "rgb8; jpeg compressed bgr8"`

![image](https://github.com/foxglove/studio/assets/138452214/0674eaf0-edf0-4f85-a82e-72db1f1a5f20)

- Version: 1.72.0+d5acba0.c105d9e
- Platform: Web
- Data source: rosbridge (ROS 1)

As mentioned, this is a new error that appeared only recently. Previous versions of Foxglove Studio Web had no issue, so this is likely a regression. Additionally, today I also tested on the desktop app (version 1.72.0, Ubuntu 22.04) and it works fine.

**Steps To Reproduce**
1. Connect to a ROS 1 system via rosbridge
2. Open image panel and select a topic with compressed Astra rgb image data

**Expected Behavior**

No errors, compressed images appear in image panel

**Comment by jtbandes** [comment]
Fixed by https://github.com/foxglove/studio/pull/6974
