### ISSUE TITLE
Convert Modals to FluentUI

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#699]
via @jtbandes:

- [x] #1335
- [x] #670
- [x] #1365
- [x] #1288 
- [x] #1005
- [x] #1386
- [x] #1337
- [x] #1408
- [x] #1409

**Comment by 2metres** [comment]
Removing non modals and creating separate issues

**Comment by 2metres** [comment]
Once these are done should we remove the generic foxglove `<Modal /> ` and `<RenderComponentToBody />`?

**Comment by jtbandes** [comment]
If that's the only thing RenderComponentToBody is used for, then yep

**Comment by defunctzombie** [comment]
@2metres All the items in this list are done. Are we good to close this? Did the foxglove `<Modal />` and `<RenderComponentToBody/ >` get removed? Should we make a separate issue for that?
