### ISSUE TITLE
Replace studio-base/components/Dropdown and studio-base/components/Menu with MUI

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#705]

**Comment by foxymiles** [comment]
@amacneil This seems moot now that we're moving to MUI right?

**Comment by amacneil** [comment]
Yep

**Comment by jtbandes** [comment]
Well we could still use the same issue for mui?

**Comment by defunctzombie** [comment]
Dropdown does not exist anymore. Menu does and we are tracking it in the fluentui 🔪 epic.
