### ISSUE TITLE
Local files: Support for latched or infrequently published topics when scrubbing

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#707]
When scrubbing, we should intelligently find the right message to display for topics which are published infrequently.

- [x] Experimental play w/ support for .bag files
- [x] #3027
- [x] #3028
- [x] https://github.com/foxglove/studio/issues/2899
- [x] https://github.com/foxglove/studio/issues/1962
- [x] #3361

References:
- https://github.com/cruise-automation/webviz/issues/314
- https://github.com/fetchrobotics/webviz/commit/ab301ca317e816583db6e93d24b370253c5c2092

cc @cjds

**Comment by rgov** [comment]
I'm not sure what you have in mind but it would be helpful to have a `PanelAPI` function that enumerates messages forward or backward in a given time window.

This be useful for things like video streams (#537), where to decode a given frame you need to find some earlier messages that provide context: the header(s) that describe the width, height, and other parameters; the last intra frame; and all subsequent inter frames that are deltas to the inter frame.

1. Search backwards from `currentTime` to find the header packet message.
2. Search backwards from `currentTime` to `headerPacket.header.stamp` to find the most recent intra frame.
3. Search forwards from `intraFrame.header.stamp` to `currentTime` to collect a list of inter frames.

**Comment by jhurliman** [comment]
This may be related to <https://github.com/foxglove/studio/issues/2343>. Internally latching every topic in Studio would likely make seeking/scrubbing work a lot better in practice, especially with bags that have `/tf_static`.

**Comment by amacneil** [comment]
Also created https://github.com/foxglove/studio/issues/2899 for the same feature in Data Platform

**Comment by defunctzombie** [comment]
Re-opening because this issue is a meta-tracking issue which also needs to have support for mcap.

**Comment by defunctzombie** [comment]
@rgov 

> I'm not sure what you have in mind but it would be helpful to have a `PanelAPI` function that enumerates messages forward or backward in a given time window.

This issue won't cover this functionality. This issue is scoped to only finding the last message on each topic.
