### ISSUE TITLE
Pointcloud2 visualization

### ISSUE THREAD

**Issue by edvart-ros** [foxglove/studio#7148]
- Version: Recently installed foxglove studio, ROS2 Iron
- Platform: Docker on windows
- Data source: Live connection to container

Attempted to visualize the pointcloud2 message in foxglove studio. Foxglove complains about "PointCloud must contain at least two of x/y/z fields" and wont visualize the points. I am manually populating these messages, but have verified the format by visualizing the messages in rviz2. Rviz has no issues with the message format and does the visualization correctly. Is this just a foxglove bug or is it being intentionally more picky about the format?

Example message:
```
{
  "header": {
    "stamp": {
      "sec": 1700177019,
      "nsec": 615725994
    },
    "frame_id": "wamv/lidar_link"
  },
  "height": 1,
  "width": 1728,
  "fields": [
    {
      "name": "x",
      "offset": 0,
      "datatype": 7,
      "count": 1728
    },
    {
      "name": "y",
      "offset": 4,
      "datatype": 7,
      "count": 1728
    },
    {
      "name": "z",
      "offset": 8,
      "datatype": 7,
      "count": 1728
    }
  ],
  "is_bigendian": false,
  "point_step": 12,
  "row_step": 20736,
  "data": [
    0,
    0,
    192,
    255,
    0,
    0,
    192,
    127,
    ...
  ],
  "is_dense": true
}
```
![image](https://github.com/foxglove/studio/assets/94528774/8e8b2996-a3ea-414b-ba56-d0016f7d09cb)

![image](https://github.com/foxglove/studio/assets/94528774/a3c6ab2e-427b-4ab9-b8a1-443f67a59647)

**Comment by jtbandes** [comment]
Please share a bag/mcap file that we can use to reproduce the issue.

**Comment by edvart-ros** [comment]
[rosbag2_2023_11_20-18_55_07_0.zip](https://github.com/foxglove/studio/files/13418104/rosbag2_2023_11_20-18_55_07_0.zip)

**Comment by jtbandes** [comment]
The problem is the `"count": 1728` – foxglove only supports fields with count equal to 1.
