### ISSUE TITLE
ROS 2 rosbridge websocket connection support

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#716]
Placeholder ticket to discuss if ROS 2 websocket connections are interesting to anyone.

In theory we could allow connections over websocket (similar to what we support with `rosbridge` in ROS 1) using https://github.com/RobotWebTools/ros2-web-bridge.

However, we have also discussed a native-connection-over-ssh option which might be more useful than websocket connections. We're open to feedback.

See also:
- https://github.com/foxglove/studio/issues/715 (ROS 2 native connections)
- https://github.com/foxglove/studio/issues/717 (ROS 2 bag support)
- https://github.com/RobotWebTools/ros2-web-bridge/issues/174
- https://github.com/RobotWebTools/rosbridge_suite/issues/345

**Comment by amacneil** [comment]
This might not be necessary if we add support for ssh tunnels.

However, it may be needed if we wish to retain browser compatibility.

**Comment by jtbandes** [comment]
Leaving this open until https://github.com/RobotWebTools/rosbridge_suite/pull/574 is merged and released.

**Comment by jtbandes** [comment]
Release is currently blocked on https://github.com/GT-RAIL/rosauth/issues/35

**Comment by jtbandes** [comment]
- galactic: https://github.com/ros/rosdistro/pull/30479
- foxy: https://github.com/ros/rosdistro/pull/30480

**Comment by amacneil** [comment]
All studio features are complete, we are just waiting for the next Galactic sync to release rosbridge, which is happening on [Tuesday](https://discourse.ros.org/t/preparing-for-galactic-sync-2021-08-24/21900).
