### ISSUE TITLE
ROS 2 bag support

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#717]
We should support loading ROS 2 bags.

It seems that will be much more difficult than loading ROS 1 bags, since ROS 2 bags are not a self contained file, and the output folder can contain many different formats (sqlite is the default driver).

See also:
- https://github.com/foxglove/studio/issues/715 (ROS 2 native connections)
- https://github.com/foxglove/studio/issues/716 (ROS 2 websocket connections)

**Comment by jtbandes** [comment]
Fixed in #1436! 🎉
