### ISSUE TITLE
Merge _addMarker/_consumeMarker in SceneBuilder

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#719]
Since #622, one of these two functions is unused. If there are any differences we should merge them.

**Comment by defunctzombie** [comment]
`_addMarker` removed in https://github.com/foxglove/studio/commit/f3aee3c3e7c8452986f61b2d1457b96099dbd51b#diff-dd0db32ea09eb42be919b34c45f46ac0d4c17b2ae7ba422c6af781aca5a01f19
