### ISSUE TITLE
TF section in 3D panel topic list should be collapsible

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#722]
via @jtbandes:

I thought this used to be collapsible but it doesn't appear to be. The list of TFs can get very long, which pushes the actual viz topics lower and makes for a confusing experience. I guess it is collapsible in some cases — not sure why it wasn't in this case.

![image (1)](https://user-images.githubusercontent.com/637671/116326314-01eb2080-a779-11eb-956f-50820b448515.png)

**Comment by jtbandes** [comment]
Seems to be fixed, maybe it was just a missing icon?
