### ISSUE TITLE
Interactions for user-drawn polygons in 3D panel are broken

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#723]
### Overview

The 3D panel docs include this section on drawing polygons:

![Screen Shot 2021-04-27 at 5 08 17 PM](https://user-images.githubusercontent.com/6993359/116327234-2ea03780-a77b-11eb-9149-8f1c9aca3674.png)

Of the functionality described above, only 1) drawing a polygon, 2) selecting a polygon, and 3) bisecting a polygon edge seem to be working. Selecting a point within the polygon, moving / resizing / deleting a polygon, deleting a point in the polygon, etc. are not working, at least not as described by the included documentation.

### Steps to repro
- Open Foxglove Studio with demo bag: `https://storage.googleapis.com/foxglove-public-assets/demo.bag`
- Open 3D panel and click on pencil icon
- Hold Ctrl + click around on canvas to create a polygon
- All other interactions (selecting point, moving point, etc.) do not work as expected

**Comment by amacneil** [comment]
@esthersweon is following up to get more context on this feature

**Comment by amacneil** [comment]
Likely that we will replace this feature with ability to create "static markers" in the scene (https://github.com/foxglove/studio/issues/1560).

In the meantime, we should update docs to remove references broken functionality, since it's not clear anyone is using this feature.

**Comment by esthersweon** [comment]
Used mostly for debugging - people copy these points from someplace else (e.g. test outputs) and paste them into the 3D panel to see where it is related to other objects in the scene.

**Comment by amacneil** [comment]
Next steps: Move entire polygon feature behind feature flag and remove documentation.
