### ISSUE TITLE
Publish panel should allow publishing arbitrary/common datatypes

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#725]
via @jtbandes:

I should be able to publish a `geometry_msgs/Twist` to control turtlesim, even though there are no publishers for this topic yet.

This might mean we need to ship common datatype definitions with the app, if the md5sum needs to be correct.

`rostopic pub` does this by looking up the datatype definition on disk.

**Comment by jtbandes** [comment]
I think this may be done now?
