### ISSUE TITLE
Node Playground should support importing custom data types

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#726]
via @jtbandes:

Node Playground lets you publish custom datatypes, but the datatype name that's exposed to the rest of the app is autogenerated. This means the message can't be used for other panels that are looking for specific datatypes.

![image (2)](https://user-images.githubusercontent.com/637671/116328412-d0288880-a77d-11eb-9cc6-a3267d3b92a9.png)

We should consider allowing users to import custom data types for use in Node Playground that aren't part of the common ROS packages, but also aren't in their bag / data source.

(It would also be good to provide built-in definitions for the common ROS datatypes: #1261)

**Comment by jhurliman** [comment]
> It would also be good to provide built-in definitions for the common ROS datatypes.

This part is addressed in https://github.com/foxglove/studio/pull/1038

**Comment by jtbandes** [comment]
> > It would also be good to provide built-in definitions for the common ROS datatypes.
> 
> This part is addressed in #1038

I don't think it is — I tried to use Node Playground today and I didn't find any common data types exposed to my code. I filed #1261 to track this part

**Comment by defunctzombie** [comment]
Node playground understands if you are using existing messages from your datasource types (and builtin types) and uses those datatype names.
