### ISSUE TITLE
TF editor

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#730]
via @jhurliman:

Editable table view of all TF values and the ability to add/delete/rename rows. This will need a clear button as well to reset back to TFs sourced from the player only.

**Comment by Aposhian** [comment]
What use case would this serve?

**Comment by amacneil** [comment]
I don't recall why you would want to add/delete/rename TFs. @jhurliman thoughts?

I'm going to close this as a duplicate of https://github.com/foxglove/studio/issues/1975. Even through https://github.com/foxglove/studio/issues/1975 is newer, it has a better description.
