### ISSUE TITLE
Missing transform error in the demo bag

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#734]
via @jhurliman:

![missing-transform-demo-bag](https://user-images.githubusercontent.com/637671/116329669-b2a8ee00-a780-11eb-98d9-161e389c1997.png)

**Comment by defunctzombie** [comment]
I was able to open the demo bag and display radar points. Closing this as it is likely stale or before we made some tf fixes. Open if you are able to reproduce and provide more details.
