### ISSUE TITLE
Resizing panels causes 3D panel to flicker

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#735]
via @jtbandes:

https://user-images.githubusercontent.com/637671/116329832-04ea0f00-a781-11eb-971f-73fd0477e01d.mov

**Comment by defunctzombie** [comment]
I've removed the bug label from this. I don't see anything to indicate that the app breaks when this happens. Possibly a re-render. I've added the ux label to indicate there could be an improvement here - even then its minimal.

**Comment by defunctzombie** [comment]
No longer able to reproduce. I suspect this was related to some layout re-rendering or canvas resizing logic which has been implicitly fixed through other changes.
