### ISSUE TITLE
Playback scrubber and tooltips appear on top of modals

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#740]
via @jtbandes:

I guess the z-index is quite high. I'm not sure if we want to try and prevent any mouse events from getting through modals, or just make sure the tooltip is underneath the modal.

https://user-images.githubusercontent.com/637671/116330070-9194cd00-a781-11eb-9427-c19b06c5de2f.mov

**Comment by defunctzombie** [comment]
The modal in this example video no longer exists. Possibly the tooltips appear over other modals tho? Downgrading to _ux_ issue.

**Comment by defunctzombie** [comment]
Looks fixed.
