### ISSUE TITLE
Dependencies cannot be pulled down

### ISSUE THREAD

**Issue by a554878526** [foxglove/studio#7402]
**Description**

![image](https://github.com/foxglove/studio/assets/70568691/4a119939-c9b9-4361-a0d9-6c714e4215e1)

- Version:
- Platform:
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

**Expected Behavior**

**Comment by a554878526** [comment]
Users from China

**Comment by defunctzombie** [comment]
This is an issue with your connectivity and access to Github. The referenced dependency is in a public repo: https://github.com/foxglove/comlink and is not restricted.
