### ISSUE TITLE
Joystick support broken in Snap package

### ISSUE THREAD

**Issue by joshnewans** [foxglove/studio#7409]
**Description**

Extensions that access the Gamepad API do not work under the Snap version of Foxglove

- Version: 1.85.0
- Platform: Linux Snap
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Websocket

**Steps To Reproduce**
- Install my [Joystick panel](https://github.com/joshnewans/foxglove-joystick) on the snap version of Foxglove
- Switch into gamepad mode
- Use gamepad
- Doesn't work

**Expected Behavior**

- Gamepad works

I know essentially nothing about snap packaging, but my understanding is that snaps block access to joysticks by default. There is the [joystick interface](https://snapcraft.io/docs/joystick-interface) and this could be auto-enabled or switchable in the terminal, but either way I think needs to be configured as part of the initial packaging?

**Comment by joshnewans** [comment]
In addition to the `joystick` snap interface mentioned above, I have also seen posts online mention [`uinput`](https://snapcraft.io/docs/the-uinput-interface) which is presumably similar but more generic?

**Comment by Guillaumebeuzeboc** [comment]
What is necessary here is probably something similar to this patch:  https://github.com/foxglove/studio/blob/main/patches/app-builder-lib.patch

But would be something like:
```diff
--- a/templates/snap/snapcraft.yaml
+++ b/templates/snap/snapcraft.yaml
###
-    plugs: ["desktop", "desktop-legacy", "home", "x11", "wayland", "unity7", "browser-support", "network", "gsettings", "audio-playback", "pulseaudio", "opengl"]
+    plugs: ["desktop", "desktop-legacy", "home", "x11", "wayland", "unity7", "browser-support", "network", "gsettings", "audio-playback", "pulseaudio", "opengl", "joystick"]
```
I am not sure where and when this patch is applied, but this is the idea.

Then the user will connect the interface:
```
sudo snap connect foxglove-studio:joystick 
```
Unless there is an [auto-connection request](https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks) made for that.

**Comment by achim-k** [comment]
We have added the `joystick` and `camera` plugs for the upcoming release. It should then work if you do

```
sudo snap connect foxglove-studio:joystick 
```

as @Guillaumebeuzeboc already mentioned above.
