### ISSUE TITLE
Lazy load panel components on demand

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#747]
Rather than importing all panels into the BuiltinPanelCatalog - make a catalog from instances (maybe of a Panel class) which will lazy load panel components on demand. This will lower the amount of code loading up-front to render the initial app containers.

**Comment by jtbandes** [comment]
I think a nice loading screen would be more impactful for “smooth launch experience” than splitting panel loading. _Now you have 10 loading spinners_

**Comment by amacneil** [comment]
@jhurliman made a good comment in Slack about following the pattern of showing some greyed out app UI while loading (similar to pretty much every other tool & website these days). 

The main problem in v0.6 is that the whole window is unresponsive (not even draggable) while we're loading. I believe Roman fixed that in https://github.com/foxglove/studio/pull/639.
