### ISSUE TITLE
Investigate removing maybePlayer

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#754]
via @jtbandes:

The CONSTRUCTING status was added to PlayerPresence because some player selection options cannot be immediately constructed. Specifically because of the IndexedDB bag caching feature, `buildPlayerFromBagURLs` requires fetching the "guid" of the remote bag before the data providers can be constructed. If we could make this part of the standard data provider initialization process then we could probably remove `maybePlayer` and make MessagePipeline the only vendor of player status.

**Comment by defunctzombie** [comment]
IndexedDB caching is no more so this might be easier to accomplish now.
