### ISSUE TITLE
Ensure std_msgs/Empty is supported

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#758]
https://github.com/foxglove/studio/blob/08e5c0c113ffb7cc3c3a7de24fd2836856e0b43d/app/dataProviders/BagDataProvider.ts#L202-L206

**Comment by jtbandes** [comment]
Related: https://github.com/cruise-automation/webviz/issues/588

**Comment by jtbandes** [comment]
@jhurliman did you check on the warning message I specifically linked to above, when a bag contains std_msgs/Empty?

**Comment by defunctzombie** [comment]
Fixed by https://github.com/foxglove/studio/pull/1479
