### ISSUE TITLE
2D view mouse movements are erratic when you zoom in

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#765]
via @jhurliman:

Repro: in the demo bag, turn on the `base_link` tf and zoom in far enough in the default 2D view until you can see the three-axis rendering of the tf. At this zoom level, tiny mouse movements will cause erratic >90 degree spins of the view. If you switch to 3D view this problem goes away and rotating the camera with the mouse is smooth.

I was able to reproduce erratic camera movements with small mouse motions in the 3D view as well.

**Comment by jtbandes** [comment]
I think this is via @jhurliman. iirc I wasn't able to reproduce this issue — we need to narrow down whether it happens on certain platforms or with certain mouse devices etc.
