### ISSUE TITLE
Topic Graph panel: add storybook tests

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#771]
via @jhurliman 

The Topic Graph panel doesn't have any screenshot tests in storybook/chromatic.

Examples can be found in other `*.stories.tsx` files — for example https://github.com/foxglove/studio/blob/main/packages/studio-base/src/panels/URDFViewer/index.stories.tsx

**Comment by esthersweon** [comment]
These storybook tests now exist - example here: https://www.chromatic.com/component?appId=603ec8bf7908b500231841e2&name=panels%2FTopicGraph%2Findex&buildNumber=3256&specName=Empty
