### ISSUE TITLE
Joystick/gamepad/teleop panel

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#775]
Feature request from @rgov on Slack:

Currently we have a Publish panel, but it is limited to only creating one button. It would be nice to create a panel to allow basic control of the robot. Idea would be to support both mouse/keyboard control via UI, and/or to support USB joysticks via HID.

We should publish `geometry_msgs/Twist` messages.

For example: https://github.com/WHOIGit/ros-web-gamepad.

Need to be able to customize the publish topic name. For example, duckiebot publishes to `/robotname/joy`.

**Comment by jtbandes** [comment]
Example prototype implementation: https://github.com/cruise-automation/webviz/pull/561
