### ISSUE TITLE
Rosbag play/pause support in Ros1Player

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#779]
via @jhurliman:

It should be possible to support play/pause over the Ros1Player if we recognize a bag replay is happening.

**Comment by jtbandes** [comment]
FYI, this was a feature we previously achieved by editing the `rosbag play` source code to add a topic to play, pause, seek, and set speed.

The [standard version of rosbag](http://wiki.ros.org/rosbag/Commandline) seems like it supports `--rate-control-topic`, but not general play/pause/seek/speed capabilities.

Here's an old discussion thread about the issue: https://answers.ros.org/question/28798/pause-functionality-in-rosbag-play/ & http://library.isr.ist.utl.pt/docs/roswiki/rxbag.html
