### ISSUE TITLE
Support Ouster lidar

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#781]
via @jtbandes:

We currently support Velodyne packets. We should add support for Ouster too.

See:
- https://github.com/cruise-automation/webviz/issues/162, https://github.com/cruise-automation/webviz/issues/675 (similar webviz feature requests)
- https://data.ouster.io/downloads/software-user-manual/lidar-packet-format-update.pdf
- https://github.com/ouster-lidar/ouster_example

**Comment by amacneil** [comment]
Closing because we have not had any user requests for this. If interested, please comment.

**Comment by albait03** [comment]
Hello, 
i am currently working with Lidar from Ouster. When I am trying to visualize the data i get the following error:

![image](https://user-images.githubusercontent.com/59478554/154437515-7f58130a-caec-4e04-a133-5da7b0b72c9b.png)

Is there any plan to support visualizing bag files from Ouster in the near future?

**Comment by amacneil** [comment]
See also: https://github.com/cruise-automation/webviz/issues/714

@albait03 I saw you posted here and then deleted your comment. Did you try your bag file in Foxglove Studio (https://studio.foxglove.dev/)? I'm pretty sure it should work out of the box based on your screenshot.

**Comment by albait03** [comment]
Thank you for the advice. I tried out Foxglove Studio and it met my requirements. I did not know about Foxglove and that there is an almost identical alternative to Webviz.

**Comment by jtbandes** [comment]
If you'd like to learn more about the differences between Foxglove Studio and Webviz, we have a blog post about it: https://foxglove.dev/blog/foxglove-studio-vs-webviz

**Comment by mamacker** [comment]
We're going to be bringing Ouster Lidar into FoxGlove - just adding a comment to reinforce this need. :)

**Comment by Grisly00** [comment]
Yes please!

**Comment by defunctzombie** [comment]
Is this a separate request from supporting point clouds? We have support for point cloud messages in Studio which you can produce from many different types of lidar sensors. We've no plans to add custom support for ouster lidar beyond point clouds right now.
