### ISSUE TITLE
Visualize MESH_RESOURCE markers in the 3D panel

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#782]
We currently have a separate URDF Viewer panel, but users naturally want to visualize the robot model along with other markers, pointclouds, map, etc.

Related: https://github.com/cruise-automation/webviz/issues/568 and https://github.com/foxglove/studio/issues/1984

> In #1983 we are adding support for MESH_RESOURCE markers, but currently only supporting HTTP(S) URLs pointing at glTF (.glb) 3D models. Support for the rviz-supported mesh formats (.stl and .dae) and package:// URLs is planned.

**Comment by v4hn** [comment]
This is one of the basic requirements for everything involving manipulation. So yes, not having this is a deal-breaker for us.

**Comment by defunctzombie** [comment]
Related idea (or part of the implementation) is a resource browser that would let users upload their resources and reference them in markers similar to how ROS markers allow for a mesh_resource string http://wiki.ros.org/rviz/DisplayTypes/Marker#Mesh_Resource_.28MESH_RESOURCE.3D10.29_.5B1.1.2B-.5D

**Comment by jhurliman** [comment]
In https://github.com/foxglove/studio/pull/1983 we are adding support for `MESH_RESOURCE` markers, but currently only supporting HTTP(S) URLs pointing at glTF (.glb) 3D models. Support for the rviz-supported mesh formats (.stl and .dae) and `package://` URLs is planned.

**Comment by amacneil** [comment]
Closing. Remaining work tracked in https://github.com/foxglove/studio/issues/2059
