### ISSUE TITLE
"Recent files/connections" UI

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#789]
Would be nice to show in the menu or elsewhere some recent bag files or ros connections you made, so that the user doesn't have to load these each time.

**Comment by jtbandes** [comment]
This would be especially useful during development when we tend to reload the page quite often. It would be helpful not to have to drag a bag file in each time.

**Comment by foxymiles** [comment]
@amacneil We can close this now right?

**Comment by jtbandes** [comment]
Yeah this is done in #2388 / https://github.com/foxglove/studio/pull/2312 / other open dialog work
