### ISSUE TITLE
Hovering playback bar should highlight points in Map panel

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#801]
The currently hovered time `hoverValue` should be used in Map to show the closest GPS position when hovering on the playback bar (or on a Plot).

This code will probably need to be cleaned up to store a Time instead of an arbitrary "hoverValue" since the Map does not use a linear translation for highlighting the current position.

https://github.com/foxglove/studio/blob/6579ae338deb916fe4e665df62fe5845bee16df8/app/components/TimeBasedChart/HoverBar.tsx#L56

https://github.com/foxglove/studio/blob/6579ae338deb916fe4e665df62fe5845bee16df8/app/components/TimeBasedChart/index.tsx#L768-L771

As a bonus, hovering on the Map could also update the hoverValue and clicking can seek playback.

https://github.com/foxglove/studio/blob/fc858b1fd337f7413c6f6457befed78f35d66a91/app/panels/Plot/index.tsx#L265-L276

Related: https://github.com/foxglove/studio/issues/1105

**Comment by defunctzombie** [comment]
We can add a `const { hoverTime, setHoverTime } = useHoverTime()` to the panels api. Should also consider alternatives to calling it _hover_ tho maybe that is appropriate.

**Comment by jtbandes** [comment]
Yeah, maybe something like `previewedTime`?
