### ISSUE TITLE
mDNS caching

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#805]
There is no caching on mDNS responses right now, which means we can flood a server with mDNS requests when connecting to many nodes at once (such as subscribing to `/rosout`). This results in the occasional timeout which is at least caught and displayed to the user in 0.6.1-dev, but we should be able to prevent it from happening entirely by obeying the TTL field of the mDNS response. The retry loop would also benefit from the exponential truncated backoff with jitter algorithm we use elsewhere in the codebase (ros1 library) rather than a fixed one second loop which can cause a thundering herd problem.

**Comment by amacneil** [comment]
Ah, the joys of running our own dns
