### ISSUE TITLE
Provider topics should not change often

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#846]
> If they do they are probably not memoized properly. Please let the Foxglove team know if you see this warning.

This happens when connecting to a websocket (just simple rosbridge+roscore running inside a VM) on latest main.

Not sure what it means but it is not actionable so should probably not be displayed to the user at all.

![image](https://user-images.githubusercontent.com/637671/116938632-ed4ad480-ac1f-11eb-9bfc-49412f5a1d91.png)

**Comment by defunctzombie** [comment]
@jtbandes @amacneil I researched this further to understand why we get this. I wasn't able to reproduce the warning by connecting immediately to websocket but I was able to reproduce by having a local bag file open and then switching to a websocket connection.

The warning comes from https://github.com/foxglove/studio/blob/main/app/components/MessagePipeline/index.tsx#L245 which uses https://github.com/foxglove/studio/blob/f4da0a890d275c0619e7477005507dd649001d72/app/hooks/useShouldNotChangeOften.ts#L17. This hook checks that the value has not changed 3 times within 200 ms. However, when changing the player the value _does_ change 3 times in 200ms. The current player topics value, then undefined while websocket is connecting, and finally the new topics value.

I am not convinced on the usefulness of this warning; It is definitely a false positive in the situation I described.

**Comment by amacneil** [comment]
Maybe we just remove this message then? We see this a lot in sentry too. I'm unclear whether there is any real issue for us to be concerned about here.

**Comment by amacneil** [comment]
@defunctzombie is this closed by https://github.com/foxglove/studio/pull/994?

**Comment by defunctzombie** [comment]
@amacneil no - it will be fixed by https://github.com/foxglove/studio/pull/993
