### ISSUE TITLE
Enable Windows dark mode

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#852]
Currently, the app titlebar does not change to dark mode even though we force enable dark mode. It seems like this line:

https://github.com/electron/electron/blob/v14.0.0-nightly.20210503/buildflags/buildflags.gni#L36

needs to be modified and a custom build of Electron created. Discussion: https://github.com/electron/electron/pull/25373#issuecomment-825778990

**Comment by amacneil** [comment]
I guess there comes a time in every electron app's life when they need to build electron from source...
