### ISSUE TITLE
zoomPercentage for the image panel was <N>, but must be between 0 and 150. It has been reset to 100.

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#866]
<img width="463" alt="zoom-percentage" src="https://user-images.githubusercontent.com/195374/117069390-43cc1780-ace1-11eb-906e-0c24c6d9de01.png">

I don't know what the exact repro is, but I think this happens sometimes when resizing the window.

**Comment by jtbandes** [comment]
Related to #729

**Comment by amacneil** [comment]
Fixed in https://github.com/foxglove/studio/pull/1046
