### ISSUE TITLE
Drag preview is incorrectly positioned for Rosout panel

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#907]
Somehow this only seems to occur, and occurs consistently, for the Rosout panel and not other panels (at least not the few others I tried).

https://user-images.githubusercontent.com/14237/117725624-17047e00-b181-11eb-9937-2917377efbb8.mov

**Comment by jtbandes** [comment]
Issue still seems to occur, though not always on the Log panel. Blocked on https://bugs.chromium.org/p/chromium/issues/detail?id=1208623.

**Comment by defunctzombie** [comment]
@jtbandes Are you still able to reproduce? I tried today by dragging the log panel around but didn't notice the same behavior. If you are able to reproduce please indicate the steps taken.

**Comment by jtbandes** [comment]
There's definitely still some bugginess around this. This is the "all panels" layout:

https://user-images.githubusercontent.com/14237/188714258-63b44594-1765-4164-baef-0f9abfbc408d.mov

**Comment by jtbandes** [comment]
However it doesn't seem like we can do much here and the issue is minor, so I guess we can close it

**Comment by jtbandes** [comment]
Encountered this again today.

https://user-images.githubusercontent.com/14237/188952296-c6143119-5dcc-493d-889e-c734c1f3b6a0.mov
