### ISSUE TITLE
Plot "following view width" setting doesn't work

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#916]
This code was mistakenly removed in the chart.js v3 upgrade #341. The X range setting no longer works.

https://github.com/cruise-automation/webviz/blob/2925a6fe8efaf8b95db2ecdd64130239818093e5/packages/webviz-core/src/components/TimeBasedChart/index.js#L414-L419

**Comment by defunctzombie** [comment]
@jtbandes What should that setting toggle? The current chart will follow the latest current time value (for live updating data).

**Comment by jtbandes** [comment]
The `defaultView.width` is currently not used at all. It's supposed to let you configure the width of the sliding window / the amount of data displayed at once.
