### ISSUE TITLE
Regression: EXCEPTION_ACCESS_VIOLATION_READ

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#923]
Our font segfaults are back. Likely some fallout from https://github.com/foxglove/studio/pull/888 and related issues https://github.com/foxglove/studio/pull/910

Marking as a bug since this is a regression which we know causes the app to not work.

https://sentry.io/organizations/foxglove/issues/2395586660/?environment=production&project=5649767
https://sentry.io/organizations/foxglove/issues/2395585095/?environment=production&project=5649767

**Comment by amacneil** [comment]
I can take a look at this
