### ISSUE TITLE
Proliferation of "unnamed" layouts

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#924]
A few of us have noted the layouts menu tends to fill up with "unnamed" layouts over time. The root cause is unknown (possibly related to loading the Welcome layout?) but it seems like a real issue that bears investigating.

**Comment by defunctzombie** [comment]
I'm thinking we mark this as closed since you've re-worked the layout save/load flow. I suspect this was a one-time occurrence with a version of main we had. If you think this still requires investigation or have a case to repro please re-open.

**Comment by amacneil** [comment]
It was still happening for me in the last version. I will have a play and see if I can repro.
