### ISSUE TITLE
Improve contrast ratio of brand font

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#955]
The brand purple `#9a74f2` currently fails the [contrast checker](https://contrastchecker.com/) but if you push it ever so slightly towards white to `#B199FF` you can get it to pass all the criteria

<img width="1312" alt="Screen Shot 2021-05-15 at 6 24 12 AM" src="https://user-images.githubusercontent.com/924528/118325016-2ea78200-b546-11eb-9731-ead471d26faa.png">

<img width="926" alt="Screen Shot 2021-05-15 at 6 13 12 AM" src="https://user-images.githubusercontent.com/924528/118324011-cc01b680-b544-11eb-8013-bd58ad4cb2e4.png">

**Comment by amacneil** [comment]
Thanks. I pushed it a more still to `#b8aefd` in https://github.com/foxglove/studio/pull/952, and https://contrastchecker.com/ seems to be happy now.
