### ISSUE TITLE
Allow overriding the default theme in ThemeProvider

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#974]
Add the ability for a user of <ThemeProvider> to override the theme with their own.

Move theme provider into components folder. The default theme can remain in the theme folder.

**Comment by jtbandes** [comment]
By "a user", do you mean a developer or an end user?

**Comment by defunctzombie** [comment]
Eventually both - but this issue is specifically by a developer. Rather than hard-code the theme in the theme provider the theme provider accepts a _value_. The thinking was to allow theming within the environment by a developer - but maybe this ticket is better focused on allowing _end user_ theming.

**Comment by jtbandes** [comment]
I think now that we have dark and light mode, the groundwork is laid for any further theme customizability. Any further development would need to be driven by specific feature requests.
