### ISSUE TITLE
Delete global.scss

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#986]
Rather than overriding some components via a global.scss file, move styles into the component implementation and leverage theme where possible. Global css has a way of leaking into too many elements.

- [ ] rc-color-picker: https://github.com/foxglove/studio/blob/main/app/styles/global.scss#L19
- [ ] button: https://github.com/foxglove/studio/blob/main/app/styles/global.scss#L19, https://github.com/foxglove/studio/blob/main/app/styles/global.scss#L184
- [ ] tables: https://github.com/foxglove/studio/blob/main/app/styles/global.scss#L217

Injecting a css _reset_ or normalize and fonts should be provided via components - see https://material-ui.com/components/css-baseline/ This allows end users to opt in to such resets in a react friendly manner.

**Comment by amacneil** [comment]
Completed in https://github.com/foxglove/studio/pull/1546
