### ISSUE TITLE
Migrate Data Source Info panel into Connection sidebar

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#996]
Now that we have the Connection sidebar, it would be a logical place to show information about the current connection.

I propose removing the Data Source Info panel, and surfacing this information in the Connection sidebar for the active connection. It might need some layout adjustment to make sense given the sidebar width.

![image](https://user-images.githubusercontent.com/637671/118529210-1b3c1880-b6f8-11eb-9696-a631538df5c3.png)

**Comment by amacneil** [comment]
Still think we should do this

**Comment by 2metres** [comment]
<img width="355" alt="Screen Shot 2022-03-22 at 1 59 12 pm" src="https://user-images.githubusercontent.com/924528/159399145-906f5630-30ea-4d88-8211-83765a88340a.png">
